// fileTemplates.js — starter skeletons for each new-file kind.
//
// Exported as a plain map from kind → string so callers don't need to import
// everything. The template for 'ato' is defined here (no editorRouter.js
// exists in this tree) and re-exported alongside the others.
//
// Rules:
//  - Each template must be a non-empty string.
//  - The first line must contain a recognisable marker (see fileTemplates.test.js).
//  - Keep skeletons minimal — just enough to compile / parse without errors.

/** @type {Record<string, string>} */
export const FILE_TEMPLATES = {
  // HDL — VHDL
  hdl_vhdl: `-- VHDL entity + architecture skeleton
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity Untitled is
  port (
    clk : in  STD_LOGIC;
    rst : in  STD_LOGIC;
    y   : out STD_LOGIC
  );
end entity Untitled;

architecture Behavioral of Untitled is
begin
  process(clk, rst)
  begin
    if rst = '1' then
      y <= '0';
    elsif rising_edge(clk) then
      y <= '0';
    end if;
  end process;
end architecture Behavioral;
`,

  // HDL — Verilog
  hdl_verilog: `// Verilog module skeleton
module Foo (
  input  wire clk,
  input  wire rst,
  output reg  y
);
  always @(posedge clk or posedge rst) begin
    if (rst)
      y <= 1'b0;
    else
      y <= 1'b0;
  end
endmodule
`,

  // HDL — SystemVerilog (plc_ld re-uses hdl kind; sv is a dedicated variant)
  hdl_sv: `// SystemVerilog module skeleton
module Foo (
  input  logic clk,
  input  logic rst,
  output logic y
);
  always_ff @(posedge clk or posedge rst) begin
    if (rst)
      y <= '0;
    else
      y <= '0;
  end
endmodule
`,

  // Arduino / embedded sketch
  sketch_ino: `// Arduino sketch
void setup() {
  // put your setup code here, to run once:
}

void loop() {
  // put your main code here, to run repeatedly:
}
`,

  // C firmware / embedded
  firmware_c: `/* C source — minimal main */
#include <stdint.h>

int main(void) {
  return 0;
}
`,

  // C++ firmware / embedded
  firmware_cpp: `// C++ source — minimal main
#include <cstdint>

int main() {
  return 0;
}
`,

  // SPICE netlist
  spice_netlist: `* SPICE deck — Untitled circuit
* ----------------------------------------
* Netlist goes here.
*
* Example: voltage divider
VIN  IN  0  DC 5V
R1   IN  MID  10k
R2   MID  0   10k
*
.op
.end
`,

  // Firmware project descriptor (kerf.fw.json, T-230 schema)
  firmware_project: `{
  "version": 1,
  "name": "untitled-firmware",
  "target": {
    "arch": "arm-none-eabi",
    "mcu": "stm32f4xx",
    "flash_kb": 512,
    "ram_kb": 128
  },
  "build": {
    "toolchain": "gcc",
    "standard": "c11",
    "sources": ["main.c"],
    "include_dirs": [],
    "defines": []
  },
  "rtos": null,
  "debug": {
    "probe": "stlink",
    "svd": null
  }
}
`,

  // Atopile — hardware description language module
  ato: `# atopile module skeleton
import Power from "generics/interfaces.ato"

module Untitled:
    power = new Power

    # Add signals and sub-modules here
`,

  // IEC 61131-3 Structured Text program
  plc_st: `(* IEC 61131-3 Structured Text program skeleton *)
PROGRAM Untitled
VAR
  (* declare variables here *)
  counter : INT := 0;
END_VAR

(* main body *)
counter := counter + 1;

END_PROGRAM
`,

  // PLCopen XML wrapper for an empty program
  plc_ld: `<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://www.plcopen.org/xml/tc6_0201">
  <fileHeader companyName="" productName="kerf" productVersion="1" creationDateTime=""/>
  <contentHeader name="Untitled" modificationDateTime="">
    <coordinateInfo>
      <fbd><scaling x="1" y="1"/></fbd>
      <ld><scaling x="1" y="1"/></ld>
      <sfc><scaling x="1" y="1"/></sfc>
    </coordinateInfo>
  </contentHeader>
  <types><dataTypes/><pous/></types>
  <instances>
    <configurations>
      <configuration name="Config">
        <resource name="Resource">
          <task name="MainTask" priority="1" interval="T#20ms">
            <pouInstance name="MainProgram" typeName="Untitled"/>
          </task>
          <pouInstance name="MainProgram" typeName="Untitled"/>
        </resource>
      </configuration>
    </configurations>
  </instances>
</project>
`,

  // GDS layout (binary format — provide a note-only text stub)
  gds_layout: `# GDS-II layout file
# Binary GDSII format — edit with a dedicated layout tool (KLayout, Magic, etc.)
# This stub is a placeholder; the real .gds file must be generated by your EDA flow.
`,

  // LEF library (Liberty Exchange Format)
  lef_lib: `# LEF library — technology/cell definitions
VERSION 5.8 ;
BUSBITCHARS "[]" ;
DIVIDERCHAR "/" ;

# Add MACRO (cell) definitions here.

END LIBRARY
`,

  // DEF design
  def_design: `# DEF design file
VERSION 5.8 ;
DIVIDERCHAR "/" ;
BUSBITCHARS "[]" ;

DESIGN Untitled ;
UNITS DISTANCE MICRONS 1000 ;

# COMPONENTS, NETS, PINS, etc. go here.

END DESIGN
`,

  // Liberty timing library
  liberty_lib: `/* Liberty timing library skeleton */
library (untitled) {
  time_unit : "1ns";
  voltage_unit : "1V";
  current_unit : "1mA";
  capacitive_load_unit (1, pf);

  /* cell definitions go here */
  cell (INV) {
    area : 1.0;
    pin (A) { direction : input; capacitance : 0.01; }
    pin (Y) { direction : output;
      timing() {
        related_pin : "A";
        timing_sense : negative_unate;
        cell_rise (scalar) { values ("0.1"); }
        cell_fall (scalar) { values ("0.1"); }
      }
    }
  }
}
`,

  // Silicon flow descriptor
  silicon_flow: `{
  "version": 1,
  "name": "untitled-flow",
  "pdk": null,
  "steps": [
    { "tool": "yosys",   "script": "synth.tcl" },
    { "tool": "openroad","script": "floorplan.tcl" },
    { "tool": "openroad","script": "place_route.tcl" },
    { "tool": "klayout", "script": "drc.tcl" }
  ],
  "outputs": ["gds", "lef", "def", "sdf"]
}
`,

  // Silicon PDK descriptor
  silicon_pdk: `{
  "version": 1,
  "name": "untitled-pdk",
  "foundry": "",
  "node_nm": null,
  "layers": [],
  "design_rules": {},
  "standard_cells": null
}
`,
}

/**
 * Return the starter template string for a given file kind, or an empty string
 * if no template is defined for that kind.
 *
 * @param {string} kind  — file kind (e.g. 'hdl_vhdl', 'spice_netlist', …)
 * @returns {string}
 */
export function getTemplate(kind) {
  return FILE_TEMPLATES[kind] ?? ''
}
