/**
 * plcSimBridge — fetch wrapper around the /api/plc/sim/* backend routes.
 *
 * All public functions return a normalised object:
 *   { ok: boolean, outputs, trace, last_state, session_id, errors, status }
 *
 * Network errors and non-2xx HTTP responses are caught and surfaced
 * through the `errors` array rather than thrown, so callers can render
 * degraded UI without try/catch boilerplate.
 */

const API_URL: string = (typeof import.meta !== 'undefined' && import.meta.env?.VITE_API_URL) || ''

// ── Shapes ─────────────────────────────────────────────────────────────────
//
// Not part of api.js's ~80 documented endpoints (src/types/api.ts), so these are kept local
// rather than appended there — this module hits its own /api/plc/sim/* routes directly.

/** One simulated scan-cycle's recorded I/O, as returned in `trace[]`. */
export interface PlcSimTraceEntry {
  tick: number
  outputs: Record<string, unknown>
  inputs: Record<string, unknown>
  [key: string]: unknown
}

export interface StepSimOptions {
  program: string
  inputs?: Record<string, unknown>
  tick_count?: number
  session_id?: string | null
}

export interface StepSimResult {
  ok: boolean
  status: number
  session_id: string | null
  outputs: Record<string, unknown>
  trace: PlcSimTraceEntry[]
  last_state: Record<string, unknown>
  errors: string[]
}

export interface LoadFixtureResult {
  ok: boolean
  status: number
  name: string
  program: string
  inputs: unknown[]
  description: string
  errors: string[]
}

/**
 * Run tick_count scan cycles of a PLC program.
 *
 * @param opts.program     — IEC 61131-3 ST source
 * @param opts.inputs      — map of input variable name → value
 * @param opts.tick_count  — number of ticks to simulate (default 1)
 * @param opts.session_id  — opaque session token (auto-generated by
 *                           server on first call; pass back to
 *                           maintain state across calls)
 */
export async function stepSim({ program, inputs = {}, tick_count = 1, session_id = null }: StepSimOptions): Promise<StepSimResult> {
  try {
    const body: { program: string; inputs: Record<string, unknown>; tick_count: number; session_id?: string } = { program, inputs, tick_count }
    if (session_id) body.session_id = session_id

    const res = await fetch(`${API_URL}/api/plc/sim/step`, {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify(body),
    })

    const status = res.status

    if (!res.ok) {
      let detail: string = `HTTP ${status}`
      try {
        const errBody = await res.json()
        detail = errBody?.detail ?? detail
      } catch { /* ignore JSON parse failure */ }
      return {
        ok: false,
        status,
        session_id: session_id ?? null,
        outputs: {},
        trace: [],
        last_state: {},
        errors: [detail],
      }
    }

    const data = await res.json()
    return {
      ok: data.ok ?? true,
      status,
      session_id: data.session_id ?? session_id,
      outputs: data.outputs ?? {},
      trace: data.trace ?? [],
      last_state: data.last_state ?? {},
      errors: data.errors ?? [],
    }
  } catch (err) {
    // Network error (DNS failure, CORS, offline, etc.)
    return {
      ok: false,
      status: 0,
      session_id: session_id ?? null,
      outputs: {},
      trace: [],
      last_state: {},
      errors: [err?.message ?? 'Network error'],
    }
  }
}

/**
 * Load a pre-bundled fixture program from the backend.
 *
 * @param name — fixture name, e.g. "blinker" or "conveyor"
 */
export async function loadFixture(name: string): Promise<LoadFixtureResult> {
  try {
    const res = await fetch(`${API_URL}/api/plc/sim/load_fixture`, {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify({ name }),
    })

    const status = res.status

    if (!res.ok) {
      let detail: string = `HTTP ${status}`
      try {
        const errBody = await res.json()
        detail = errBody?.detail ?? detail
      } catch { /* ignore */ }
      return { ok: false, status, name, program: '', inputs: [], description: '', errors: [detail] }
    }

    const data = await res.json()
    return {
      ok: data.ok ?? true,
      status,
      name: data.name ?? name,
      program: data.program ?? '',
      inputs: data.inputs ?? [],
      description: data.description ?? '',
      errors: [],
    }
  } catch (err) {
    return {
      ok: false,
      status: 0,
      name,
      program: '',
      inputs: [],
      description: '',
      errors: [err?.message ?? 'Network error'],
    }
  }
}
