// zebraMaterial.js — Class-A zebra / reflection-line ShaderMaterial for the
// Three.js viewport.
//
// Simulates the zebra-stripe lighting analysis tool used in automotive surface
// modelling (Class-A). Stripes are generated by sampling how the view-space
// reflection of the surface normal aligns with a periodic stripe axis, creating
// the visual equivalent of reflecting a parallel-stripe environment map.
//
// Usage:
//   import { createZebraMaterial } from '../lib/zebraMaterial.js'
//   const mat = createZebraMaterial()
//   mesh.material = mat
//   // later:
//   mat.uniforms.stripeCount.value = 12
//   mat.uniforms.stripeAxis.value.set(0, 1)   // 0=horizontal, 1=vertical
//   mat.dispose()

import * as THREE from 'three'

/**
 * Factory: returns a new THREE.ShaderMaterial that draws zebra reflection
 * stripes. The material is side=DoubleSide so back-faces are analysed too.
 *
 * Configurable uniforms:
 *   stripeCount  {float}  number of black+white stripe pairs   default: 8
 *   stripeAxis   {vec2}   2-D axis in view space that defines stripe direction
 *                         (0,1)=vertical bands, (1,0)=horizontal bands  default: (0,1)
 *   color0       {vec3}   colour of dark stripe     default: near-black  (0.04, 0.04, 0.04)
 *   color1       {vec3}   colour of bright stripe   default: near-white  (0.96, 0.96, 0.96)
 *
 * @returns {THREE.ShaderMaterial}
 */
export function createZebraMaterial({
  stripeCount = 8,
  stripeAxis = [0, 1],
  color0 = [0.04, 0.04, 0.04],
  color1 = [0.96, 0.96, 0.96],
} = {}) {
  return new THREE.ShaderMaterial({
    side: THREE.DoubleSide,
    uniforms: {
      stripeCount: { value: stripeCount },
      stripeAxis:  { value: new THREE.Vector2(...stripeAxis) },
      color0:      { value: new THREE.Vector3(...color0) },
      color1:      { value: new THREE.Vector3(...color1) },
    },
    vertexShader: /* glsl */`
      varying vec3 vViewNormal;
      varying vec3 vViewDir;

      void main() {
        // Transform normal and position into view (camera) space.
        vec4 mvPosition = modelViewMatrix * vec4(position, 1.0);
        vViewDir    = normalize(-mvPosition.xyz);

        // normalMatrix is the inverse-transpose of the upper-left 3x3 of
        // modelViewMatrix — already available as a built-in in Three.js.
        vViewNormal = normalize(normalMatrix * normal);

        gl_Position = projectionMatrix * mvPosition;
      }
    `,
    fragmentShader: /* glsl */`
      uniform float  stripeCount;
      uniform vec2   stripeAxis;
      uniform vec3   color0;
      uniform vec3   color1;

      varying vec3 vViewNormal;
      varying vec3 vViewDir;

      void main() {
        // Ensure the normal faces the viewer (handle back-faces gracefully).
        vec3 N = normalize(vViewNormal);
        if (dot(N, vViewDir) < 0.0) N = -N;

        // Reflect the view direction in the surface normal — this gives the
        // direction of the incoming ray that a perfect mirror at this point
        // would redirect toward the viewer. Classic environment-map reflection.
        vec3 R = reflect(-vViewDir, N);

        // Project the reflection direction onto the stripe axis in view space.
        // Using only the xy components gives a screen-tangent stripe field
        // that is consistent regardless of depth — same visual as holding a
        // fluorescent-tube board perpendicular to the camera.
        vec2 axisN = normalize(stripeAxis);
        float t = dot(R.xy, axisN);

        // Map t ∈ [-1, 1] → [0, 1] and repeat stripeCount times.
        float phase = fract((t * 0.5 + 0.5) * stripeCount);

        // Hard edge at 0.5 → classic sharp zebra bands.
        float band = step(0.5, phase);

        vec3 col = mix(color0, color1, band);
        gl_FragColor = vec4(col, 1.0);
      }
    `,
  })
}
