"""
kerf_firmware.rtos.freertos_main_template — Python string template for FreeRTOS main.c.

No Jinja dependency: uses stdlib string.Template (${VAR} syntax).
The template is expanded by c_codegen.generate_freertos_main().

Template variables
------------------
${INCLUDES}         — #include directives
${TASK_HANDLES}     — TaskHandle_t declarations
${MUTEX_HANDLES}    — SemaphoreHandle_t declarations (mutexes)
${SEMAPHORE_HANDLES} — SemaphoreHandle_t declarations (semaphores)
${QUEUE_HANDLES}    — QueueHandle_t declarations
${TASK_PROTOS}      — Forward declarations of task entry functions
${MAIN_BODY}        — Body of main(): xTaskCreate / xSemaphoreCreate / xQueueCreate calls
"""

FREERTOS_MAIN_TEMPLATE = """\
/* Auto-generated by kerf-firmware — DO NOT EDIT */
/* Generated with kerf_firmware.rtos.c_codegen */

#include "FreeRTOS.h"
#include "task.h"
#include "semphr.h"
#include "queue.h"
${INCLUDES}

/* Task handles */
${TASK_HANDLES}

/* Mutex handles */
${MUTEX_HANDLES}

/* Semaphore handles */
${SEMAPHORE_HANDLES}

/* Queue handles */
${QUEUE_HANDLES}

/* Task entry-function forward declarations */
${TASK_PROTOS}

int main(void)
{
${MAIN_BODY}
    /* Start the FreeRTOS scheduler — does not return */
    vTaskStartScheduler();
    for (;;);
    return 0;
}
"""
