"""make_usb_macro_keyboard — LLM tool: generate a USB-HID macro keyboard sketch.

Emits a complete Arduino-compatible sketch (.ino) that uses the Kerf
USB-HID class driver (kerf_usb_hid.h) to implement a macro key that
sends a configurable HID keycode when a button is pressed.

Supported ``send`` values (HID keycodes):
  F1–F12, F13–F24, letters A–Z, digits 1–9, Enter, Space, Escape, and
  arbitrary 0x00–0xFF hex literals ("0x68" → F13).

Parameters
----------
spec : str | dict
    Natural-language string or a dict with keys:
      button_pin  — digital pin (default 2)
      send        — key to send, e.g. "F13", "A", "Enter" (default "F13")
      modifier    — modifier string, e.g. "ctrl", "shift+ctrl" (default "")
      board       — board slug (default "teensy40")

Returns
-------
  {"sketch": str, "manifest": dict, "keycode": int, "descriptor_note": str}
  {"error": str, "spec": str}   on unresolvable spec

Notes
-----
The HID keyboard boot-protocol report descriptor is summarised in the
returned ``descriptor_note`` field so callers / tests can verify the
expected HID Usage Page + Usage for keyboard (0x01/0x06) without parsing
binary descriptors.

F13 = HID keycode 0x68 (USB HID Usage Tables 1.4 §10).
"""
from __future__ import annotations

import re
from typing import Any

from ..project_manifest import make_manifest


# ── HID keycode table ──────────────────────────────────────────────────────────

_KEY_TABLE: dict[str, int] = {
    "a": 0x04, "b": 0x05, "c": 0x06, "d": 0x07, "e": 0x08, "f": 0x09,
    "g": 0x0A, "h": 0x0B, "i": 0x0C, "j": 0x0D, "k": 0x0E, "l": 0x0F,
    "m": 0x10, "n": 0x11, "o": 0x12, "p": 0x13, "q": 0x14, "r": 0x15,
    "s": 0x16, "t": 0x17, "u": 0x18, "v": 0x19, "w": 0x1A, "x": 0x1B,
    "y": 0x1C, "z": 0x1D,
    "1": 0x1E, "2": 0x1F, "3": 0x20, "4": 0x21, "5": 0x22,
    "6": 0x23, "7": 0x24, "8": 0x25, "9": 0x26, "0": 0x27,
    "enter": 0x28, "return": 0x28,
    "esc": 0x29, "escape": 0x29,
    "space": 0x2C,
    "f1": 0x3A, "f2": 0x3B, "f3": 0x3C, "f4": 0x3D,
    "f5": 0x3E, "f6": 0x3F, "f7": 0x40, "f8": 0x41,
    "f9": 0x42, "f10": 0x43, "f11": 0x44, "f12": 0x45,
    "f13": 0x68, "f14": 0x69, "f15": 0x6A, "f16": 0x6B,
    "f17": 0x6C, "f18": 0x6D, "f19": 0x6E, "f20": 0x6F,
    "f21": 0x70, "f22": 0x71, "f23": 0x72, "f24": 0x73,
}

_MODIFIER_TABLE: dict[str, int] = {
    "lctrl": 0x01, "ctrl": 0x01, "control": 0x01,
    "lshift": 0x02, "shift": 0x02,
    "lalt": 0x04, "alt": 0x04,
    "lgui": 0x08, "gui": 0x08, "win": 0x08, "cmd": 0x08,
    "rctrl": 0x10, "rshift": 0x20, "ralt": 0x40, "rgui": 0x80,
}


def _resolve_keycode(send: str) -> int:
    """Resolve a key name / hex literal to a HID keycode integer."""
    s = send.strip().lower()
    # Hex literal: "0x68"
    if s.startswith("0x") or s.startswith("0X"):
        return int(s, 16)
    # Decimal literal
    if s.isdigit():
        return int(s)
    return _KEY_TABLE.get(s, 0x00)


def _resolve_modifier(modifier_str: str) -> int:
    """Resolve a modifier string like "ctrl+shift" to a bitmask."""
    result = 0
    for part in re.split(r'[+\s,|]+', modifier_str.lower()):
        part = part.strip()
        if part:
            result |= _MODIFIER_TABLE.get(part, 0)
    return result


def _extract_board(spec: str, default: str = "teensy40") -> str:
    s = spec.lower()
    if "pro micro" in s or "promicro" in s or "32u4" in s:
        return "pro-micro-32u4"
    if "teensy 4" in s or "teensy4" in s or "teensy40" in s:
        return "teensy40"
    if "rp2040" in s or "pico" in s:
        return "raspberry-pi-pico"
    if "samd21" in s:
        return "samd21-mini"
    if "nrf" in s:
        return "nrf52840-feather"
    return default


def _backend_for_board(board_slug: str) -> str:
    lufa_boards = {"pro-micro-32u4", "arduino-leonardo", "arduino-micro"}
    return "lufa" if board_slug in lufa_boards else "tinyusb"


# ── sketch template ─────────────────────────────────────────────────────────────

_MACRO_KB_TEMPLATE = """\
/*
 * USB-HID Macro Keyboard — generated by Kerf make_usb_macro_keyboard
 * Spec: {spec}
 * Backend: {backend}
 *
 * Wiring: button on pin {button_pin} (INPUT_PULLUP, active-low).
 * On press: sends HID keycode 0x{keycode:02X} ({key_name}) with modifier 0x{modifier:02X}.
 * On release: sends all-zeros (key-up) report.
 *
 * HID Report Descriptor note:
 *   Usage Page (Generic Desktop, 0x01), Usage (Keyboard, 0x06).
 *   8-byte boot-protocol report: [modifier, 0x00, key0, key1, key2, key3, key4, key5].
 *   F13 = keycode 0x68 per USB HID Usage Tables 1.4 §10 (Keyboard/Keypad page).
 */

#include "kerf_usb_hid.h"

static const uint8_t BUTTON_PIN  = {button_pin};
static const uint8_t HID_MOD     = 0x{modifier:02X};
static const uint8_t HID_KEYCODE = 0x{keycode:02X};

static uint8_t _last_btn = 1;

void setup() {{
    pinMode(BUTTON_PIN, INPUT_PULLUP);
    kerf_usb_hid_init();
}}

void loop() {{
    kerf_usb_hid_task();
    uint8_t btn = digitalRead(BUTTON_PIN);
    if (btn != _last_btn) {{
        _last_btn = btn;
        if (btn == 0) {{
            kerf_usb_hid_keyboard_press(HID_MOD, HID_KEYCODE);
        }} else {{
            kerf_usb_hid_keyboard_release();
        }}
    }}
}}
"""

# ── public API ────────────────────────────────────────────────────────────────

_DESCRIPTOR_NOTE = (
    "HID boot-protocol keyboard: Usage Page (Generic Desktop, 0x01), "
    "Usage (Keyboard, 0x06). 8-byte report: [modifier, reserved, "
    "keycode0..keycode5]. F13 = 0x68 (USB HID Usage Tables 1.4 §10)."
)


def make_usb_macro_keyboard(spec: str | dict) -> dict[str, Any]:
    """Generate a USB-HID macro keyboard Arduino sketch.

    Dict form::

        make_usb_macro_keyboard({"button_pin": 2, "send": "F13"})

    String form::

        make_usb_macro_keyboard("button on pin 3, send F13, board pico")

    Returns
    -------
    dict with keys:
      sketch          — .ino source code (str)
      manifest        — kerf.fw.json manifest (dict)
      keycode         — resolved HID keycode integer
      descriptor_note — plain-text summary of the HID report descriptor
    """
    if isinstance(spec, dict):
        params_dict = spec
        spec_str = str(spec)
    else:
        params_dict = {}
        spec_str = spec

    # --- extract parameters ---------------------------------------------------
    # button_pin
    button_pin = params_dict.get("button_pin")
    if button_pin is None:
        m = re.search(r'\bpin\s*[=:]?\s*(\d+)\b', spec_str, re.IGNORECASE)
        button_pin = int(m.group(1)) if m else 2

    # send (key name or code)
    send = params_dict.get("send")
    if send is None:
        m = re.search(r'\bsend\s+([A-Za-z0-9_]+)', spec_str, re.IGNORECASE)
        send = m.group(1) if m else "F13"

    # modifier
    modifier_str = params_dict.get("modifier", "")
    if not modifier_str:
        m = re.search(r'\bmodifier\s*[=:]\s*(\S+)', spec_str, re.IGNORECASE)
        if m:
            modifier_str = m.group(1)

    # board
    board = params_dict.get("board") or _extract_board(spec_str)
    backend = _backend_for_board(board)

    # --- resolve keycode / modifier -------------------------------------------
    keycode = _resolve_keycode(str(send))
    modifier = _resolve_modifier(str(modifier_str))
    key_name = str(send).upper()

    # --- emit sketch ----------------------------------------------------------
    try:
        sketch = _MACRO_KB_TEMPLATE.format(
            spec=spec_str,
            backend=backend,
            button_pin=button_pin,
            keycode=keycode,
            modifier=modifier,
            key_name=key_name,
        )
        manifest = make_manifest(
            name="usb-hid-macro-keyboard",
            board=board,
            libraries=[{"name": "kerf-usb-hid", "version": "1.0.0"}],
            sources=["sketch/usb_macro_keyboard.ino"],
            build_flags=["-DKERF_USB_BACKEND_" + backend.upper()],
            monitor_speed=0,
        )
    except Exception as exc:
        return {"error": str(exc), "spec": spec_str}

    return {
        "sketch": sketch,
        "manifest": manifest,
        "keycode": keycode,
        "descriptor_note": _DESCRIPTOR_NOTE,
    }
