"""make_usb_midi_controller — LLM tool: generate a USB-MIDI controller sketch.

Emits a complete Arduino-compatible sketch (.ino) that uses the Kerf
USB-MIDI class driver (kerf_usb_midi.h) to implement a simple MIDI
controller.

Supported spec patterns (case-insensitive):
  "note button"  / "button note"  — button on a pin sends a Note-On/Off
  "cc knob"      / "knob cc"      — potentiometer sends Control-Change
  "cc button"    / "button cc"    — button sends CC toggle (0/127)
  Default (unrecognised) falls back to the "note button" pattern.

Parameters extracted from spec (with sensible defaults):
  button_pin   — digital pin for the button (default 2)
  note         — MIDI note number (default 60 = Middle C)
  velocity     — MIDI velocity (default 100)
  channel      — MIDI channel 0–15 (default 0)
  control      — CC number (default 1 = Modulation)
  pot_pin      — analog pin for potentiometer (default A0)
  board        — target board slug (default "teensy40")

Returns
-------
  {"sketch": str, "manifest": dict, "backend": str}   on success
  {"error": str, "spec": str}                          on hard failure
"""
from __future__ import annotations

import re
from typing import Any

from ..project_manifest import make_manifest


# ── helpers ────────────────────────────────────────────────────────────────────

def _extract_int(spec: str, keyword: str, default: int) -> int:
    """Extract an integer following *keyword* in *spec*."""
    pattern = rf'\b{re.escape(keyword)}\s*[=:]\s*(\d+)\b'
    m = re.search(pattern, spec, re.IGNORECASE)
    if m:
        return int(m.group(1))
    # Bare integer after a common noun
    alt = rf'\b{re.escape(keyword)}\s+(\d+)\b'
    m2 = re.search(alt, spec, re.IGNORECASE)
    if m2:
        return int(m2.group(1))
    return default


def _extract_board(spec: str, default: str = "teensy40") -> str:
    """Identify a target board slug mentioned in *spec*."""
    spec_lower = spec.lower()
    if "pro micro" in spec_lower or "promicro" in spec_lower or "32u4" in spec_lower:
        return "pro-micro-32u4"
    if "teensy 4" in spec_lower or "teensy4" in spec_lower or "teensy40" in spec_lower:
        return "teensy40"
    if "rp2040" in spec_lower or "pico" in spec_lower:
        return "raspberry-pi-pico"
    if "samd21" in spec_lower:
        return "samd21-mini"
    if "nrf" in spec_lower:
        return "nrf52840-feather"
    return default


def _backend_for_board(board_slug: str) -> str:
    """Return 'tinyusb' or 'lufa' for the given board slug."""
    lufa_boards = {"pro-micro-32u4", "arduino-leonardo", "arduino-micro"}
    return "lufa" if board_slug in lufa_boards else "tinyusb"


# ── sketch templates ────────────────────────────────────────────────────────────

_NOTE_BUTTON_TEMPLATE = """\
/*
 * USB-MIDI Note Controller — generated by Kerf make_usb_midi_controller
 * Spec: {spec}
 * Backend: {backend}
 *
 * Wiring: button on pin {button_pin} (INPUT_PULLUP, active-low)
 * Sends Note-On (note {note}, velocity {velocity}) on press,
 *       Note-Off on release, channel {channel}.
 */

#include "kerf_usb_midi.h"

static const uint8_t BUTTON_PIN = {button_pin};
static const uint8_t MIDI_NOTE  = {note};
static const uint8_t MIDI_VEL   = {velocity};
static const uint8_t MIDI_CH    = {channel};

static uint8_t _last_state = 1;  /* pulled high */

void setup() {{
    pinMode(BUTTON_PIN, INPUT_PULLUP);
    kerf_usb_midi_init();
}}

void loop() {{
    kerf_usb_midi_task();
    uint8_t state = digitalRead(BUTTON_PIN);
    if (state != _last_state) {{
        _last_state = state;
        if (state == 0) {{
            kerf_usb_midi_send_note(MIDI_CH, MIDI_NOTE, MIDI_VEL, 1);
        }} else {{
            kerf_usb_midi_send_note(MIDI_CH, MIDI_NOTE, 0, 0);
        }}
    }}
}}
"""

_CC_KNOB_TEMPLATE = """\
/*
 * USB-MIDI CC Knob — generated by Kerf make_usb_midi_controller
 * Spec: {spec}
 * Backend: {backend}
 *
 * Wiring: potentiometer on analog pin {pot_pin}
 * Sends CC {control} on channel {channel} with value mapped from ADC.
 */

#include "kerf_usb_midi.h"

static const uint8_t POT_PIN   = {pot_pin};
static const uint8_t MIDI_CC   = {control};
static const uint8_t MIDI_CH   = {channel};

static uint8_t _last_cc = 255;

void setup() {{
    kerf_usb_midi_init();
}}

void loop() {{
    kerf_usb_midi_task();
    int adc = analogRead(POT_PIN);
    uint8_t cc_val = (uint8_t)(adc >> 3);  /* 10-bit ADC → 7-bit MIDI */
    if (cc_val != _last_cc) {{
        _last_cc = cc_val;
        kerf_usb_midi_send_cc(MIDI_CH, MIDI_CC, cc_val);
    }}
    delay(5);
}}
"""

_CC_BUTTON_TEMPLATE = """\
/*
 * USB-MIDI CC Button Toggle — generated by Kerf make_usb_midi_controller
 * Spec: {spec}
 * Backend: {backend}
 *
 * Wiring: button on pin {button_pin} (INPUT_PULLUP, active-low)
 * Toggles CC {control} between 0 and 127 on channel {channel}.
 */

#include "kerf_usb_midi.h"

static const uint8_t BUTTON_PIN = {button_pin};
static const uint8_t MIDI_CC    = {control};
static const uint8_t MIDI_CH    = {channel};

static uint8_t _cc_state  = 0;
static uint8_t _last_btn  = 1;

void setup() {{
    pinMode(BUTTON_PIN, INPUT_PULLUP);
    kerf_usb_midi_init();
}}

void loop() {{
    kerf_usb_midi_task();
    uint8_t btn = digitalRead(BUTTON_PIN);
    if (btn == 0 && _last_btn == 1) {{
        _cc_state = _cc_state ? 0 : 127;
        kerf_usb_midi_send_cc(MIDI_CH, MIDI_CC, _cc_state);
    }}
    _last_btn = btn;
    delay(10);
}}
"""


# ── pattern dispatch ─────────────────────────────────────────────────────────

def _make_note_button(spec: str, params: dict) -> tuple[str, dict]:
    sketch = _NOTE_BUTTON_TEMPLATE.format(
        spec=spec,
        backend=params["backend"],
        button_pin=params["button_pin"],
        note=params["note"],
        velocity=params["velocity"],
        channel=params["channel"],
    )
    manifest = make_manifest(
        name="usb-midi-note-button",
        board=params["board"],
        libraries=[{"name": "kerf-usb-midi", "version": "1.0.0"}],
        sources=["sketch/usb_midi_note_button.ino"],
        build_flags=["-DKERF_USB_BACKEND_" + params["backend"].upper()],
        monitor_speed=0,
    )
    return sketch, manifest


def _make_cc_knob(spec: str, params: dict) -> tuple[str, dict]:
    sketch = _CC_KNOB_TEMPLATE.format(
        spec=spec,
        backend=params["backend"],
        pot_pin=params["pot_pin"],
        control=params["control"],
        channel=params["channel"],
    )
    manifest = make_manifest(
        name="usb-midi-cc-knob",
        board=params["board"],
        libraries=[{"name": "kerf-usb-midi", "version": "1.0.0"}],
        sources=["sketch/usb_midi_cc_knob.ino"],
        build_flags=["-DKERF_USB_BACKEND_" + params["backend"].upper()],
        monitor_speed=0,
    )
    return sketch, manifest


def _make_cc_button(spec: str, params: dict) -> tuple[str, dict]:
    sketch = _CC_BUTTON_TEMPLATE.format(
        spec=spec,
        backend=params["backend"],
        button_pin=params["button_pin"],
        control=params["control"],
        channel=params["channel"],
    )
    manifest = make_manifest(
        name="usb-midi-cc-button",
        board=params["board"],
        libraries=[{"name": "kerf-usb-midi", "version": "1.0.0"}],
        sources=["sketch/usb_midi_cc_button.ino"],
        build_flags=["-DKERF_USB_BACKEND_" + params["backend"].upper()],
        monitor_speed=0,
    )
    return sketch, manifest


_PATTERNS: list[tuple[str, Any]] = [
    ("cc knob",     _make_cc_knob),
    ("knob cc",     _make_cc_knob),
    ("knob",        _make_cc_knob),
    ("cc button",   _make_cc_button),
    ("button cc",   _make_cc_button),
    ("note button", _make_note_button),
    ("button note", _make_note_button),
    ("button",      _make_note_button),
    ("note",        _make_note_button),
]


# ── public API ────────────────────────────────────────────────────────────────

def make_usb_midi_controller(spec: str | dict) -> dict[str, Any]:
    """Generate a USB-MIDI controller Arduino sketch from a natural-language
    *spec* or a dict of parameters.

    Dict form (structured)::

        make_usb_midi_controller({
            "button_pin": 2,
            "note": 60,
            "velocity": 100,
            "channel": 0,
            "board": "teensy40"
        })

    String form::

        make_usb_midi_controller("note button on pin 3, note 72, teensy 4")

    Returns ``{"sketch": str, "manifest": dict, "backend": str}`` on success,
    ``{"error": str, "spec": str}`` if the spec cannot be processed.
    """
    if isinstance(spec, dict):
        params_dict = spec
        spec_str = str(spec)
    else:
        params_dict = {}
        spec_str = spec

    board = params_dict.get("board") or _extract_board(spec_str)
    backend = _backend_for_board(board)

    params: dict[str, Any] = {
        "board":      board,
        "backend":    backend,
        "button_pin": params_dict.get("button_pin",
                                       _extract_int(spec_str, "button_pin", 2)),
        "note":       params_dict.get("note",
                                       _extract_int(spec_str, "note", 60)),
        "velocity":   params_dict.get("velocity",
                                       _extract_int(spec_str, "velocity", 100)),
        "channel":    params_dict.get("channel",
                                       _extract_int(spec_str, "channel", 0)),
        "control":    params_dict.get("control",
                                       _extract_int(spec_str, "control", 1)),
        "pot_pin":    params_dict.get("pot_pin",
                                       _extract_int(spec_str, "pot_pin", 14)),  # A0
    }

    spec_lower = spec_str.lower()
    factory = _make_note_button  # default
    for keyword, fn in _PATTERNS:
        if keyword in spec_lower:
            factory = fn
            break

    try:
        sketch, manifest = factory(spec_str, params)
    except Exception as exc:
        return {"error": str(exc), "spec": spec_str}

    return {"sketch": sketch, "manifest": manifest, "backend": backend}
