"""T-47: Jewelry generated-parts render check — kerf-parts library side.

Verifies that PartDoc JSON produced by the jewelry generator (kerf-partsgen)
is consumable by the kerf-parts library render path:

  * KerfPart.to_part_doc() round-trips through JSON with the correct shape
    that the library's ``kind='part'`` files row stores and BOM/library
    queries read back.
  * The jewelry category path (jewelry/<subcategory>) is valid in the model.
  * A generated jewelry PartDoc (synthesised without a live OCCT kernel)
    carries all the keys that the library reader and seed pipeline expect.
  * content_hash is deterministic (no timestamp drift).
  * The generated part's rel_path is suitable for folder-tree seeding.

No OCCT kernel, no network access, no database — pure model/doc validation.
The kernel-gated geometry tests live in kerf-partsgen/tests/.
"""

from __future__ import annotations

import hashlib
import json
import math

import pytest

from kerf_parts.model import KerfPart, part_filename


# ---------------------------------------------------------------------------
# Synthesise a representative generated jewelry PartDoc
# (mirrors kerf_partsgen.seed.part_doc_for_variant output)
# ---------------------------------------------------------------------------

def _make_generated_bangle_part(size: str = "M") -> KerfPart:
    """Build a KerfPart that mirrors what kerf-partsgen seed emits for a bangle."""
    # Reproduce the dimension formula from the generator (inner_circ / π, etc.)
    inner_circs = {"S": 155.0, "M": 165.0, "L": 175.0, "XL": 185.0}
    inner_circ = inner_circs[size]
    inner_d = inner_circ / math.pi
    wall = 3.0
    outer_d = inner_d + 2.0 * wall
    band_w = 6.0
    outer_r = outer_d / 2.0
    inner_r = inner_d / 2.0
    volume = math.pi * (outer_r ** 2 - inner_r ** 2) * band_w

    slug = f"jewelry_plain_bangle-{size}"
    name = f"Jewelry plain round bangle {size}"

    part = KerfPart(
        name=name,
        category="jewelry/bracelets",
        description=(
            f"Jewelry plain round bangle, size {size}, per KERF-JEWELRY. "
            "Generated by kerf-partsgen from the committed parametric "
            "generator jewelry_plain_bangle.py (MIT)."
        ),
        manufacturer="Kerf Workshop",
        mpn=f"KERF-JEWELRYPLAINBANGLE-{size}",
        value=size,
        datasheet_url="",
        distributors=[],
        metadata={
            "standard": "KERF-JEWELRY",
            "units": "mm",
            "params": {
                "inner_diameter": round(inner_d, 3),
                "outer_diameter": round(outer_d, 3),
                "band_width": band_w,
                "wall_thickness": wall,
                "inner_circumference": inner_circ,
            },
            "geometry": {
                "generator": "kerf_partsgen/generators/jewelry_plain_bangle.py",
                "size": size,
                "kernel_step": f".parts-out/jewelry/jewelry_plain_bangle/{slug}/part.step",
                "measured_bbox_mm": [round(outer_d, 3), round(outer_d, 3), band_w],
                "measured_volume_mm3": round(volume, 2),
            },
        },
    )
    part.rel_path = f"kerf-jewelry/bracelets/jewelry_plain_bangle_{size}.part"
    return part


# ===========================================================================
# KerfPart model validation tests
# ===========================================================================


@pytest.mark.parametrize("size", ["S", "M", "L", "XL"])
def test_generated_bangle_to_part_doc_canonical_keys(size):
    """to_part_doc() includes every key that the library kind='part' row stores."""
    part = _make_generated_bangle_part(size)
    doc = part.to_part_doc()
    required = ("version", "name", "description", "category", "manufacturer",
                "mpn", "value", "datasheet_url", "distributors", "metadata")
    for key in required:
        assert key in doc, f"size={size}: PartDoc missing {key!r}"


@pytest.mark.parametrize("size", ["S", "M", "L", "XL"])
def test_generated_bangle_category_under_jewelry(size):
    """Generated bangle category path is under jewelry/ domain."""
    part = _make_generated_bangle_part(size)
    doc = part.to_part_doc()
    assert doc["category"].startswith("jewelry/"), (
        f"size={size}: category {doc['category']!r} not under jewelry/"
    )
    assert doc["category"] == "jewelry/bracelets"


@pytest.mark.parametrize("size", ["S", "M", "L", "XL"])
def test_generated_bangle_doc_version_is_1(size):
    """Library reader expects version == 1."""
    part = _make_generated_bangle_part(size)
    assert part.to_part_doc()["version"] == 1


@pytest.mark.parametrize("size", ["S", "M", "L", "XL"])
def test_generated_bangle_name_contains_size(size):
    """Library BOM uses name for display; name must include the size label."""
    part = _make_generated_bangle_part(size)
    assert size in part.to_part_doc()["name"]


@pytest.mark.parametrize("size", ["S", "M", "L", "XL"])
def test_generated_bangle_mpn_contains_size(size):
    """MPN is used by the BOM to key parts; must include the size."""
    part = _make_generated_bangle_part(size)
    assert size in part.to_part_doc()["mpn"]


# ===========================================================================
# Geometry metadata in the rendered doc
# ===========================================================================


@pytest.mark.parametrize("size", ["S", "M", "L", "XL"])
def test_generated_bangle_geometry_block_present(size):
    """The geometry sub-block is present in metadata (records the generator)."""
    part = _make_generated_bangle_part(size)
    doc = part.to_part_doc()
    geo = doc["metadata"].get("geometry", {})
    assert "generator" in geo, f"size={size}: geometry.generator missing"
    assert "jewelry_plain_bangle" in geo["generator"]


@pytest.mark.parametrize("size", ["S", "M", "L", "XL"])
def test_generated_bangle_measured_bbox_three_positive(size):
    """measured_bbox_mm has exactly three positive values."""
    part = _make_generated_bangle_part(size)
    doc = part.to_part_doc()
    bbox = doc["metadata"]["geometry"]["measured_bbox_mm"]
    assert len(bbox) == 3, f"size={size}: bbox has {len(bbox)} elements"
    assert all(v > 0 for v in bbox), f"size={size}: non-positive bbox {bbox}"


@pytest.mark.parametrize("size", ["S", "M", "L", "XL"])
def test_generated_bangle_measured_volume_positive(size):
    """measured_volume_mm3 is a positive number."""
    part = _make_generated_bangle_part(size)
    doc = part.to_part_doc()
    vol = doc["metadata"]["geometry"]["measured_volume_mm3"]
    assert isinstance(vol, (int, float))
    assert vol > 0, f"size={size}: non-positive volume {vol}"


@pytest.mark.parametrize("size", ["S", "M", "L", "XL"])
def test_generated_bangle_volume_formula_consistent(size):
    """Declared volume in the PartDoc matches the annular-cylinder formula."""
    part = _make_generated_bangle_part(size)
    doc = part.to_part_doc()
    params = doc["metadata"]["params"]
    outer_r = params["outer_diameter"] / 2.0
    inner_r = params["inner_diameter"] / 2.0
    h = params["band_width"]
    expected_vol = math.pi * (outer_r ** 2 - inner_r ** 2) * h
    actual_vol = doc["metadata"]["geometry"]["measured_volume_mm3"]
    assert abs(actual_vol - expected_vol) < 1.0, (
        f"size={size}: doc vol {actual_vol:.2f} vs formula {expected_vol:.2f}"
    )


# ===========================================================================
# Library render-path: rel_path + filename + JSON round-trip
# ===========================================================================


@pytest.mark.parametrize("size", ["S", "M", "L", "XL"])
def test_generated_bangle_rel_path_ends_with_part(size):
    """rel_path ends with .part (library seeder writes this as the filename)."""
    part = _make_generated_bangle_part(size)
    assert part.rel_path.endswith(".part"), (
        f"size={size}: rel_path {part.rel_path!r} does not end with .part"
    )


@pytest.mark.parametrize("size", ["S", "M", "L", "XL"])
def test_generated_bangle_rel_path_has_jewelry_folder(size):
    """rel_path places the part under a jewelry folder path."""
    part = _make_generated_bangle_part(size)
    assert "jewelry" in part.rel_path.lower(), (
        f"size={size}: rel_path {part.rel_path!r} does not include jewelry"
    )


@pytest.mark.parametrize("size", ["S", "M", "L", "XL"])
def test_generated_bangle_doc_roundtrips_json(size):
    """to_part_doc() serialises to JSON without error; key fields survive the trip."""
    part = _make_generated_bangle_part(size)
    doc = part.to_part_doc()
    serialised = json.dumps(doc)
    restored = json.loads(serialised)
    assert restored["category"] == doc["category"]
    assert restored["name"] == doc["name"]
    assert restored["version"] == 1


# ===========================================================================
# Content hash (incremental seed)
# ===========================================================================


@pytest.mark.parametrize("size", ["S", "M", "L", "XL"])
def test_generated_bangle_content_hash_deterministic(size):
    """content_hash is stable across two ensure_hash() calls (no timestamp)."""
    p1 = _make_generated_bangle_part(size)
    p2 = _make_generated_bangle_part(size)
    h1 = p1.ensure_hash()
    h2 = p2.ensure_hash()
    assert h1 == h2, f"size={size}: content_hash unstable ({h1} vs {h2})"


def test_generated_bangle_hash_differs_across_sizes():
    """Content hashes are distinct for distinct sizes (no accidental collision)."""
    hashes = {
        size: _make_generated_bangle_part(size).ensure_hash()
        for size in ("S", "M", "L", "XL")
    }
    assert len(set(hashes.values())) == 4, (
        f"hash collision across sizes: {hashes}"
    )


# ===========================================================================
# part_filename helper
# ===========================================================================


def test_part_filename_sanitises_jewelry_name():
    """part_filename() produces a safe .part filename for a jewelry part name."""
    fn = part_filename("Jewelry plain round bangle XL")
    assert fn.endswith(".part")
    # No shell-unsafe characters.
    for ch in ("/", "\\", " ", "&", "|"):
        assert ch not in fn, f"unsafe char {ch!r} in filename {fn!r}"


# ===========================================================================
# Category vocabulary
# ===========================================================================


def test_jewelry_category_vocabulary_not_mechanical():
    """Generated jewelry parts must NOT land in the mechanical/ category tree."""
    part = _make_generated_bangle_part("M")
    doc = part.to_part_doc()
    assert not doc["category"].startswith("mechanical/"), (
        "jewelry part landed in mechanical/ category: "
        f"{doc['category']!r}"
    )


def test_all_sizes_have_populated_library_doc():
    """Every size produces a non-trivially-empty PartDoc name and description."""
    for size in ("S", "M", "L", "XL"):
        part = _make_generated_bangle_part(size)
        doc = part.to_part_doc()
        assert doc["name"].strip(), f"size={size}: empty name"
        assert doc["description"].strip(), f"size={size}: empty description"
