"""
Native plant species catalog for Kerf landscape design.

Data sources
------------
* Dirr, Michael A. *Manual of Woody Landscape Plants*, 6th ed., Stipes (2009).
  Canonical reference for mature dimensions, zone ranges, and growth rates.
* USDA Plant Hardiness Zone Map (2023 edition) — zone boundaries.
* Dirr & Heuser, *The Reference Manual of Woody Plant Propagation* (2006).
* Lady Bird Johnson Wildflower Center — native plant data.
* Missouri Botanical Garden Plant Finder — supplementary species data.

DISCLAIMER
----------
Species attributes are derived from published reference data (Dirr 2009,
USDA PHZM 2023, Missouri Botanical Garden). This catalog is for landscape
design assistance only and is **NOT USDA certified**. Verify zone suitability
and cultural requirements with local Extension Service offices before
installation.

Public API
----------
lookup_plant(name: str) -> PlantSpecies
    Case-insensitive lookup by common or scientific name.

filter_plants(usda_zone, light, water, kind=None, deer_resistant=None)
    -> list[PlantSpecies]
    Return plants suitable for the given conditions.

plants_for_pollinators(region: 'east'|'west'|'south'|'north')
    -> list[PlantSpecies]
    Pollinator-friendly species per region.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Literal


# ---------------------------------------------------------------------------
# PlantSpecies dataclass
# ---------------------------------------------------------------------------

KindLiteral = Literal[
    "deciduous_tree", "evergreen", "shrub", "perennial", "grass", "groundcover"
]
LightLiteral = Literal["full_sun", "partial_shade", "shade"]
WaterLiteral = Literal["low", "medium", "high"]


@dataclass(frozen=True)
class PlantSpecies:
    """
    Landscape plant with full design-specification attributes.

    Attributes
    ----------
    scientific_name : str
        Binomial (Genus species) following ICN nomenclature.
    common_name : str
        Most widely used common name in North American landscape trade.
    kind : KindLiteral
        Plant category: deciduous_tree / evergreen / shrub / perennial / grass / groundcover.
    mature_height_m : float
        Typical mature height in metres (Dirr midpoint or range mid).
    mature_spread_m : float
        Typical mature canopy spread in metres.
    growth_rate_cm_per_year : float
        Average annual growth rate in cm (slow <30, medium 30-60, fast >60).
    usda_zones_min : int
        Minimum USDA hardiness zone (cold-hardiness limit).
    usda_zones_max : int
        Maximum USDA hardiness zone (heat-tolerance limit).
    light : LightLiteral
        Primary light requirement: full_sun / partial_shade / shade.
    water : WaterLiteral
        Water demand once established: low / medium / high.
    soil_type : str
        Preferred soil texture / drainage (free text, Dirr notes).
    bloom_color : str
        Dominant bloom color, or "none" for non-ornamental / foliage plants.
    deer_resistant : bool
        True when documented as generally deer-resistant in literature.
    notes : str
        Brief landscape design note (Dirr character / use).
    regions : tuple[str, ...]
        Geographic regions where naturally native or well-adapted:
        'east', 'west', 'south', 'north', 'midwest', 'mountain', 'pacific'.
    pollinator_value : str
        Documented pollinator benefit: 'high' / 'medium' / 'low' / 'none'.
        Includes bees, butterflies, hummingbirds, moths.
    """

    scientific_name: str
    common_name: str
    kind: str
    mature_height_m: float
    mature_spread_m: float
    growth_rate_cm_per_year: float
    usda_zones_min: int
    usda_zones_max: int
    light: str
    water: str
    soil_type: str
    bloom_color: str
    deer_resistant: bool
    notes: str = ""
    regions: tuple = ()
    pollinator_value: str = "low"


# ---------------------------------------------------------------------------
# PLANT_CATALOG — 100+ common landscape species (Dirr 2009, USDA PHZM 2023)
#
# Sources: Dirr, MWLP 6th ed. (2009); USDA PHZM (2023); Missouri Botanical Garden.
# NOT USDA certified — for design assistance only.
# ---------------------------------------------------------------------------

PLANT_CATALOG: dict[str, PlantSpecies] = {}


def _add(*species_list: PlantSpecies) -> None:
    for sp in species_list:
        PLANT_CATALOG[sp.scientific_name.lower()] = sp


_add(
    # -----------------------------------------------------------------------
    # DECIDUOUS TREES
    # -----------------------------------------------------------------------
    PlantSpecies(
        scientific_name="Acer rubrum",
        common_name="Red Maple",
        kind="deciduous_tree",
        mature_height_m=22.0,
        mature_spread_m=12.0,
        growth_rate_cm_per_year=60.0,
        usda_zones_min=3,
        usda_zones_max=9,
        light="full_sun",
        water="medium",
        soil_type="Adaptable; moist to wet; tolerates clay",
        bloom_color="red",
        deer_resistant=False,
        notes="Brilliant fall colour; tolerates wet soils; fastest-growing maple (Dirr p. 63).",
        regions=("east", "midwest", "south"),
        pollinator_value="medium",
    ),
    PlantSpecies(
        scientific_name="Quercus alba",
        common_name="White Oak",
        kind="deciduous_tree",
        mature_height_m=24.0,
        mature_spread_m=24.0,
        growth_rate_cm_per_year=30.0,
        usda_zones_min=3,
        usda_zones_max=9,
        light="full_sun",
        water="medium",
        soil_type="Deep, well-drained, acidic loam",
        bloom_color="none",
        deer_resistant=True,
        notes="Long-lived shade tree; critical wildlife mast producer; stunning wine-red fall colour (Dirr p. 830).",
        regions=("east", "midwest", "south"),
        pollinator_value="medium",
    ),
    PlantSpecies(
        scientific_name="Quercus rubra",
        common_name="Red Oak",
        kind="deciduous_tree",
        mature_height_m=21.0,
        mature_spread_m=18.0,
        growth_rate_cm_per_year=60.0,
        usda_zones_min=4,
        usda_zones_max=8,
        light="full_sun",
        water="medium",
        soil_type="Well-drained, acidic; tolerates clay",
        bloom_color="none",
        deer_resistant=False,
        notes="Fastest-growing oak; dependable scarlet fall colour; urban-tolerant (Dirr p. 851).",
        regions=("east", "midwest"),
        pollinator_value="medium",
    ),
    PlantSpecies(
        scientific_name="Cornus florida",
        common_name="Flowering Dogwood",
        kind="deciduous_tree",
        mature_height_m=9.0,
        mature_spread_m=9.0,
        growth_rate_cm_per_year=25.0,
        usda_zones_min=5,
        usda_zones_max=9,
        light="partial_shade",
        water="medium",
        soil_type="Moist, well-drained, acidic, humus-rich",
        bloom_color="white",
        deer_resistant=False,
        notes="Iconic four-season tree; spring bracts, summer berries, fall red; understory native (Dirr p. 316).",
        regions=("east", "south"),
        pollinator_value="medium",
    ),
    PlantSpecies(
        scientific_name="Betula nigra",
        common_name="River Birch",
        kind="deciduous_tree",
        mature_height_m=18.0,
        mature_spread_m=12.0,
        growth_rate_cm_per_year=75.0,
        usda_zones_min=4,
        usda_zones_max=9,
        light="full_sun",
        water="medium",
        soil_type="Moist to wet; acidic; adaptable",
        bloom_color="none",
        deer_resistant=False,
        notes="Exfoliating cinnamon-pink bark; heat-tolerant birch; riparian plantings (Dirr p. 155).",
        regions=("east", "south", "midwest"),
        pollinator_value="medium",
    ),
    PlantSpecies(
        scientific_name="Liquidambar styraciflua",
        common_name="Sweetgum",
        kind="deciduous_tree",
        mature_height_m=24.0,
        mature_spread_m=12.0,
        growth_rate_cm_per_year=60.0,
        usda_zones_min=5,
        usda_zones_max=9,
        light="full_sun",
        water="medium",
        soil_type="Moist, slightly acidic; clay-tolerant",
        bloom_color="none",
        deer_resistant=False,
        notes="Outstanding multicolored fall display; spiky fruit capsules a limitation (Dirr p. 564).",
        regions=("east", "south"),
        pollinator_value="low",
    ),
    PlantSpecies(
        scientific_name="Liriodendron tulipifera",
        common_name="Tulip Poplar",
        kind="deciduous_tree",
        mature_height_m=30.0,
        mature_spread_m=15.0,
        growth_rate_cm_per_year=90.0,
        usda_zones_min=4,
        usda_zones_max=9,
        light="full_sun",
        water="medium",
        soil_type="Deep, moist, well-drained loam",
        bloom_color="yellow-orange",
        deer_resistant=False,
        notes="Tallest eastern hardwood; tulip-shaped flowers at 15+ years; golden fall colour (Dirr p. 573).",
        regions=("east", "south"),
        pollinator_value="high",
    ),
    PlantSpecies(
        scientific_name="Nyssa sylvatica",
        common_name="Black Gum",
        kind="deciduous_tree",
        mature_height_m=15.0,
        mature_spread_m=9.0,
        growth_rate_cm_per_year=30.0,
        usda_zones_min=4,
        usda_zones_max=9,
        light="full_sun",
        water="medium",
        soil_type="Moist, acidic; tolerates wet",
        bloom_color="white",
        deer_resistant=False,
        notes="Best native for early fall colour (scarlet-orange); excellent wildlife value (Dirr p. 635).",
        regions=("east", "south", "midwest"),
        pollinator_value="high",
    ),
    PlantSpecies(
        scientific_name="Platanus occidentalis",
        common_name="American Sycamore",
        kind="deciduous_tree",
        mature_height_m=30.0,
        mature_spread_m=24.0,
        growth_rate_cm_per_year=90.0,
        usda_zones_min=4,
        usda_zones_max=9,
        light="full_sun",
        water="medium",
        soil_type="Moist, deep alluvial; clay-tolerant",
        bloom_color="none",
        deer_resistant=False,
        notes="Massive shade tree; exfoliating bark; riparian buffer; flood-tolerant (Dirr p. 727).",
        regions=("east", "midwest"),
        pollinator_value="low",
    ),
    PlantSpecies(
        scientific_name="Acer saccharum",
        common_name="Sugar Maple",
        kind="deciduous_tree",
        mature_height_m=24.0,
        mature_spread_m=15.0,
        growth_rate_cm_per_year=30.0,
        usda_zones_min=3,
        usda_zones_max=8,
        light="partial_shade",
        water="medium",
        soil_type="Well-drained, slightly acidic; not compaction-tolerant",
        bloom_color="yellow-green",
        deer_resistant=False,
        notes="Spectacular orange-red fall colour; maple syrup source; requires good drainage (Dirr p. 56).",
        regions=("east", "midwest", "north"),
        pollinator_value="medium",
    ),
    PlantSpecies(
        scientific_name="Cercis canadensis",
        common_name="Eastern Redbud",
        kind="deciduous_tree",
        mature_height_m=9.0,
        mature_spread_m=9.0,
        growth_rate_cm_per_year=30.0,
        usda_zones_min=4,
        usda_zones_max=9,
        light="partial_shade",
        water="low",
        soil_type="Well-drained; adaptable; drought-tolerant when established",
        bloom_color="pink",
        deer_resistant=False,
        notes="Stunning magenta-pink bloom before leaf-out; understory size; adaptable (Dirr p. 240).",
        regions=("east", "south", "midwest"),
        pollinator_value="high",
    ),
    PlantSpecies(
        scientific_name="Prunus serotina",
        common_name="Black Cherry",
        kind="deciduous_tree",
        mature_height_m=18.0,
        mature_spread_m=12.0,
        growth_rate_cm_per_year=60.0,
        usda_zones_min=3,
        usda_zones_max=9,
        light="full_sun",
        water="low",
        soil_type="Well-drained, moist; adaptable",
        bloom_color="white",
        deer_resistant=False,
        notes="Largest native cherry; critical wildlife food source; 400+ Lepidoptera host species (Dirr p. 779).",
        regions=("east", "midwest", "south"),
        pollinator_value="high",
    ),
    PlantSpecies(
        scientific_name="Gleditsia triacanthos",
        common_name="Honeylocust",
        kind="deciduous_tree",
        mature_height_m=15.0,
        mature_spread_m=12.0,
        growth_rate_cm_per_year=60.0,
        usda_zones_min=3,
        usda_zones_max=9,
        light="full_sun",
        water="low",
        soil_type="Adaptable; drought, salt, compaction-tolerant",
        bloom_color="none",
        deer_resistant=False,
        notes="Filtered shade; high urban tolerance; thornless varieties preferred (Dirr p. 477).",
        regions=("east", "midwest", "south"),
        pollinator_value="medium",
    ),
    PlantSpecies(
        scientific_name="Ulmus americana",
        common_name="American Elm",
        kind="deciduous_tree",
        mature_height_m=24.0,
        mature_spread_m=24.0,
        growth_rate_cm_per_year=90.0,
        usda_zones_min=2,
        usda_zones_max=9,
        light="full_sun",
        water="medium",
        soil_type="Moist, deep loam; adaptable",
        bloom_color="none",
        deer_resistant=False,
        notes="Classic vase form; DED-resistant cultivars (Princeton, Valley Forge) now available (Dirr p. 922).",
        regions=("east", "midwest", "north"),
        pollinator_value="low",
    ),
    PlantSpecies(
        scientific_name="Tilia americana",
        common_name="American Linden",
        kind="deciduous_tree",
        mature_height_m=21.0,
        mature_spread_m=12.0,
        growth_rate_cm_per_year=45.0,
        usda_zones_min=2,
        usda_zones_max=8,
        light="partial_shade",
        water="medium",
        soil_type="Moist, well-drained; adaptable",
        bloom_color="yellow-white",
        deer_resistant=False,
        notes="Fragrant summer flowers attract bees heavily; excellent honey plant; large shade tree (Dirr p. 899).",
        regions=("east", "midwest", "north"),
        pollinator_value="high",
    ),
    PlantSpecies(
        scientific_name="Fraxinus pennsylvanica",
        common_name="Green Ash",
        kind="deciduous_tree",
        mature_height_m=18.0,
        mature_spread_m=15.0,
        growth_rate_cm_per_year=60.0,
        usda_zones_min=3,
        usda_zones_max=9,
        light="full_sun",
        water="medium",
        soil_type="Adaptable; wet to dry; clay-tolerant",
        bloom_color="none",
        deer_resistant=False,
        notes="Hardy adaptable shade tree; EAB has devastated populations — consider alternatives or treated specimens (Dirr p. 432).",
        regions=("east", "midwest", "south"),
        pollinator_value="low",
    ),
    PlantSpecies(
        scientific_name="Amelanchier canadensis",
        common_name="Serviceberry",
        kind="deciduous_tree",
        mature_height_m=7.5,
        mature_spread_m=4.5,
        growth_rate_cm_per_year=45.0,
        usda_zones_min=3,
        usda_zones_max=8,
        light="partial_shade",
        water="medium",
        soil_type="Moist, well-drained, slightly acidic",
        bloom_color="white",
        deer_resistant=False,
        notes="First spring bloom; June berries loved by birds; multi-season interest; understory (Dirr p. 89).",
        regions=("east", "midwest", "north"),
        pollinator_value="high",
    ),
    PlantSpecies(
        scientific_name="Quercus palustris",
        common_name="Pin Oak",
        kind="deciduous_tree",
        mature_height_m=21.0,
        mature_spread_m=12.0,
        growth_rate_cm_per_year=60.0,
        usda_zones_min=4,
        usda_zones_max=8,
        light="full_sun",
        water="medium",
        soil_type="Moist to wet, acidic; clay-tolerant",
        bloom_color="none",
        deer_resistant=False,
        notes="Pyramidal form; persistent bronze winter leaves; tolerates wet soils; abundant acorns (Dirr p. 848).",
        regions=("east", "midwest"),
        pollinator_value="medium",
    ),
    PlantSpecies(
        scientific_name="Celtis occidentalis",
        common_name="Common Hackberry",
        kind="deciduous_tree",
        mature_height_m=15.0,
        mature_spread_m=15.0,
        growth_rate_cm_per_year=60.0,
        usda_zones_min=2,
        usda_zones_max=9,
        light="full_sun",
        water="low",
        soil_type="Adaptable; clay to sandy; drought-tolerant",
        bloom_color="none",
        deer_resistant=False,
        notes="Extremely tough urban tree; cork-like bark; food for 40+ bird species; wide zone range (Dirr p. 233).",
        regions=("east", "midwest", "south"),
        pollinator_value="medium",
    ),
    PlantSpecies(
        scientific_name="Populus tremuloides",
        common_name="Quaking Aspen",
        kind="deciduous_tree",
        mature_height_m=12.0,
        mature_spread_m=7.5,
        growth_rate_cm_per_year=75.0,
        usda_zones_min=1,
        usda_zones_max=6,
        light="full_sun",
        water="medium",
        soil_type="Moist, well-drained; adaptable",
        bloom_color="none",
        deer_resistant=False,
        notes="Trembling leaves; white bark; clonal colonies; short-lived; brilliant gold fall colour (Dirr p. 743).",
        regions=("north", "mountain", "west"),
        pollinator_value="medium",
    ),

    # -----------------------------------------------------------------------
    # EVERGREEN TREES
    # -----------------------------------------------------------------------
    PlantSpecies(
        scientific_name="Juniperus virginiana",
        common_name="Eastern Red Cedar",
        kind="evergreen",
        mature_height_m=12.0,
        mature_spread_m=6.0,
        growth_rate_cm_per_year=30.0,
        usda_zones_min=2,
        usda_zones_max=9,
        light="full_sun",
        water="low",
        soil_type="Highly adaptable; dry to moist; clay, sand, rock",
        bloom_color="none",
        deer_resistant=True,
        notes="Tough native evergreen; blue berries critical cedar waxwing food; windbreak; drought-tolerant (Dirr p. 538).",
        regions=("east", "midwest", "south"),
        pollinator_value="low",
    ),
    PlantSpecies(
        scientific_name="Pinus strobus",
        common_name="Eastern White Pine",
        kind="evergreen",
        mature_height_m=30.0,
        mature_spread_m=12.0,
        growth_rate_cm_per_year=60.0,
        usda_zones_min=3,
        usda_zones_max=8,
        light="partial_shade",
        water="medium",
        soil_type="Moist, well-drained, acidic; not wet or clay",
        bloom_color="none",
        deer_resistant=False,
        notes="Graceful soft-needle pine; fastest-growing eastern pine; shelter planting (Dirr p. 698).",
        regions=("east", "midwest", "north"),
        pollinator_value="low",
    ),
    PlantSpecies(
        scientific_name="Abies balsamea",
        common_name="Balsam Fir",
        kind="evergreen",
        mature_height_m=15.0,
        mature_spread_m=6.0,
        growth_rate_cm_per_year=25.0,
        usda_zones_min=3,
        usda_zones_max=5,
        light="partial_shade",
        water="medium",
        soil_type="Cool, moist, well-drained, acidic",
        bloom_color="none",
        deer_resistant=False,
        notes="Aromatic Christmas tree species; prefers cool climates; important boreal species (Dirr p. 11).",
        regions=("north", "east"),
        pollinator_value="low",
    ),
    PlantSpecies(
        scientific_name="Picea glauca",
        common_name="White Spruce",
        kind="evergreen",
        mature_height_m=18.0,
        mature_spread_m=6.0,
        growth_rate_cm_per_year=30.0,
        usda_zones_min=2,
        usda_zones_max=6,
        light="full_sun",
        water="medium",
        soil_type="Moist, well-drained; adaptable; cold-hardy",
        bloom_color="none",
        deer_resistant=False,
        notes="Cold-hardiest spruce; windbreak and screen; white-striped needles (Dirr p. 683).",
        regions=("north", "east", "midwest"),
        pollinator_value="low",
    ),
    PlantSpecies(
        scientific_name="Pseudotsuga menziesii",
        common_name="Douglas Fir",
        kind="evergreen",
        mature_height_m=60.0,
        mature_spread_m=15.0,
        growth_rate_cm_per_year=60.0,
        usda_zones_min=4,
        usda_zones_max=6,
        light="full_sun",
        water="medium",
        soil_type="Well-drained, deep; moist to moderately dry",
        bloom_color="none",
        deer_resistant=False,
        notes="Pacific Northwest dominant; large-scale screen or specimen; iconic cones (Dirr p. 779).",
        regions=("west", "pacific", "mountain"),
        pollinator_value="low",
    ),
    PlantSpecies(
        scientific_name="Pinus ponderosa",
        common_name="Ponderosa Pine",
        kind="evergreen",
        mature_height_m=36.0,
        mature_spread_m=9.0,
        growth_rate_cm_per_year=45.0,
        usda_zones_min=3,
        usda_zones_max=7,
        light="full_sun",
        water="low",
        soil_type="Well-drained, sandy to loamy; drought-tolerant",
        bloom_color="none",
        deer_resistant=True,
        notes="Vanilla-scented bark; western landscape dominant; drought-adapted (Dirr p. 700).",
        regions=("west", "mountain"),
        pollinator_value="low",
    ),
    PlantSpecies(
        scientific_name="Sequoia sempervirens",
        common_name="Coast Redwood",
        kind="evergreen",
        mature_height_m=90.0,
        mature_spread_m=9.0,
        growth_rate_cm_per_year=90.0,
        usda_zones_min=7,
        usda_zones_max=10,
        light="partial_shade",
        water="medium",
        soil_type="Deep, moist, well-drained; coastal fog beneficial",
        bloom_color="none",
        deer_resistant=True,
        notes="World's tallest tree; fast-growing; fog-adapted Pacific coast species; iconic specimen (Dirr p. 875).",
        regions=("pacific", "west"),
        pollinator_value="low",
    ),

    # -----------------------------------------------------------------------
    # SHRUBS
    # -----------------------------------------------------------------------
    PlantSpecies(
        scientific_name="Hydrangea macrophylla",
        common_name="Bigleaf Hydrangea",
        kind="shrub",
        mature_height_m=1.8,
        mature_spread_m=2.4,
        growth_rate_cm_per_year=30.0,
        usda_zones_min=5,
        usda_zones_max=9,
        light="partial_shade",
        water="high",
        soil_type="Moist, well-drained, slightly acidic; pH affects bloom color",
        bloom_color="blue-pink",
        deer_resistant=False,
        notes="Mophead or lacecap blooms; pH controls colour — acid = blue, alkaline = pink (Dirr p. 497).",
        regions=("east", "south"),
        pollinator_value="medium",
    ),
    PlantSpecies(
        scientific_name="Hydrangea quercifolia",
        common_name="Oakleaf Hydrangea",
        kind="shrub",
        mature_height_m=1.8,
        mature_spread_m=2.4,
        growth_rate_cm_per_year=30.0,
        usda_zones_min=5,
        usda_zones_max=9,
        light="partial_shade",
        water="medium",
        soil_type="Moist, well-drained; more drought-tolerant than macrophylla",
        bloom_color="white",
        deer_resistant=False,
        notes="Native eastern shrub; exfoliating cinnamon bark; four-season interest; fall colour (Dirr p. 501).",
        regions=("east", "south"),
        pollinator_value="medium",
    ),
    PlantSpecies(
        scientific_name="Ilex verticillata",
        common_name="Winterberry Holly",
        kind="shrub",
        mature_height_m=2.4,
        mature_spread_m=2.4,
        growth_rate_cm_per_year=30.0,
        usda_zones_min=3,
        usda_zones_max=9,
        light="full_sun",
        water="high",
        soil_type="Moist to wet, acidic; excellent for wet sites",
        bloom_color="white",
        deer_resistant=True,
        notes="Stunning red-berry display after leaf drop; requires male pollinator; native wetland shrub (Dirr p. 520).",
        regions=("east", "midwest", "south"),
        pollinator_value="medium",
    ),
    PlantSpecies(
        scientific_name="Viburnum trilobum",
        common_name="American Cranberrybush",
        kind="shrub",
        mature_height_m=3.6,
        mature_spread_m=3.6,
        growth_rate_cm_per_year=45.0,
        usda_zones_min=2,
        usda_zones_max=7,
        light="partial_shade",
        water="medium",
        soil_type="Moist, well-drained; adaptable",
        bloom_color="white",
        deer_resistant=False,
        notes="Showy red fruit persists into winter; native alternative to non-native V. opulus (Dirr p. 949).",
        regions=("north", "east", "midwest"),
        pollinator_value="medium",
    ),
    PlantSpecies(
        scientific_name="Clethra alnifolia",
        common_name="Summersweet",
        kind="shrub",
        mature_height_m=2.4,
        mature_spread_m=1.8,
        growth_rate_cm_per_year=30.0,
        usda_zones_min=3,
        usda_zones_max=9,
        light="partial_shade",
        water="medium",
        soil_type="Moist to wet, acidic; tolerates wet and sandy soils",
        bloom_color="white",
        deer_resistant=True,
        notes="Intensely fragrant late-summer bloom; excellent for shady, wet sites; pollinators love it (Dirr p. 287).",
        regions=("east", "south"),
        pollinator_value="high",
    ),
    PlantSpecies(
        scientific_name="Itea virginica",
        common_name="Virginia Sweetspire",
        kind="shrub",
        mature_height_m=1.5,
        mature_spread_m=1.5,
        growth_rate_cm_per_year=30.0,
        usda_zones_min=5,
        usda_zones_max=9,
        light="partial_shade",
        water="medium",
        soil_type="Moist to wet; adaptable; tolerates shade and wet",
        bloom_color="white",
        deer_resistant=True,
        notes="Outstanding fall colour (burgundy-scarlet); fragrant white racemes; native (Dirr p. 533).",
        regions=("east", "south"),
        pollinator_value="medium",
    ),
    PlantSpecies(
        scientific_name="Rhododendron catawbiense",
        common_name="Catawba Rhododendron",
        kind="evergreen",
        mature_height_m=3.0,
        mature_spread_m=3.0,
        growth_rate_cm_per_year=15.0,
        usda_zones_min=4,
        usda_zones_max=8,
        light="partial_shade",
        water="medium",
        soil_type="Moist, well-drained, acidic, humus-rich",
        bloom_color="purple",
        deer_resistant=True,
        notes="Lavender-purple flowers May-June; evergreen foundational shrub; Appalachian native (Dirr p. 810).",
        regions=("east", "south"),
        pollinator_value="medium",
    ),
    PlantSpecies(
        scientific_name="Kalmia latifolia",
        common_name="Mountain Laurel",
        kind="evergreen",
        mature_height_m=3.0,
        mature_spread_m=3.0,
        growth_rate_cm_per_year=15.0,
        usda_zones_min=4,
        usda_zones_max=9,
        light="partial_shade",
        water="medium",
        soil_type="Moist, well-drained, acidic, humus-rich",
        bloom_color="pink-white",
        deer_resistant=True,
        notes="CT/PA state flower; remarkable bud and flower geometry; all parts toxic (Dirr p. 543).",
        regions=("east", "south"),
        pollinator_value="medium",
    ),
    PlantSpecies(
        scientific_name="Fothergilla gardenii",
        common_name="Dwarf Fothergilla",
        kind="shrub",
        mature_height_m=1.0,
        mature_spread_m=1.2,
        growth_rate_cm_per_year=15.0,
        usda_zones_min=5,
        usda_zones_max=9,
        light="partial_shade",
        water="medium",
        soil_type="Moist, well-drained, acidic; no wet clay",
        bloom_color="white",
        deer_resistant=True,
        notes="Fragrant bottlebrush flowers before leaves; best red-orange-yellow fall colour per Dirr (p. 425).",
        regions=("east", "south"),
        pollinator_value="high",
    ),
    PlantSpecies(
        scientific_name="Spiraea japonica",
        common_name="Japanese Spirea",
        kind="shrub",
        mature_height_m=1.2,
        mature_spread_m=1.5,
        growth_rate_cm_per_year=30.0,
        usda_zones_min=4,
        usda_zones_max=8,
        light="full_sun",
        water="medium",
        soil_type="Well-drained; adaptable; drought-tolerant when established",
        bloom_color="pink",
        deer_resistant=True,
        notes="Long-blooming; mass planting; deadhead for rebloom; invasive in some states (Dirr p. 880).",
        regions=("east", "midwest"),
        pollinator_value="medium",
    ),
    PlantSpecies(
        scientific_name="Syringa vulgaris",
        common_name="Common Lilac",
        kind="shrub",
        mature_height_m=4.5,
        mature_spread_m=3.0,
        growth_rate_cm_per_year=30.0,
        usda_zones_min=3,
        usda_zones_max=7,
        light="full_sun",
        water="medium",
        soil_type="Well-drained, slightly alkaline; not wet",
        bloom_color="purple",
        deer_resistant=True,
        notes="Fragrant May bloom; needs cold winters for best flower; classic cottage shrub (Dirr p. 895).",
        regions=("north", "east", "midwest"),
        pollinator_value="high",
    ),
    PlantSpecies(
        scientific_name="Calycanthus floridus",
        common_name="Sweetshrub",
        kind="shrub",
        mature_height_m=2.4,
        mature_spread_m=3.6,
        growth_rate_cm_per_year=30.0,
        usda_zones_min=4,
        usda_zones_max=9,
        light="partial_shade",
        water="medium",
        soil_type="Moist, well-drained; adaptable to shade",
        bloom_color="maroon",
        deer_resistant=True,
        notes="Fragrant wine-red flowers; old-fashioned native shrub; excellent in shade (Dirr p. 199).",
        regions=("east", "south"),
        pollinator_value="medium",
    ),
    PlantSpecies(
        scientific_name="Hamamelis virginiana",
        common_name="Common Witch Hazel",
        kind="shrub",
        mature_height_m=4.5,
        mature_spread_m=4.5,
        growth_rate_cm_per_year=30.0,
        usda_zones_min=3,
        usda_zones_max=8,
        light="partial_shade",
        water="medium",
        soil_type="Moist, well-drained, slightly acidic",
        bloom_color="yellow",
        deer_resistant=True,
        notes="Latest-blooming native shrub (Nov-Dec); fragrant yellow ribbons after leaf drop (Dirr p. 491).",
        regions=("east", "midwest"),
        pollinator_value="medium",
    ),
    PlantSpecies(
        scientific_name="Physocarpus opulifolius",
        common_name="Ninebark",
        kind="shrub",
        mature_height_m=2.4,
        mature_spread_m=2.4,
        growth_rate_cm_per_year=45.0,
        usda_zones_min=2,
        usda_zones_max=8,
        light="full_sun",
        water="low",
        soil_type="Highly adaptable; dry to moist; very tough",
        bloom_color="white",
        deer_resistant=True,
        notes="Exfoliating bark; purple/gold-leaved cultivars popular; very cold-hardy and tough (Dirr p. 672).",
        regions=("north", "east", "midwest"),
        pollinator_value="medium",
    ),
    PlantSpecies(
        scientific_name="Aronia arbutifolia",
        common_name="Red Chokeberry",
        kind="shrub",
        mature_height_m=2.4,
        mature_spread_m=1.5,
        growth_rate_cm_per_year=30.0,
        usda_zones_min=4,
        usda_zones_max=9,
        light="full_sun",
        water="medium",
        soil_type="Adaptable; wet to dry; tolerates clay and infertile soils",
        bloom_color="white",
        deer_resistant=True,
        notes="Brilliant red berries and scarlet fall colour; extremely adaptable native (Dirr p. 118).",
        regions=("east", "south", "midwest"),
        pollinator_value="medium",
    ),

    # -----------------------------------------------------------------------
    # PERENNIALS
    # -----------------------------------------------------------------------
    PlantSpecies(
        scientific_name="Echinacea purpurea",
        common_name="Purple Coneflower",
        kind="perennial",
        mature_height_m=0.9,
        mature_spread_m=0.6,
        growth_rate_cm_per_year=30.0,
        usda_zones_min=3,
        usda_zones_max=9,
        light="full_sun",
        water="low",
        soil_type="Well-drained; average; drought-tolerant once established",
        bloom_color="purple",
        deer_resistant=True,
        notes="Iconic prairie native; long-blooming July-Sept; critical butterfly and finch plant; easy (Dirr p. 376).",
        regions=("east", "midwest", "south"),
        pollinator_value="high",
    ),
    PlantSpecies(
        scientific_name="Asclepias tuberosa",
        common_name="Butterfly Weed",
        kind="perennial",
        mature_height_m=0.6,
        mature_spread_m=0.6,
        growth_rate_cm_per_year=20.0,
        usda_zones_min=3,
        usda_zones_max=9,
        light="full_sun",
        water="low",
        soil_type="Well-drained, lean, sandy; does not tolerate wet",
        bloom_color="orange",
        deer_resistant=True,
        notes="Critical monarch butterfly host and nectar plant; brilliant orange; native prairie species (Dirr p. 126).",
        regions=("east", "midwest", "south"),
        pollinator_value="high",
    ),
    PlantSpecies(
        scientific_name="Hosta sieboldiana",
        common_name="Siebold's Hosta",
        kind="perennial",
        mature_height_m=0.75,
        mature_spread_m=1.2,
        growth_rate_cm_per_year=20.0,
        usda_zones_min=3,
        usda_zones_max=8,
        light="shade",
        water="medium",
        soil_type="Moist, well-drained, humus-rich; tolerates clay",
        bloom_color="white",
        deer_resistant=False,
        notes="Largest-leaved hosta; blue-green corrugated foliage; definitive shade groundcover (Dirr p. 505).",
        regions=("east", "midwest", "north"),
        pollinator_value="medium",
    ),
    PlantSpecies(
        scientific_name="Rudbeckia fulgida",
        common_name="Orange Coneflower",
        kind="perennial",
        mature_height_m=0.75,
        mature_spread_m=0.6,
        growth_rate_cm_per_year=30.0,
        usda_zones_min=3,
        usda_zones_max=9,
        light="full_sun",
        water="medium",
        soil_type="Average; moist to dry; adaptable",
        bloom_color="yellow",
        deer_resistant=True,
        notes="Long August-October bloom; 'Goldsturm' is most-sold perennial; bird seed heads (Dirr p. 859).",
        regions=("east", "midwest"),
        pollinator_value="high",
    ),
    PlantSpecies(
        scientific_name="Salvia nemorosa",
        common_name="Meadow Sage",
        kind="perennial",
        mature_height_m=0.6,
        mature_spread_m=0.45,
        growth_rate_cm_per_year=20.0,
        usda_zones_min=4,
        usda_zones_max=8,
        light="full_sun",
        water="low",
        soil_type="Well-drained; lean; drought-tolerant",
        bloom_color="purple",
        deer_resistant=True,
        notes="Intense violet-purple spikes; deadhead for repeat bloom; bee favourite (Dirr p. 861).",
        regions=("east", "midwest", "north"),
        pollinator_value="high",
    ),
    PlantSpecies(
        scientific_name="Penstemon digitalis",
        common_name="Foxglove Beardtongue",
        kind="perennial",
        mature_height_m=0.9,
        mature_spread_m=0.45,
        growth_rate_cm_per_year=25.0,
        usda_zones_min=3,
        usda_zones_max=8,
        light="full_sun",
        water="low",
        soil_type="Well-drained; average; drought-tolerant",
        bloom_color="white",
        deer_resistant=True,
        notes="Native; white tubular flowers; excellent for bees and hummingbirds; adaptable (Dirr p. 666).",
        regions=("east", "midwest"),
        pollinator_value="high",
    ),
    PlantSpecies(
        scientific_name="Lobelia cardinalis",
        common_name="Cardinal Flower",
        kind="perennial",
        mature_height_m=1.2,
        mature_spread_m=0.45,
        growth_rate_cm_per_year=30.0,
        usda_zones_min=3,
        usda_zones_max=9,
        light="partial_shade",
        water="high",
        soil_type="Moist to wet; humus-rich; riparian",
        bloom_color="red",
        deer_resistant=True,
        notes="Intensely red; critical hummingbird plant; native riparian/wetland; short-lived but self-seeds (Dirr p. 576).",
        regions=("east", "midwest", "south"),
        pollinator_value="high",
    ),
    PlantSpecies(
        scientific_name="Monarda didyma",
        common_name="Bee Balm",
        kind="perennial",
        mature_height_m=1.2,
        mature_spread_m=1.2,
        growth_rate_cm_per_year=45.0,
        usda_zones_min=4,
        usda_zones_max=9,
        light="full_sun",
        water="medium",
        soil_type="Moist, well-drained; humus-rich",
        bloom_color="red",
        deer_resistant=True,
        notes="Native; red flowers attract hummingbirds and swallowtails; powdery mildew on humid sites (Dirr p. 607).",
        regions=("east", "midwest"),
        pollinator_value="high",
    ),
    PlantSpecies(
        scientific_name="Aquilegia canadensis",
        common_name="Wild Columbine",
        kind="perennial",
        mature_height_m=0.6,
        mature_spread_m=0.3,
        growth_rate_cm_per_year=20.0,
        usda_zones_min=3,
        usda_zones_max=8,
        light="partial_shade",
        water="low",
        soil_type="Well-drained, rocky; adaptable",
        bloom_color="red-yellow",
        deer_resistant=True,
        notes="Native woodland edge; red-yellow nodding flowers; hummingbird plant; self-seeds gracefully (Dirr p. 112).",
        regions=("east", "midwest", "north"),
        pollinator_value="high",
    ),
    PlantSpecies(
        scientific_name="Hemerocallis fulva",
        common_name="Tawny Daylily",
        kind="perennial",
        mature_height_m=0.75,
        mature_spread_m=0.6,
        growth_rate_cm_per_year=30.0,
        usda_zones_min=3,
        usda_zones_max=9,
        light="full_sun",
        water="medium",
        soil_type="Adaptable; tolerates poor soils and clay",
        bloom_color="orange",
        deer_resistant=False,
        notes="Extremely adaptable; long bloom season; naturalises on roadsides; ditch lily (Dirr p. 493).",
        regions=("east", "midwest", "south"),
        pollinator_value="medium",
    ),
    PlantSpecies(
        scientific_name="Phlox paniculata",
        common_name="Garden Phlox",
        kind="perennial",
        mature_height_m=1.2,
        mature_spread_m=0.6,
        growth_rate_cm_per_year=30.0,
        usda_zones_min=4,
        usda_zones_max=8,
        light="full_sun",
        water="medium",
        soil_type="Moist, well-drained; humus-rich",
        bloom_color="pink",
        deer_resistant=False,
        notes="Classic summer border perennial; fragrant; mildew-resistant varieties preferred (Dirr p. 672).",
        regions=("east", "midwest"),
        pollinator_value="high",
    ),
    PlantSpecies(
        scientific_name="Aster novae-angliae",
        common_name="New England Aster",
        kind="perennial",
        mature_height_m=1.5,
        mature_spread_m=0.9,
        growth_rate_cm_per_year=45.0,
        usda_zones_min=4,
        usda_zones_max=8,
        light="full_sun",
        water="medium",
        soil_type="Average to moist; adaptable",
        bloom_color="purple",
        deer_resistant=True,
        notes="Fall native; critical late-season nectar source for monarchs and bumblebees (Dirr p. 134).",
        regions=("east", "midwest"),
        pollinator_value="high",
    ),
    PlantSpecies(
        scientific_name="Solidago canadensis",
        common_name="Canada Goldenrod",
        kind="perennial",
        mature_height_m=1.5,
        mature_spread_m=0.9,
        growth_rate_cm_per_year=45.0,
        usda_zones_min=3,
        usda_zones_max=9,
        light="full_sun",
        water="low",
        soil_type="Average to poor; adaptable; spreads by rhizome",
        bloom_color="yellow",
        deer_resistant=True,
        notes="Fall colour and critical pollinator plant; not a hay-fever cause (wind-pollinated ragweed is) (Dirr p. 878).",
        regions=("east", "midwest", "north"),
        pollinator_value="high",
    ),
    PlantSpecies(
        scientific_name="Helenium autumnale",
        common_name="Sneezeweed",
        kind="perennial",
        mature_height_m=1.5,
        mature_spread_m=0.9,
        growth_rate_cm_per_year=45.0,
        usda_zones_min=3,
        usda_zones_max=8,
        light="full_sun",
        water="medium",
        soil_type="Moist; tolerates clay and wet",
        bloom_color="yellow-orange",
        deer_resistant=True,
        notes="Late-season yellow-orange daisies; native prairie/wetland; important late pollinator plant (Dirr p. 491).",
        regions=("east", "midwest"),
        pollinator_value="high",
    ),
    PlantSpecies(
        scientific_name="Baptisia australis",
        common_name="Blue Wild Indigo",
        kind="perennial",
        mature_height_m=1.2,
        mature_spread_m=0.9,
        growth_rate_cm_per_year=15.0,
        usda_zones_min=3,
        usda_zones_max=9,
        light="full_sun",
        water="low",
        soil_type="Well-drained; lean; deep taproot; drought-tolerant",
        bloom_color="blue",
        deer_resistant=True,
        notes="Native prairie; indigo-blue lupine-like flowers; blue-grey pods; long-lived (50+ years) (Dirr p. 151).",
        regions=("east", "midwest"),
        pollinator_value="high",
    ),

    # -----------------------------------------------------------------------
    # GRASSES
    # -----------------------------------------------------------------------
    PlantSpecies(
        scientific_name="Festuca arundinacea",
        common_name="Tall Fescue",
        kind="grass",
        mature_height_m=0.9,
        mature_spread_m=0.3,
        growth_rate_cm_per_year=30.0,
        usda_zones_min=3,
        usda_zones_max=8,
        light="partial_shade",
        water="medium",
        soil_type="Adaptable; clay to loam; moderate drought tolerance",
        bloom_color="none",
        deer_resistant=True,
        notes="Turf and roadside grass; heat-tolerant cool-season; bunching habit; endophyte strains resist insects.",
        regions=("east", "midwest", "west", "south"),
        pollinator_value="low",
    ),
    PlantSpecies(
        scientific_name="Andropogon gerardii",
        common_name="Big Bluestem",
        kind="grass",
        mature_height_m=1.8,
        mature_spread_m=0.6,
        growth_rate_cm_per_year=45.0,
        usda_zones_min=4,
        usda_zones_max=9,
        light="full_sun",
        water="low",
        soil_type="Well-drained; lean to average; deep taproot",
        bloom_color="none",
        deer_resistant=True,
        notes="Tallgrass prairie dominant; turkey-foot seedhead; outstanding copper fall colour (Dirr p. 89).",
        regions=("midwest", "east", "south"),
        pollinator_value="medium",
    ),
    PlantSpecies(
        scientific_name="Panicum virgatum",
        common_name="Switchgrass",
        kind="grass",
        mature_height_m=1.5,
        mature_spread_m=0.75,
        growth_rate_cm_per_year=45.0,
        usda_zones_min=5,
        usda_zones_max=9,
        light="full_sun",
        water="low",
        soil_type="Highly adaptable; wet to dry; clay to sand",
        bloom_color="none",
        deer_resistant=True,
        notes="Extremely tough native; airy seedhead; erosion control; 'Shenandoah' red fall colour (Dirr p. 654).",
        regions=("east", "midwest", "south"),
        pollinator_value="medium",
    ),
    PlantSpecies(
        scientific_name="Schizachyrium scoparium",
        common_name="Little Bluestem",
        kind="grass",
        mature_height_m=0.9,
        mature_spread_m=0.45,
        growth_rate_cm_per_year=30.0,
        usda_zones_min=3,
        usda_zones_max=9,
        light="full_sun",
        water="low",
        soil_type="Well-drained, lean; tolerates drought and infertile soils",
        bloom_color="none",
        deer_resistant=True,
        notes="Brilliant copper-orange fall colour; prairie and roadside native; erosion control (Dirr p. 869).",
        regions=("east", "midwest", "south"),
        pollinator_value="medium",
    ),
    PlantSpecies(
        scientific_name="Calamagrostis x acutiflora",
        common_name="Feather Reed Grass",
        kind="grass",
        mature_height_m=1.5,
        mature_spread_m=0.6,
        growth_rate_cm_per_year=30.0,
        usda_zones_min=4,
        usda_zones_max=9,
        light="partial_shade",
        water="medium",
        soil_type="Moist to moderately dry; clay-tolerant; adaptable",
        bloom_color="none",
        deer_resistant=True,
        notes="Upright columnar form; 'Karl Foerster' most-grown ornamental grass; three-season interest (Dirr p. 196).",
        regions=("east", "midwest", "north"),
        pollinator_value="low",
    ),
    PlantSpecies(
        scientific_name="Muhlenbergia capillaris",
        common_name="Muhly Grass",
        kind="grass",
        mature_height_m=0.9,
        mature_spread_m=0.9,
        growth_rate_cm_per_year=30.0,
        usda_zones_min=6,
        usda_zones_max=11,
        light="full_sun",
        water="low",
        soil_type="Well-drained; sandy to rocky; drought-tolerant",
        bloom_color="pink",
        deer_resistant=True,
        notes="Spectacular pink-purple fall plumes; native southeast coastal plain; dramatic specimen (Dirr p. 619).",
        regions=("south", "east"),
        pollinator_value="low",
    ),
    PlantSpecies(
        scientific_name="Poa pratensis",
        common_name="Kentucky Bluegrass",
        kind="grass",
        mature_height_m=0.6,
        mature_spread_m=0.3,
        growth_rate_cm_per_year=15.0,
        usda_zones_min=2,
        usda_zones_max=7,
        light="full_sun",
        water="medium",
        soil_type="Well-drained, fertile loam; prefers cool moist conditions",
        bloom_color="none",
        deer_resistant=True,
        notes="Premier cool-season turf grass; sod-forming; dormant in heat; requires irrigation in warm summers.",
        regions=("north", "east", "midwest", "mountain"),
        pollinator_value="low",
    ),
    PlantSpecies(
        scientific_name="Bouteloua gracilis",
        common_name="Blue Grama",
        kind="grass",
        mature_height_m=0.45,
        mature_spread_m=0.3,
        growth_rate_cm_per_year=20.0,
        usda_zones_min=3,
        usda_zones_max=9,
        light="full_sun",
        water="low",
        soil_type="Well-drained, sandy; xeric; highly drought-tolerant",
        bloom_color="none",
        deer_resistant=True,
        notes="Short-grass prairie native; eyelash-like seedheads; excellent low-water turf alternative (Dirr p. 162).",
        regions=("midwest", "west", "mountain"),
        pollinator_value="low",
    ),
    PlantSpecies(
        scientific_name="Carex pensylvanica",
        common_name="Pennsylvania Sedge",
        kind="grass",
        mature_height_m=0.25,
        mature_spread_m=0.3,
        growth_rate_cm_per_year=15.0,
        usda_zones_min=3,
        usda_zones_max=8,
        light="shade",
        water="low",
        soil_type="Dry to moist; woodland; tolerates poor soils under trees",
        bloom_color="none",
        deer_resistant=True,
        notes="Excellent native groundcover under trees; fine-textured; low-maintenance lawn alternative (Dirr p. 206).",
        regions=("east", "midwest", "north"),
        pollinator_value="low",
    ),
    PlantSpecies(
        scientific_name="Elymus canadensis",
        common_name="Canada Wild Rye",
        kind="grass",
        mature_height_m=1.2,
        mature_spread_m=0.6,
        growth_rate_cm_per_year=45.0,
        usda_zones_min=3,
        usda_zones_max=8,
        light="partial_shade",
        water="medium",
        soil_type="Adaptable; moist to dry; tolerates shade",
        bloom_color="none",
        deer_resistant=True,
        notes="Adaptable native grass; nodding wheat-like seedheads; excellent erosion control and prairie restoration.",
        regions=("east", "midwest", "north"),
        pollinator_value="low",
    ),

    # -----------------------------------------------------------------------
    # GROUNDCOVERS / ADDITIONAL
    # -----------------------------------------------------------------------
    PlantSpecies(
        scientific_name="Pachysandra terminalis",
        common_name="Japanese Pachysandra",
        kind="groundcover",
        mature_height_m=0.25,
        mature_spread_m=0.3,
        growth_rate_cm_per_year=20.0,
        usda_zones_min=4,
        usda_zones_max=8,
        light="shade",
        water="medium",
        soil_type="Moist, well-drained, acidic; no standing water",
        bloom_color="white",
        deer_resistant=False,
        notes="Standard shade groundcover; evergreen; spreads to form mats; caution — deer do browse (Dirr p. 645).",
        regions=("east", "midwest"),
        pollinator_value="low",
    ),
    PlantSpecies(
        scientific_name="Gaultheria procumbens",
        common_name="Wintergreen",
        kind="groundcover",
        mature_height_m=0.15,
        mature_spread_m=0.6,
        growth_rate_cm_per_year=10.0,
        usda_zones_min=3,
        usda_zones_max=6,
        light="shade",
        water="medium",
        soil_type="Moist, acidic, humus-rich; requires acid soil",
        bloom_color="white",
        deer_resistant=True,
        notes="Evergreen native; red berries; minty fragrance; excellent under pines and oaks (Dirr p. 446).",
        regions=("east", "north"),
        pollinator_value="medium",
    ),
    PlantSpecies(
        scientific_name="Comptonia peregrina",
        common_name="Sweetfern",
        kind="shrub",
        mature_height_m=1.2,
        mature_spread_m=1.5,
        growth_rate_cm_per_year=20.0,
        usda_zones_min=2,
        usda_zones_max=6,
        light="full_sun",
        water="low",
        soil_type="Dry, sandy, acidic; nitrogen-fixer; tolerates poor soils",
        bloom_color="none",
        deer_resistant=True,
        notes="Fragrant fern-like leaves; nitrogen-fixing native; excellent for dry, acid, infertile sites (Dirr p. 304).",
        regions=("north", "east"),
        pollinator_value="low",
    ),
    PlantSpecies(
        scientific_name="Rosa palustris",
        common_name="Swamp Rose",
        kind="shrub",
        mature_height_m=1.8,
        mature_spread_m=1.5,
        growth_rate_cm_per_year=30.0,
        usda_zones_min=4,
        usda_zones_max=9,
        light="full_sun",
        water="high",
        soil_type="Wet to moist; tolerates flooding; stream banks",
        bloom_color="pink",
        deer_resistant=False,
        notes="Native rose for wet sites; fragrant pink flowers; red hips; riparian planting (Dirr p. 855).",
        regions=("east", "midwest"),
        pollinator_value="high",
    ),
    PlantSpecies(
        scientific_name="Sambucus canadensis",
        common_name="American Elderberry",
        kind="shrub",
        mature_height_m=3.6,
        mature_spread_m=3.6,
        growth_rate_cm_per_year=60.0,
        usda_zones_min=3,
        usda_zones_max=9,
        light="partial_shade",
        water="medium",
        soil_type="Moist; adaptable; tolerates wet",
        bloom_color="white",
        deer_resistant=False,
        notes="Flat-topped white flowers June-July; purple berries for pies and birds; fast native coloniser (Dirr p. 864).",
        regions=("east", "midwest", "south"),
        pollinator_value="high",
    ),
    PlantSpecies(
        scientific_name="Cornus sericea",
        common_name="Red Twig Dogwood",
        kind="shrub",
        mature_height_m=2.4,
        mature_spread_m=3.0,
        growth_rate_cm_per_year=45.0,
        usda_zones_min=2,
        usda_zones_max=8,
        light="partial_shade",
        water="high",
        soil_type="Moist to wet; adaptable; excellent for wet sites",
        bloom_color="white",
        deer_resistant=False,
        notes="Brilliant red winter stems; cut to ground every 3 years for brightest colour; wet-site native (Dirr p. 322).",
        regions=("north", "east", "midwest"),
        pollinator_value="medium",
    ),
    PlantSpecies(
        scientific_name="Lindera benzoin",
        common_name="Spicebush",
        kind="shrub",
        mature_height_m=3.0,
        mature_spread_m=3.6,
        growth_rate_cm_per_year=30.0,
        usda_zones_min=4,
        usda_zones_max=9,
        light="shade",
        water="medium",
        soil_type="Moist, well-drained; tolerates shade",
        bloom_color="yellow",
        deer_resistant=True,
        notes="Earliest yellow bloom (March); spicy fragrant twigs; critical spicebush swallowtail host (Dirr p. 567).",
        regions=("east", "south"),
        pollinator_value="high",
    ),
    PlantSpecies(
        scientific_name="Vaccinium corymbosum",
        common_name="Highbush Blueberry",
        kind="shrub",
        mature_height_m=2.4,
        mature_spread_m=1.8,
        growth_rate_cm_per_year=20.0,
        usda_zones_min=4,
        usda_zones_max=7,
        light="full_sun",
        water="medium",
        soil_type="Moist, well-drained, very acidic (pH 4.5-5.5); organic matter",
        bloom_color="white",
        deer_resistant=False,
        notes="Edible blueberries; brilliant red fall colour; spring urn-shaped flowers; requires acidic soil (Dirr p. 935).",
        regions=("east", "midwest", "north"),
        pollinator_value="high",
    ),
    PlantSpecies(
        scientific_name="Mahonia aquifolium",
        common_name="Oregon Grape",
        kind="evergreen",
        mature_height_m=1.8,
        mature_spread_m=1.5,
        growth_rate_cm_per_year=15.0,
        usda_zones_min=5,
        usda_zones_max=9,
        light="shade",
        water="low",
        soil_type="Well-drained; adaptable; drought-tolerant in shade",
        bloom_color="yellow",
        deer_resistant=True,
        notes="Evergreen holly-like leaves; fragrant yellow flowers; blue-black berries; shade-tolerant (Dirr p. 596).",
        regions=("west", "pacific"),
        pollinator_value="medium",
    ),
    PlantSpecies(
        scientific_name="Leucothoe fontanesiana",
        common_name="Drooping Leucothoe",
        kind="evergreen",
        mature_height_m=1.2,
        mature_spread_m=1.5,
        growth_rate_cm_per_year=20.0,
        usda_zones_min=4,
        usda_zones_max=6,
        light="shade",
        water="medium",
        soil_type="Moist, acidic, humus-rich; no drought",
        bloom_color="white",
        deer_resistant=True,
        notes="Arching evergreen; white racemes; reddish purple winter colour; stream bank native (Dirr p. 571).",
        regions=("east", "south"),
        pollinator_value="low",
    ),
    PlantSpecies(
        scientific_name="Symphoricarpus albus",
        common_name="Snowberry",
        kind="shrub",
        mature_height_m=1.5,
        mature_spread_m=1.8,
        growth_rate_cm_per_year=30.0,
        usda_zones_min=3,
        usda_zones_max=7,
        light="partial_shade",
        water="low",
        soil_type="Adaptable; dry to moist; tolerates shade",
        bloom_color="pink",
        deer_resistant=True,
        notes="Waxy white berries persistent into winter; very cold-hardy; tolerates dry shade (Dirr p. 893).",
        regions=("north", "west", "east"),
        pollinator_value="medium",
    ),
    PlantSpecies(
        scientific_name="Rhamnus cathartica",
        common_name="Common Buckthorn",
        kind="deciduous_tree",
        mature_height_m=6.0,
        mature_spread_m=4.5,
        growth_rate_cm_per_year=30.0,
        usda_zones_min=3,
        usda_zones_max=8,
        light="partial_shade",
        water="low",
        soil_type="Adaptable; tolerates poor and dry soils",
        bloom_color="none",
        deer_resistant=True,
        notes="Extremely tough; NOTE: invasive in many Midwest/Northeast states — use native alternatives where restricted (Dirr note).",
        regions=("north", "east", "midwest"),
        pollinator_value="low",
    ),
    PlantSpecies(
        scientific_name="Cercidiphyllum japonicum",
        common_name="Katsura Tree",
        kind="deciduous_tree",
        mature_height_m=18.0,
        mature_spread_m=12.0,
        growth_rate_cm_per_year=60.0,
        usda_zones_min=4,
        usda_zones_max=8,
        light="partial_shade",
        water="medium",
        soil_type="Moist, well-drained; not drought-tolerant",
        bloom_color="none",
        deer_resistant=True,
        notes="Heart-shaped leaves; cotton-candy / burnt-sugar fall scent; layered branching; superb specimen (Dirr p. 237).",
        regions=("east", "midwest"),
        pollinator_value="low",
    ),
    PlantSpecies(
        scientific_name="Oxydendrum arboreum",
        common_name="Sourwood",
        kind="deciduous_tree",
        mature_height_m=9.0,
        mature_spread_m=6.0,
        growth_rate_cm_per_year=20.0,
        usda_zones_min=5,
        usda_zones_max=9,
        light="partial_shade",
        water="medium",
        soil_type="Moist, well-drained, acidic; not wet",
        bloom_color="white",
        deer_resistant=True,
        notes="Best native for brilliant scarlet fall colour; creamy white racemes; sourwood honey (Dirr p. 642).",
        regions=("east", "south"),
        pollinator_value="high",
    ),
    PlantSpecies(
        scientific_name="Catalpa speciosa",
        common_name="Northern Catalpa",
        kind="deciduous_tree",
        mature_height_m=18.0,
        mature_spread_m=12.0,
        growth_rate_cm_per_year=60.0,
        usda_zones_min=4,
        usda_zones_max=8,
        light="full_sun",
        water="medium",
        soil_type="Adaptable; moist to dry; clay-tolerant",
        bloom_color="white",
        deer_resistant=False,
        notes="Bold tropical-looking leaves; white orchid-like flowers; long bean pods; tough urban tree (Dirr p. 218).",
        regions=("east", "midwest"),
        pollinator_value="medium",
    ),

    # -----------------------------------------------------------------------
    # ADDITIONAL SPECIES — rounding out to 100+
    # -----------------------------------------------------------------------
    PlantSpecies(
        scientific_name="Quercus macrocarpa",
        common_name="Bur Oak",
        kind="deciduous_tree",
        mature_height_m=18.0,
        mature_spread_m=18.0,
        growth_rate_cm_per_year=30.0,
        usda_zones_min=3,
        usda_zones_max=8,
        light="full_sun",
        water="low",
        soil_type="Adaptable; sandy to clay; excellent drought tolerance",
        bloom_color="none",
        deer_resistant=True,
        notes="Most drought-tolerant eastern oak; massive acorns; cork-like bark; prairie native (Dirr p. 836).",
        regions=("midwest", "east"),
        pollinator_value="medium",
    ),
    PlantSpecies(
        scientific_name="Gymnocladus dioicus",
        common_name="Kentucky Coffeetree",
        kind="deciduous_tree",
        mature_height_m=18.0,
        mature_spread_m=12.0,
        growth_rate_cm_per_year=30.0,
        usda_zones_min=3,
        usda_zones_max=8,
        light="full_sun",
        water="low",
        soil_type="Adaptable; drought, clay, and compaction-tolerant",
        bloom_color="white",
        deer_resistant=True,
        notes="Bold winter silhouette; unusual compound leaves; extremely tough urban tree; rare native (Dirr p. 479).",
        regions=("midwest", "east"),
        pollinator_value="medium",
    ),
    PlantSpecies(
        scientific_name="Sassafras albidum",
        common_name="Sassafras",
        kind="deciduous_tree",
        mature_height_m=12.0,
        mature_spread_m=7.5,
        growth_rate_cm_per_year=45.0,
        usda_zones_min=4,
        usda_zones_max=9,
        light="full_sun",
        water="low",
        soil_type="Well-drained, sandy to loam, acidic",
        bloom_color="yellow",
        deer_resistant=False,
        notes="Mitten-shaped aromatic leaves; brilliant fall colour; spicebush swallowtail and bird berries (Dirr p. 867).",
        regions=("east", "south"),
        pollinator_value="medium",
    ),
    PlantSpecies(
        scientific_name="Chionanthus virginicus",
        common_name="White Fringetree",
        kind="deciduous_tree",
        mature_height_m=6.0,
        mature_spread_m=6.0,
        growth_rate_cm_per_year=20.0,
        usda_zones_min=3,
        usda_zones_max=9,
        light="full_sun",
        water="medium",
        soil_type="Moist, well-drained; adaptable",
        bloom_color="white",
        deer_resistant=True,
        notes="Spectacular fragrant white fringe flowers; one of the best native small trees; wide zone range (Dirr p. 257).",
        regions=("east", "south"),
        pollinator_value="medium",
    ),
    PlantSpecies(
        scientific_name="Magnolia virginiana",
        common_name="Sweetbay Magnolia",
        kind="deciduous_tree",
        mature_height_m=9.0,
        mature_spread_m=6.0,
        growth_rate_cm_per_year=30.0,
        usda_zones_min=5,
        usda_zones_max=10,
        light="partial_shade",
        water="high",
        soil_type="Moist to wet, acidic; stream margins and swamps",
        bloom_color="white",
        deer_resistant=False,
        notes="Lemony-scented white flowers June-Sept; semi-evergreen in south; wet-site native (Dirr p. 596).",
        regions=("east", "south"),
        pollinator_value="medium",
    ),
    PlantSpecies(
        scientific_name="Pinus taeda",
        common_name="Loblolly Pine",
        kind="evergreen",
        mature_height_m=27.0,
        mature_spread_m=9.0,
        growth_rate_cm_per_year=90.0,
        usda_zones_min=6,
        usda_zones_max=9,
        light="full_sun",
        water="medium",
        soil_type="Adaptable; sandy to clay; tolerates wet",
        bloom_color="none",
        deer_resistant=False,
        notes="Fastest-growing southeastern pine; important timber and wildlife tree; dominant SE coastal plain (Dirr p. 702).",
        regions=("south", "east"),
        pollinator_value="low",
    ),
    PlantSpecies(
        scientific_name="Tsuga canadensis",
        common_name="Eastern Hemlock",
        kind="evergreen",
        mature_height_m=21.0,
        mature_spread_m=9.0,
        growth_rate_cm_per_year=30.0,
        usda_zones_min=3,
        usda_zones_max=7,
        light="shade",
        water="medium",
        soil_type="Moist, well-drained, acidic; cool north-facing slopes",
        bloom_color="none",
        deer_resistant=False,
        notes="Finest evergreen shade tree; feathery graceful habit; HWA threaten wild populations (Dirr p. 915).",
        regions=("east", "north"),
        pollinator_value="low",
    ),
    PlantSpecies(
        scientific_name="Thuja occidentalis",
        common_name="American Arborvitae",
        kind="evergreen",
        mature_height_m=15.0,
        mature_spread_m=4.5,
        growth_rate_cm_per_year=30.0,
        usda_zones_min=2,
        usda_zones_max=8,
        light="full_sun",
        water="medium",
        soil_type="Moist, well-drained; adaptable; tolerates wet",
        bloom_color="none",
        deer_resistant=False,
        notes="Most commonly planted evergreen screen/hedge; 'Emerald Green' most popular cultivar (Dirr p. 897).",
        regions=("north", "east", "midwest"),
        pollinator_value="low",
    ),
    PlantSpecies(
        scientific_name="Ilex opaca",
        common_name="American Holly",
        kind="evergreen",
        mature_height_m=9.0,
        mature_spread_m=6.0,
        growth_rate_cm_per_year=15.0,
        usda_zones_min=5,
        usda_zones_max=9,
        light="partial_shade",
        water="medium",
        soil_type="Moist, well-drained, acidic; humus-rich",
        bloom_color="white",
        deer_resistant=True,
        notes="Classic Christmas holly; bright red berries; requires male pollinator; native evergreen (Dirr p. 516).",
        regions=("east", "south"),
        pollinator_value="medium",
    ),
    PlantSpecies(
        scientific_name="Aesculus parviflora",
        common_name="Bottlebrush Buckeye",
        kind="shrub",
        mature_height_m=3.6,
        mature_spread_m=4.5,
        growth_rate_cm_per_year=30.0,
        usda_zones_min=4,
        usda_zones_max=9,
        light="partial_shade",
        water="medium",
        soil_type="Moist, well-drained; tolerates dry shade",
        bloom_color="white",
        deer_resistant=True,
        notes="Outstanding large native shrub; white bottlebrush spires in July; spreads by suckers; attracts hummingbirds (Dirr p. 80).",
        regions=("east", "south"),
        pollinator_value="high",
    ),
    PlantSpecies(
        scientific_name="Ceanothus americanus",
        common_name="New Jersey Tea",
        kind="shrub",
        mature_height_m=0.9,
        mature_spread_m=0.9,
        growth_rate_cm_per_year=15.0,
        usda_zones_min=4,
        usda_zones_max=8,
        light="full_sun",
        water="low",
        soil_type="Well-drained; dry to average; deep taproot; nitrogen-fixer",
        bloom_color="white",
        deer_resistant=True,
        notes="Native prairie edge shrub; nitrogen-fixer; attracts many bee species; tea substitute in Revolution (Dirr p. 227).",
        regions=("east", "midwest"),
        pollinator_value="high",
    ),
    PlantSpecies(
        scientific_name="Diervilla lonicera",
        common_name="Bush Honeysuckle",
        kind="shrub",
        mature_height_m=0.9,
        mature_spread_m=1.5,
        growth_rate_cm_per_year=30.0,
        usda_zones_min=3,
        usda_zones_max=7,
        light="partial_shade",
        water="low",
        soil_type="Well-drained; dry to average; adaptable",
        bloom_color="yellow",
        deer_resistant=True,
        notes="Native alternative to invasive Lonicera; tough dry-site shrub; fall foliage turns red (Dirr p. 346).",
        regions=("north", "east"),
        pollinator_value="medium",
    ),
    PlantSpecies(
        scientific_name="Staphylea trifolia",
        common_name="American Bladdernut",
        kind="shrub",
        mature_height_m=3.0,
        mature_spread_m=2.4,
        growth_rate_cm_per_year=30.0,
        usda_zones_min=3,
        usda_zones_max=8,
        light="partial_shade",
        water="medium",
        soil_type="Moist, well-drained; stream margins; adaptable",
        bloom_color="white",
        deer_resistant=True,
        notes="Underused native; papery inflated seedpods; white spring flowers; naturalises on stream banks (Dirr p. 883).",
        regions=("east", "midwest"),
        pollinator_value="medium",
    ),
    PlantSpecies(
        scientific_name="Vernonia noveboracensis",
        common_name="New York Ironweed",
        kind="perennial",
        mature_height_m=1.8,
        mature_spread_m=0.6,
        growth_rate_cm_per_year=45.0,
        usda_zones_min=5,
        usda_zones_max=9,
        light="full_sun",
        water="medium",
        soil_type="Moist; average to wet; adaptable",
        bloom_color="purple",
        deer_resistant=True,
        notes="Intense royal-purple flat-topped clusters Aug-Sept; critical late-season pollinator plant (Dirr p. 942).",
        regions=("east", "south"),
        pollinator_value="high",
    ),
    PlantSpecies(
        scientific_name="Chelone glabra",
        common_name="White Turtlehead",
        kind="perennial",
        mature_height_m=0.9,
        mature_spread_m=0.6,
        growth_rate_cm_per_year=20.0,
        usda_zones_min=3,
        usda_zones_max=8,
        light="partial_shade",
        water="high",
        soil_type="Moist to wet; humus-rich; stream banks",
        bloom_color="white",
        deer_resistant=True,
        notes="Native wetland perennial; Baltimore checkerspot butterfly host plant; white helmet-shaped flowers (Dirr p. 249).",
        regions=("east", "north"),
        pollinator_value="high",
    ),
    PlantSpecies(
        scientific_name="Eupatorium maculatum",
        common_name="Spotted Joe Pye Weed",
        kind="perennial",
        mature_height_m=1.8,
        mature_spread_m=0.9,
        growth_rate_cm_per_year=45.0,
        usda_zones_min=4,
        usda_zones_max=8,
        light="full_sun",
        water="medium",
        soil_type="Moist; average to wet; stream margins",
        bloom_color="pink",
        deer_resistant=True,
        notes="Tall native; mauve-pink domed flowerheads; monarch and tiger swallowtail magnet in late summer (Dirr p. 404).",
        regions=("east", "midwest"),
        pollinator_value="high",
    ),
    PlantSpecies(
        scientific_name="Zizia aurea",
        common_name="Golden Alexanders",
        kind="perennial",
        mature_height_m=0.75,
        mature_spread_m=0.5,
        growth_rate_cm_per_year=20.0,
        usda_zones_min=3,
        usda_zones_max=8,
        light="partial_shade",
        water="medium",
        soil_type="Moist; average to wet; adaptable",
        bloom_color="yellow",
        deer_resistant=True,
        notes="Early yellow umbel; black swallowtail host; blooms with Virginia bluebells; prairie native (Dirr p. 979).",
        regions=("east", "midwest"),
        pollinator_value="high",
    ),
    PlantSpecies(
        scientific_name="Sporobolus heterolepis",
        common_name="Prairie Dropseed",
        kind="grass",
        mature_height_m=0.6,
        mature_spread_m=0.6,
        growth_rate_cm_per_year=15.0,
        usda_zones_min=3,
        usda_zones_max=9,
        light="full_sun",
        water="low",
        soil_type="Well-drained; dry to average; prairie native",
        bloom_color="none",
        deer_resistant=True,
        notes="Elegant arching grass; coriander-scented August flowers; golden fall colour; long-lived prairie native (Dirr p. 882).",
        regions=("midwest", "east"),
        pollinator_value="low",
    ),
    PlantSpecies(
        scientific_name="Sorghastrum nutans",
        common_name="Indiangrass",
        kind="grass",
        mature_height_m=1.5,
        mature_spread_m=0.6,
        growth_rate_cm_per_year=45.0,
        usda_zones_min=4,
        usda_zones_max=9,
        light="full_sun",
        water="low",
        soil_type="Well-drained; adaptable; drought-tolerant",
        bloom_color="none",
        deer_resistant=True,
        notes="Tall-grass prairie dominant; blue-green foliage; golden-orange fall colour; paired with big bluestem (Dirr p. 880).",
        regions=("midwest", "east", "south"),
        pollinator_value="medium",
    ),
)


# ---------------------------------------------------------------------------
# Build lookup index
# ---------------------------------------------------------------------------

# Common-name → scientific name index (normalised lowercase)
_COMMON_INDEX: dict[str, str] = {
    sp.common_name.lower(): sci
    for sci, sp in PLANT_CATALOG.items()
}


def lookup_plant(name: str) -> PlantSpecies | None:
    """
    Case-insensitive lookup by common name or scientific name.

    Parameters
    ----------
    name : str
        Common name (e.g. 'red maple') or scientific name (e.g. 'Acer rubrum').

    Returns
    -------
    PlantSpecies | None
        Matching species, or None if not found.
    """
    key = name.strip().lower()
    if key in PLANT_CATALOG:
        return PLANT_CATALOG[key]
    if key in _COMMON_INDEX:
        return PLANT_CATALOG[_COMMON_INDEX[key]]
    return None


def filter_plants(
    usda_zone: int | None = None,
    light: str | None = None,
    water: str | None = None,
    kind: str | None = None,
    deer_resistant: bool | None = None,
) -> list[PlantSpecies]:
    """
    Filter the catalog by site conditions.

    Parameters
    ----------
    usda_zone : int | None
        USDA hardiness zone (1–13). Returns species whose zone range includes it.
    light : str | None
        Light requirement: 'full_sun', 'partial_shade', 'shade'.
    water : str | None
        Water demand: 'low', 'medium', 'high'.
    kind : str | None
        Plant category: 'deciduous_tree', 'evergreen', 'shrub', 'perennial',
        'grass', 'groundcover'.
    deer_resistant : bool | None
        If True, return only deer-resistant species.

    Returns
    -------
    list[PlantSpecies]
        Species matching all supplied criteria (AND logic).
    """
    results: list[PlantSpecies] = []
    for sp in PLANT_CATALOG.values():
        if usda_zone is not None and not (sp.usda_zones_min <= usda_zone <= sp.usda_zones_max):
            continue
        if light is not None and sp.light != light:
            continue
        if water is not None and sp.water != water:
            continue
        if kind is not None and sp.kind != kind:
            continue
        if deer_resistant is not None and sp.deer_resistant != deer_resistant:
            continue
        results.append(sp)
    return results


# Pollinator-friendly species by region (scientific names)
_POLLINATOR_SUBSETS: dict[str, list[str]] = {
    "east": [
        "asclepias tuberosa",
        "echinacea purpurea",
        "monarda didyma",
        "lobelia cardinalis",
        "rudbeckia fulgida",
        "solidago canadensis",
        "aster novae-angliae",
        "aquilegia canadensis",
        "baptisia australis",
        "penstemon digitalis",
        "lindera benzoin",
        "clethra alnifolia",
        "fothergilla gardenii",
        "sambucus canadensis",
        "amelanchier canadensis",
        "vaccinium corymbosum",
        "nyssa sylvatica",
        "oxydendrum arboreum",
    ],
    "west": [
        "asclepias tuberosa",
        "echinacea purpurea",
        "solidago canadensis",
        "salvia nemorosa",
        "mahonia aquifolium",
        "sambucus canadensis",
    ],
    "south": [
        "asclepias tuberosa",
        "echinacea purpurea",
        "monarda didyma",
        "lobelia cardinalis",
        "rudbeckia fulgida",
        "solidago canadensis",
        "aster novae-angliae",
        "muhlenbergia capillaris",
        "sambucus canadensis",
        "cercis canadensis",
        "nyssa sylvatica",
    ],
    "north": [
        "asclepias tuberosa",
        "echinacea purpurea",
        "solidago canadensis",
        "aster novae-angliae",
        "aquilegia canadensis",
        "monarda didyma",
        "syringa vulgaris",
        "vaccinium corymbosum",
        "tilia americana",
        "sambucus canadensis",
    ],
}


def plants_for_pollinators(
    region: Literal["east", "west", "south", "north"],
) -> list[PlantSpecies]:
    """
    Return pollinator-friendly species for the given region.

    Parameters
    ----------
    region : 'east' | 'west' | 'south' | 'north'
        Broad US region.

    Returns
    -------
    list[PlantSpecies]
        Species recommended for pollinators in the region.
        Returns empty list for unknown region.
    """
    sci_names = _POLLINATOR_SUBSETS.get(region, [])
    result: list[PlantSpecies] = []
    for name in sci_names:
        sp = PLANT_CATALOG.get(name)
        if sp is not None:
            result.append(sp)
    return result
