"""
kerf_mold.cooling_channel_layout — 3D cooling channel routing layout design.

Theory & References
-------------------
Menges G., Michaeli W., Mohren P. "How to Make Injection Molds", 3rd ed.,
  Hanser 2001 — §6.5 Cooling-channel design rules:
    Channel bore diameter: typically 8–14 mm for standard cavity blocks.
    Centre-to-centre pitch: 3–5× bore diameter.
    Distance from cavity surface: 1.5–2.5× bore diameter.
    Series vs. parallel circuit layout trade-offs.

Rosato D.V., Rosato M.G. "Injection Molding Handbook", 3rd ed.,
  Kluwer Academic 2000 — §8 Cooling system design.

Tang L.Q., Chassapis C., Manoochehri S. (1998). Optimal cooling
  system design for multi-cavity injection moulding.
  *Finite Elements in Analysis and Design*, 26(3), 229–251.
  — Covers straight gun-drilled channels and baffle/bubbler configurations.

Xu X., Sachs E., Allen S. (2001). The design of conformal cooling
  channels in injection molding tooling.
  *Polymer Engineering & Science*, 41(7), 1265–1279.
  — Conformal cooling channel offset distance and coverage rules.

Capability scope
----------------
This module designs the **routing geometry** of cooling channels — the 3-D
positions, orientations, diameter, and pitch of each drilled (or conformal)
channel run — as a complement to the thermal analysis already implemented in
kerf_mold.cooling (Dittus-Boelter HTC, pressure drop, cooling time).

Two layout strategies are provided:

  conventional:
    Straight gun-drilled channels arranged in a grid parallel to the parting
    plane.  Industry-standard approach for CNC-machined molds.  Channels are
    specified by (start, end) 3-D line segments with uniform bore diameter
    and pitch.  Bubblers and baffles can be added for deep core regions.

  conformal:
    Channels that follow the cavity-surface offset at a constant distance
    (Xu et al. 2001 rule: offset = 1.5–2× bore diameter from cavity surface).
    Represented as a polyline following the outer contour of the cavity bbox,
    suitable for additive-manufactured (3D-printed) mold inserts.

Output format
-------------
Each channel is a CoolingChannelRoute dataclass with:
  start_mm, end_mm  : 3-D endpoints (mm)
  diameter_mm       : bore diameter
  label             : human-readable identifier
  channel_type      : 'straight' | 'baffle' | 'bubbler' | 'conformal'

A CoolingLayoutReport contains all channels, summary statistics, and
honest caveats about the limitations of the heuristic placement rules.

HONEST CAVEAT
-------------
Channel positions are generated by heuristic rules from Menges 2001 §6.5 and
Xu et al. 2001.  Real cooling-channel layouts must be verified for:
  (a) mechanical interference with cavity features, ejector pins, and other
      inserts (use kerf_mold.cooling_channel_conflict for interference checks);
  (b) thermal uniformity (use kerf_mold.cooling for HTC/pressure-drop analysis);
  (c) manufactureability (gun-drilled holes need entry/exit faces; conformal
      channels need AM or electrode-discharge tooling).
This module does NOT perform thermal FEM simulation.  Use Moldflow / Moldex3D
for production-quality cooling analysis.

Wave 9C: Cimatron mold base + EDM electrode + wire EDM + cooling channel layout
"""
from __future__ import annotations

import math
from dataclasses import dataclass, field
from typing import List, Optional, Tuple


# ---------------------------------------------------------------------------
# Design constants (Menges 2001 §6.5)
# ---------------------------------------------------------------------------

# Recommended bore diameter range (mm)
BORE_DIAMETER_MIN_MM: float = 6.0
BORE_DIAMETER_MAX_MM: float = 16.0
BORE_DIAMETER_DEFAULT_MM: float = 10.0

# Pitch multiplier: pitch = pitch_factor × diameter (Menges 2001 §6.5 Table 6.4)
# Min 2.5×D for aggressive cooling; 3–4×D standard; 5×D conservative
PITCH_FACTOR_MIN: float = 2.5
PITCH_FACTOR_STANDARD: float = 3.5
PITCH_FACTOR_MAX: float = 5.0

# Cavity wall clearance: distance from cavity surface = clearance_factor × diameter
# Menges 2001 §6.5: minimum 1.5×D; standard 2×D; maximum 3×D
WALL_CLEARANCE_FACTOR_MIN: float = 1.5
WALL_CLEARANCE_FACTOR_STANDARD: float = 2.0
WALL_CLEARANCE_FACTOR_MAX: float = 3.0

# Conformal channel offset from cavity surface (Xu et al. 2001 §3)
CONFORMAL_OFFSET_FACTOR: float = 1.8  # offset = 1.8 × diameter


# ---------------------------------------------------------------------------
# Dataclasses
# ---------------------------------------------------------------------------

@dataclass
class MoldBlockSpec:
    """Bounding box of the mold cavity/core block.

    Parameters
    ----------
    x_min, x_max : Block extents in X (mm).
    y_min, y_max : Block extents in Y (mm).
    z_min, z_max : Block extents in Z (mm); z_max = parting plane height.
    pull_axis    : Mold opening axis ('x', 'y', 'z'). Default 'z'.
    cavity_surface_z : Z coordinate of the deepest cavity surface (mm).
                       Used to position channels at a fixed clearance above it.
    """
    x_min: float
    x_max: float
    y_min: float
    y_max: float
    z_min: float
    z_max: float
    pull_axis: str = "z"
    cavity_surface_z: Optional[float] = None   # if None, derived from z_max - cavity_depth

    def __post_init__(self) -> None:
        if self.x_min >= self.x_max:
            raise ValueError(f"x_min ({self.x_min}) must be < x_max ({self.x_max})")
        if self.y_min >= self.y_max:
            raise ValueError(f"y_min ({self.y_min}) must be < y_max ({self.y_max})")
        if self.z_min >= self.z_max:
            raise ValueError(f"z_min ({self.z_min}) must be < z_max ({self.z_max})")
        valid_axes = {"x", "y", "z"}
        if self.pull_axis not in valid_axes:
            raise ValueError(f"pull_axis must be one of {valid_axes}, got {self.pull_axis!r}")

    @property
    def width_mm(self) -> float:
        return self.x_max - self.x_min

    @property
    def depth_mm(self) -> float:
        return self.y_max - self.y_min

    @property
    def height_mm(self) -> float:
        return self.z_max - self.z_min


@dataclass
class CoolingChannelRoute:
    """A single cooling channel in the routing layout.

    Parameters
    ----------
    start_mm     : [x, y, z] start point of channel centreline (mm).
    end_mm       : [x, y, z] end point of channel centreline (mm).
    diameter_mm  : Bore/drill diameter (mm).
    label        : Human-readable identifier (e.g. 'CH_01', 'BAFFLE_A').
    channel_type : 'straight' (gun-drilled) | 'baffle' | 'bubbler' | 'conformal'.
    circuit_id   : Circuit grouping (e.g. 'circuit_A', 'circuit_B').
    """
    start_mm: List[float]
    end_mm: List[float]
    diameter_mm: float
    label: str = ""
    channel_type: str = "straight"    # 'straight' | 'baffle' | 'bubbler' | 'conformal'
    circuit_id: str = "circuit_A"

    def __post_init__(self) -> None:
        if len(self.start_mm) != 3:
            raise ValueError("start_mm must be a 3-element list [x, y, z]")
        if len(self.end_mm) != 3:
            raise ValueError("end_mm must be a 3-element list [x, y, z]")
        if self.diameter_mm <= 0:
            raise ValueError(f"diameter_mm must be > 0, got {self.diameter_mm}")
        valid_types = {"straight", "baffle", "bubbler", "conformal"}
        if self.channel_type not in valid_types:
            raise ValueError(
                f"channel_type must be one of {sorted(valid_types)}, got {self.channel_type!r}"
            )

    @property
    def length_mm(self) -> float:
        """Euclidean length of the channel segment (mm)."""
        dx = self.end_mm[0] - self.start_mm[0]
        dy = self.end_mm[1] - self.start_mm[1]
        dz = self.end_mm[2] - self.start_mm[2]
        return math.sqrt(dx * dx + dy * dy + dz * dz)

    def as_dict(self) -> dict:
        return {
            "label": self.label,
            "channel_type": self.channel_type,
            "circuit_id": self.circuit_id,
            "start_mm": list(self.start_mm),
            "end_mm": list(self.end_mm),
            "diameter_mm": round(self.diameter_mm, 3),
            "length_mm": round(self.length_mm, 3),
        }


@dataclass
class CoolingLayoutReport:
    """Result of cooling channel layout design.

    Attributes
    ----------
    channels         : List of all designed CoolingChannelRoute segments.
    layout_type      : 'conventional' | 'conformal'.
    total_channels   : Total number of channel segments.
    total_length_mm  : Sum of all channel segment lengths (mm).
    estimated_heat_area_mm2 : Approximate wetted inner surface area (mm²).
    pitch_mm         : Achieved centre-to-centre pitch (mm).
    bore_diameter_mm : Bore diameter used (mm).
    clearance_mm     : Achieved cavity surface clearance (mm).
    num_circuits     : Number of independent cooling circuits.
    warnings         : List of design warnings.
    honest_caveat    : Plain-text scope limitations.
    """
    channels: List[CoolingChannelRoute]
    layout_type: str
    total_channels: int
    total_length_mm: float
    estimated_heat_area_mm2: float
    pitch_mm: float
    bore_diameter_mm: float
    clearance_mm: float
    num_circuits: int
    warnings: List[str]
    honest_caveat: str = ""

    def as_dict(self) -> dict:
        return {
            "layout_type": self.layout_type,
            "total_channels": self.total_channels,
            "total_length_mm": round(self.total_length_mm, 2),
            "estimated_heat_area_mm2": round(self.estimated_heat_area_mm2, 2),
            "pitch_mm": round(self.pitch_mm, 2),
            "bore_diameter_mm": round(self.bore_diameter_mm, 3),
            "clearance_mm": round(self.clearance_mm, 3),
            "num_circuits": self.num_circuits,
            "warnings": self.warnings,
            "channels": [ch.as_dict() for ch in self.channels],
            "honest_caveat": self.honest_caveat,
        }


# ---------------------------------------------------------------------------
# Bore diameter selection heuristic
# ---------------------------------------------------------------------------

def _recommend_bore_diameter(
    block: MoldBlockSpec,
    cavity_depth_mm: float,
) -> float:
    """Select bore diameter using Menges 2001 §6.5 Table 6.4 heuristics.

    Bore diameter scales with cavity block size:
      block area < 10 000 mm² → 8 mm
      block area < 40 000 mm² → 10 mm
      block area < 100 000 mm² → 12 mm
      block area >= 100 000 mm² → 14 mm

    Capped to [BORE_DIAMETER_MIN_MM, BORE_DIAMETER_MAX_MM].
    """
    area = block.width_mm * block.depth_mm
    if area < 10_000:
        d = 8.0
    elif area < 40_000:
        d = 10.0
    elif area < 100_000:
        d = 12.0
    else:
        d = 14.0
    return max(BORE_DIAMETER_MIN_MM, min(BORE_DIAMETER_MAX_MM, d))


# ---------------------------------------------------------------------------
# Conventional (straight gun-drilled) layout
# ---------------------------------------------------------------------------

def _design_conventional_layout(
    block: MoldBlockSpec,
    bore_diameter_mm: float,
    cavity_depth_mm: float,
    pitch_factor: float,
    clearance_factor: float,
    num_circuits: int,
) -> Tuple[List[CoolingChannelRoute], List[str]]:
    """Generate straight gun-drilled channel layout parallel to the parting plane.

    Channel arrangement (Menges 2001 §6.5):
      - Channels run parallel to the longest block dimension (X or Y).
      - Rows are spaced by pitch = pitch_factor × bore_diameter.
      - Channel rows are positioned at z = cavity_surface_z + clearance_factor × diameter.
      - For multi-row layouts, additional rows are placed higher in the block.
      - Two halves: cavity-side channels (just above cavity surface) and
        core-side channels (just below parting plane).

    Parameters
    ----------
    block           : MoldBlockSpec describing the mold block bbox.
    bore_diameter_mm: Channel bore diameter (mm).
    cavity_depth_mm : Depth of the deepest cavity feature (mm).
    pitch_factor    : Centre-to-centre pitch = pitch_factor × bore_diameter.
    clearance_factor: Wall clearance = clearance_factor × bore_diameter.
    num_circuits    : Number of independent cooling circuits (1 or 2).

    Returns
    -------
    (channels, warnings)
    """
    channels: List[CoolingChannelRoute] = []
    warnings: List[str] = []

    pitch = pitch_factor * bore_diameter_mm
    clearance = clearance_factor * bore_diameter_mm

    # Determine cavity surface Z (deepest point of the cavity)
    if block.cavity_surface_z is not None:
        cav_z = block.cavity_surface_z
    else:
        cav_z = block.z_max - cavity_depth_mm

    # Clamp cavity surface Z to be within the block
    cav_z = max(block.z_min, min(block.z_max, cav_z))

    # Cavity-side channel Z level (just above cavity surface)
    z_cav_side = cav_z + clearance

    # Parting-plane-side channel Z level (just below parting plane)
    z_part_side = block.z_max - clearance

    # If the block is too thin to fit channels at both levels, use one level
    if z_cav_side > z_part_side - bore_diameter_mm:
        z_levels = [0.5 * (z_cav_side + z_part_side)]
        warnings.append(
            f"Block height ({block.height_mm:.1f} mm) is too small to fit two rows of "
            f"channels with {clearance_factor:.1f}× clearance; using single row at mid-height."
        )
    else:
        z_levels = [z_cav_side, z_part_side]

    # Validate pitch vs bore diameter
    if pitch < 2.0 * bore_diameter_mm:
        warnings.append(
            f"Pitch {pitch:.1f} mm < 2×D ({2*bore_diameter_mm:.1f} mm): channels may overlap. "
            f"Increase pitch_factor to at least 2.0 (Menges 2001 §6.5 minimum)."
        )

    # Validate clearance
    if clearance < 1.5 * bore_diameter_mm / 2:
        warnings.append(
            f"Clearance {clearance:.1f} mm < 1.5×radius: risk of cavity wall breakthrough. "
            f"Menges 2001 §6.5 minimum clearance = 1.5×D = {1.5*bore_diameter_mm:.1f} mm."
        )

    # Determine channel run direction (longest block axis)
    if block.width_mm >= block.depth_mm:
        # Channels run in X; rows spaced in Y
        run_axis = "X"
        row_start = block.y_min + pitch / 2.0
        row_end_limit = block.y_max - pitch / 2.0
        ch_x_start = block.x_min + bore_diameter_mm
        ch_x_end = block.x_max - bore_diameter_mm
    else:
        # Channels run in Y; rows spaced in X
        run_axis = "Y"
        row_start = block.x_min + pitch / 2.0
        row_end_limit = block.x_max - pitch / 2.0
        ch_y_start = block.y_min + bore_diameter_mm
        ch_y_end = block.y_max - bore_diameter_mm

    # Generate channel rows at each Z level
    ch_idx = 0
    for z_level in z_levels:
        if run_axis == "X":
            y_pos = row_start
            ckt_toggle = 0
            while y_pos <= row_end_limit + 1e-6:
                # Alternate channels between circuits for balanced flow
                ckt_id = f"circuit_{chr(ord('A') + (ckt_toggle % num_circuits))}"
                label = f"CH_{ch_idx:02d}"
                ch = CoolingChannelRoute(
                    start_mm=[ch_x_start, round(y_pos, 3), round(z_level, 3)],
                    end_mm=[ch_x_end, round(y_pos, 3), round(z_level, 3)],
                    diameter_mm=bore_diameter_mm,
                    label=label,
                    channel_type="straight",
                    circuit_id=ckt_id,
                )
                channels.append(ch)
                ch_idx += 1
                ckt_toggle += 1
                y_pos += pitch
        else:
            x_pos = row_start
            ckt_toggle = 0
            while x_pos <= row_end_limit + 1e-6:
                ckt_id = f"circuit_{chr(ord('A') + (ckt_toggle % num_circuits))}"
                label = f"CH_{ch_idx:02d}"
                ch = CoolingChannelRoute(
                    start_mm=[round(x_pos, 3), ch_y_start, round(z_level, 3)],
                    end_mm=[round(x_pos, 3), ch_y_end, round(z_level, 3)],
                    diameter_mm=bore_diameter_mm,
                    label=label,
                    channel_type="straight",
                    circuit_id=ckt_id,
                )
                channels.append(ch)
                ch_idx += 1
                ckt_toggle += 1
                x_pos += pitch

    if len(channels) == 0:
        warnings.append(
            "No channels generated: block may be too small relative to bore diameter and pitch. "
            "Reduce bore_diameter_mm or pitch_factor."
        )

    return channels, warnings


# ---------------------------------------------------------------------------
# Conformal (offset-surface) layout
# ---------------------------------------------------------------------------

def _design_conformal_layout(
    block: MoldBlockSpec,
    bore_diameter_mm: float,
    cavity_depth_mm: float,
    clearance_factor: float,
    num_segments_per_loop: int,
) -> Tuple[List[CoolingChannelRoute], List[str]]:
    """Generate a conformal cooling channel loop following the cavity-surface contour.

    Conformal channels follow the cavity-surface offset at a constant distance
    (Xu et al. 2001: offset = 1.5–2× bore diameter).

    The contour is approximated as a rectangular loop at the cavity surface
    z-level, inset by clearance from the block walls, then offset upward by
    clearance_factor × bore_diameter from the cavity surface.

    This approximation is suitable for:
      - Conceptual layout design
      - AM-capable tooling inserts where the channel follows the
        rectangular-section cavity outline

    For complex non-rectangular cavities (free-form surfaces), a proper
    offset-surface computation requires OCCT ShapeOffset or equivalent.

    Parameters
    ----------
    block                  : MoldBlockSpec
    bore_diameter_mm       : Channel bore diameter (mm)
    cavity_depth_mm        : Cavity pocket depth (mm)
    clearance_factor       : Channel offset from cavity surface = factor × diameter
    num_segments_per_loop  : Number of segments in each conformal loop (min 4
                             for a rectangular approximation). Higher values produce
                             more rounded corners.

    Returns
    -------
    (channels, warnings)
    """
    channels: List[CoolingChannelRoute] = []
    warnings: List[str] = []

    clearance = clearance_factor * bore_diameter_mm
    offset = CONFORMAL_OFFSET_FACTOR * bore_diameter_mm  # Xu 2001: 1.8×D

    # Effective rectangle for the conformal loop (inset from block walls)
    inset = clearance  # keep channels clear of block side walls
    x0 = block.x_min + inset
    x1 = block.x_max - inset
    y0 = block.y_min + inset
    y1 = block.y_max - inset

    if x0 >= x1 or y0 >= y1:
        warnings.append(
            f"Block ({block.width_mm:.1f} × {block.depth_mm:.1f} mm) is too small for "
            f"conformal channels with {clearance:.1f} mm wall clearance. "
            f"Reduce bore_diameter_mm or clearance_factor."
        )
        return channels, warnings

    # Z level for conformal channels: above the deepest cavity surface
    if block.cavity_surface_z is not None:
        cav_z = block.cavity_surface_z
    else:
        cav_z = block.z_max - cavity_depth_mm
    cav_z = max(block.z_min, min(block.z_max, cav_z))
    z_level = cav_z + offset

    if z_level > block.z_max - bore_diameter_mm:
        z_level = block.z_max - bore_diameter_mm
        warnings.append(
            f"Conformal channel Z level clamped to {z_level:.1f} mm (block top - D). "
            f"Increase block height or reduce cavity depth."
        )

    if num_segments_per_loop < 4:
        num_segments_per_loop = 4
        warnings.append("num_segments_per_loop raised to 4 (minimum for rectangular approximation).")

    # Generate the rectangular-approximation conformal loop
    # For a rectangle: 4 sides (with rounded corner approximation if n_seg > 4)
    # For simplicity and robustness, use straight-line segments along the
    # rectangle perimeter (4 sides for rectangular, more for rounded).

    # Perimeter vertices for n_seg segments: distribute evenly around rectangle
    # For n_seg = 4: corners. For n_seg > 4: subdivide longest sides.
    perimeter = 2 * ((x1 - x0) + (y1 - y0))
    seg_len = perimeter / num_segments_per_loop

    # Generate perimeter points
    pts = _rectangular_perimeter_points(x0, y0, x1, y1, num_segments_per_loop)

    # Create two conformal loops: one at z_level, one as a return
    # (conformal channels form a closed loop; two circuits split at mid-point)
    # For simplicity: one closed loop = one circuit, split into two for num_circuits=2
    for i in range(len(pts)):
        p_start = [pts[i][0], pts[i][1], z_level]
        p_end = [pts[(i + 1) % len(pts)][0], pts[(i + 1) % len(pts)][1], z_level]
        ckt_id = "circuit_A" if i < len(pts) // 2 else "circuit_B"
        label = f"CONF_{i:02d}"
        ch = CoolingChannelRoute(
            start_mm=p_start,
            end_mm=p_end,
            diameter_mm=bore_diameter_mm,
            label=label,
            channel_type="conformal",
            circuit_id=ckt_id,
        )
        channels.append(ch)

    warnings.append(
        "HONEST: Conformal channel contour is a rectangular-perimeter approximation. "
        "For free-form cavity surfaces, use a CAD-kernel offset-surface (e.g. OCCT "
        "ShapeOffset) to generate the true conformal path. "
        "Ref: Xu et al. (2001) Polymer Eng & Sci 41(7), 1265–1279."
    )

    return channels, warnings


def _rectangular_perimeter_points(
    x0: float, y0: float, x1: float, y1: float, n: int
) -> List[Tuple[float, float]]:
    """Generate n equally-spaced points along a rectangle perimeter.

    Points are distributed proportionally to each side's length.
    Returns a closed list of n points (last connects back to first).
    """
    sides = [
        ((x0, y0), (x1, y0)),  # bottom
        ((x1, y0), (x1, y1)),  # right
        ((x1, y1), (x0, y1)),  # top
        ((x0, y1), (x0, y0)),  # left
    ]
    side_lengths = [math.hypot(e[0] - s[0], e[1] - s[1]) for s, e in sides]
    perimeter = sum(side_lengths)
    pts: List[Tuple[float, float]] = []

    cumulative = 0.0
    for side_idx, (s, e) in enumerate(sides):
        sl = side_lengths[side_idx]
        # Determine how many of the n points fall on this side
        frac_start = cumulative / perimeter
        frac_end = (cumulative + sl) / perimeter
        pts_on_side = int(round(n * (frac_end - frac_start)))
        # Ensure at least one point per corner (at least 4 corners)
        for j in range(pts_on_side):
            t = j / max(pts_on_side, 1)
            x = s[0] + t * (e[0] - s[0])
            y = s[1] + t * (e[1] - s[1])
            pts.append((round(x, 4), round(y, 4)))
        cumulative += sl

    # Trim or pad to exactly n points
    if len(pts) > n:
        pts = pts[:n]
    elif len(pts) < n:
        # Pad with linearly interpolated points along perimeter
        for _ in range(n - len(pts)):
            pts.append(pts[-1])

    return pts


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def design_cooling_channel_layout(
    block: MoldBlockSpec,
    cavity_depth_mm: float,
    layout_type: str = "conventional",
    bore_diameter_mm: Optional[float] = None,
    pitch_factor: float = PITCH_FACTOR_STANDARD,
    clearance_factor: float = WALL_CLEARANCE_FACTOR_STANDARD,
    num_circuits: int = 2,
    num_conformal_segments: int = 8,
) -> CoolingLayoutReport:
    """Design a 3D cooling channel layout for an injection-mold cavity block.

    Two strategies
    --------------
    'conventional':
      Straight gun-drilled channels arranged in a grid parallel to the
      parting plane.  Industry standard for machined molds.

    'conformal':
      Channel loop following the cavity-surface contour at a constant
      offset distance (Xu et al. 2001).  For additive-manufactured inserts.

    Parameters
    ----------
    block             : MoldBlockSpec — bounding box of the mold cavity block.
    cavity_depth_mm   : Depth of the deepest cavity feature (mm).
    layout_type       : 'conventional' | 'conformal'. Default 'conventional'.
    bore_diameter_mm  : Channel bore diameter (mm). If None, selected
                        automatically from block size (Menges 2001 §6.5 Table 6.4).
    pitch_factor      : Conventional layout only. Pitch = factor × diameter.
                        Typical: 3.5 (standard), 2.5 (aggressive), 5.0 (conservative).
    clearance_factor  : Distance from cavity surface = factor × bore diameter.
                        Menges 2001 §6.5 minimum 1.5, standard 2.0.
    num_circuits      : Number of independent cooling circuits (1 or 2).
    num_conformal_segments : Number of perimeter segments per conformal loop.
                            Minimum 4 (rectangular). Default 8.

    Returns
    -------
    CoolingLayoutReport

    References
    ----------
    Menges G., Michaeli W., Mohren P. "How to Make Injection Molds", 3rd ed.,
      Hanser 2001, §6.5 — cooling channel design rules; Table 6.4.
    Xu X., Sachs E., Allen S. (2001). *Polymer Engineering & Science* 41(7),
      1265–1279 — conformal cooling channel offset rules.
    Tang L.Q. et al. (1998). *Finite Elements in Analysis and Design* 26(3),
      229–251 — optimal cooling channel placement.

    HONEST CAVEAT
    -------------
    Positions are generated by heuristic rules.  Verify:
    (a) interference via kerf_mold.cooling_channel_conflict;
    (b) thermal performance via kerf_mold.cooling (Dittus-Boelter HTC);
    (c) manufacturability (gun-drilled access, AM print direction).
    This module does NOT simulate part cooling or temperature uniformity.
    Real cooling optimisation requires Moldflow / Moldex3D FEM simulation.
    """
    warnings: List[str] = []

    # Validate inputs
    if cavity_depth_mm <= 0:
        raise ValueError(f"cavity_depth_mm must be > 0, got {cavity_depth_mm}")
    valid_layouts = {"conventional", "conformal"}
    if layout_type not in valid_layouts:
        raise ValueError(
            f"layout_type must be one of {sorted(valid_layouts)}, got {layout_type!r}"
        )
    if num_circuits < 1:
        raise ValueError(f"num_circuits must be >= 1, got {num_circuits}")
    if clearance_factor < WALL_CLEARANCE_FACTOR_MIN:
        warnings.append(
            f"clearance_factor {clearance_factor:.2f} < minimum {WALL_CLEARANCE_FACTOR_MIN}. "
            f"Risk of cavity wall breakthrough. Menges 2001 §6.5 minimum: {WALL_CLEARANCE_FACTOR_MIN}×D."
        )
    if pitch_factor < PITCH_FACTOR_MIN:
        warnings.append(
            f"pitch_factor {pitch_factor:.2f} < minimum {PITCH_FACTOR_MIN}. "
            f"Channels may be too close together."
        )

    # Select bore diameter
    if bore_diameter_mm is None:
        bore_diameter_mm = _recommend_bore_diameter(block, cavity_depth_mm)

    if bore_diameter_mm < BORE_DIAMETER_MIN_MM:
        warnings.append(
            f"bore_diameter_mm {bore_diameter_mm:.1f} mm below recommended minimum "
            f"{BORE_DIAMETER_MIN_MM} mm. Smaller bores require higher flow rates for turbulence."
        )
    if bore_diameter_mm > BORE_DIAMETER_MAX_MM:
        warnings.append(
            f"bore_diameter_mm {bore_diameter_mm:.1f} mm above recommended maximum "
            f"{BORE_DIAMETER_MAX_MM} mm. Large bores reduce temperature uniformity."
        )

    # Warn if cavity depth is close to block height
    if cavity_depth_mm >= block.height_mm * 0.8:
        warnings.append(
            f"cavity_depth_mm ({cavity_depth_mm:.1f}) is {cavity_depth_mm/block.height_mm*100:.0f}% "
            f"of block height ({block.height_mm:.1f} mm). Very little room for cooling channels."
        )

    # Generate layout
    if layout_type == "conventional":
        channels, layout_warnings = _design_conventional_layout(
            block=block,
            bore_diameter_mm=bore_diameter_mm,
            cavity_depth_mm=cavity_depth_mm,
            pitch_factor=pitch_factor,
            clearance_factor=clearance_factor,
            num_circuits=num_circuits,
        )
        pitch_mm = pitch_factor * bore_diameter_mm
    else:
        channels, layout_warnings = _design_conformal_layout(
            block=block,
            bore_diameter_mm=bore_diameter_mm,
            cavity_depth_mm=cavity_depth_mm,
            clearance_factor=clearance_factor,
            num_segments_per_loop=num_conformal_segments,
        )
        pitch_mm = CONFORMAL_OFFSET_FACTOR * bore_diameter_mm  # notional pitch for conformal

    warnings.extend(layout_warnings)

    # Compute summary statistics
    total_length = sum(ch.length_mm for ch in channels)
    heat_area = math.pi * (bore_diameter_mm * 1e-3) * (total_length * 1e-3) * 1e6  # mm²
    # (π × D[m] × L[m] → m², × 1e6 → mm²)
    heat_area = math.pi * bore_diameter_mm * total_length  # mm²  (D in mm, L in mm)

    clearance_mm = clearance_factor * bore_diameter_mm
    num_actual_circuits = len(set(ch.circuit_id for ch in channels)) if channels else 0

    caveat = (
        f"HONEST: Channel positions are heuristic estimates from Menges 2001 §6.5 rules. "
        f"{'Straight gun-drilled channels; verify drill access faces.' if layout_type == 'conventional' else 'Conformal loop is a rectangular-perimeter approximation; use CAD-kernel offset for free-form cavities.'} "
        f"Verify interference via kerf_mold.cooling_channel_conflict; "
        f"verify thermal performance via kerf_mold.cooling (Dittus-Boelter). "
        f"Actual cooling optimisation requires Moldflow / Moldex3D FEM simulation. "
        f"Ref: Menges 2001 §6.5; Tang et al. (1998) FEA 26(3) 229–251; "
        f"Xu et al. (2001) PES 41(7) 1265–1279."
    )

    return CoolingLayoutReport(
        channels=channels,
        layout_type=layout_type,
        total_channels=len(channels),
        total_length_mm=round(total_length, 2),
        estimated_heat_area_mm2=round(heat_area, 2),
        pitch_mm=round(pitch_mm, 3),
        bore_diameter_mm=round(bore_diameter_mm, 3),
        clearance_mm=round(clearance_mm, 3),
        num_circuits=num_actual_circuits,
        warnings=warnings,
        honest_caveat=caveat,
    )
