"""
Fanuc 5-axis post-processor.

Dialect notes
-------------
- N-numbers: optional per-line sequence numbers, incremented by 10.
  Disabled when opts.no_n_numbers is True.
- G90  absolute positioning
- G94  feed-per-minute
- G17  XY-plane
- G21  metric (mm)
- G54  work-coordinate system (WCS 1)
- G43.4 H<n>  TCP length compensation (Fanuc Series 30i / 31i RTCP mode).
  Emitted only when opts.use_tcp is True.  Machines without RTCP support
  (Series 18i and earlier) should leave use_tcp=False and set up RTCP via
  the machine parameter table instead.
- G05.1 Q1 / G05.1 Q0  AICC (AI Contour Control): emitted as an optional block
  when opts.use_tcp is True (modern Fanuc 31i supports AICC alongside G43.4).
  Omitted when use_tcp is False to avoid alarming controllers that do not have
  the AICC option.
- M6 T<n>  tool call
- S<rpm> M3  spindle on CW
- M8  flood coolant on  (if opts.coolant == "flood")
- M7  mist coolant on  (if opts.coolant == "mist")
- A<deg> B<deg>  rotary axes on each G1 move (head_table kinematic)
- M9 M5  coolant off, spindle off
- M30  program end + rewind

Feed handling
-------------
Feed rate changes are emitted only when the feed value changes from the
previous move, reducing output file size.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from kerf_cam.five_axis.gcode_constant_tilt import PostOpts


def emit(
    cl_points: list[dict],
    ab_pairs: list[tuple[float, float]],
    opts: "PostOpts",
    warnings: list[str],
) -> str:
    """Emit a complete Fanuc 5-axis G-code program.

    Parameters
    ----------
    cl_points : list of {x, y, z, i, j, k} dicts — tool-tip positions.
    ab_pairs  : list of (A_deg, B_deg) per CL point — precomputed by emitter.
    opts      : PostOpts
    warnings  : list of warning comment strings (prepended to file).
    """
    _n = _make_seq(opts.no_n_numbers)

    lines: list[str] = []

    # --- Warnings (Fanuc uses parenthetical comments) ---
    for w in warnings:
        # Convert "; ..." LinuxCNC-style comments to Fanuc "(...)" style.
        msg = w.lstrip("; ").strip()
        lines.append(f"({msg})")

    # --- Header ---
    lines.append(f"{_n()}(GENERATED BY KERF CAM - FANUC 5-AXIS POST HEAD_TABLE A/B)")
    lines.append(f"{_n()}(MACHINE KINEMATIC: {opts.machine_kinematic.upper()})")
    tcp_note = "G43.4 RTCP ENABLED" if opts.use_tcp else "TOOL-TIP COORDS - MACHINE HANDLES RTCP"
    lines.append(f"{_n()}(TCP MODE: {tcp_note})")
    if opts.tool is not None:
        fanuc_tool_comment = opts.tool.to_comment().upper()
        lines.append(f"{_n()}({fanuc_tool_comment})")
    lines.append(f"{_n()}G90 G94 G17 G21")
    lines.append(f"{_n()}G54")
    lines.append(f"{_n()}M6 T{opts.tool_number}")
    lines.append(f"{_n()}G0 Z50.000 A0.000 B0.000")
    if opts.use_tcp:
        lines.append(f"{_n()}G05.1 Q1")              # AICC on
        lines.append(f"{_n()}G43.4 H{opts.tool_number}")
    else:
        lines.append(f"{_n()}(G43.4 H{opts.tool_number} - UNCOMMENT FOR RTCP)")
    lines.append(f"{_n()}S{opts.spindle_rpm} M3")
    if opts.coolant == "flood":
        lines.append(f"{_n()}M8")
    elif opts.coolant == "mist":
        lines.append(f"{_n()}M7")

    if not cl_points:
        lines.append(f"{_n()}G0 Z50.000 A0.000 B0.000")
        if opts.use_tcp:
            lines.append(f"{_n()}G05.1 Q0")
        lines.append(f"{_n()}G49")
        lines.append(f"{_n()}M9")
        lines.append(f"{_n()}M5")
        lines.append(f"{_n()}M30")
        return "\n".join(lines)

    # --- Rapid to first point ---
    p0 = cl_points[0]
    a0, b0 = ab_pairs[0]
    lines.append(
        f"{_n()}G0 X{p0['x']:.3f} Y{p0['y']:.3f} Z{p0['z'] + 2.0:.3f} "
        f"A{a0:.3f} B{b0:.3f} "
        f"F{opts.feed_rapid_mm_min:.0f}"
    )

    # --- Cutting moves ---
    prev_feed: float | None = None
    for pt, (a_deg, b_deg) in zip(cl_points, ab_pairs):
        feed = float(pt.get("feed", pt.get("feed_rate", opts.feed_cut_mm_min)))
        feed_word = f" F{feed:.0f}" if feed != prev_feed else ""
        prev_feed = feed
        lines.append(
            f"{_n()}G1 X{pt['x']:.3f} Y{pt['y']:.3f} Z{pt['z']:.3f} "
            f"A{a_deg:.3f} B{b_deg:.3f}"
            f"{feed_word}"
        )

    # --- Footer ---
    lines.append(f"{_n()}G0 Z50.000 A0.000 B0.000 F{opts.feed_rapid_mm_min:.0f}")
    if opts.use_tcp:
        lines.append(f"{_n()}G05.1 Q0")              # AICC off
    lines.append(f"{_n()}G49")
    lines.append(f"{_n()}M9")
    lines.append(f"{_n()}M5")
    lines.append(f"{_n()}M30")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# 3+2 indexed emitter (T6)
# ---------------------------------------------------------------------------

def emit_indexed_3_2(
    cl_points: list[dict],
    a_deg: float,
    b_deg: float,
    axis_aligned: bool,
    opts: "PostOpts",
    warnings: list[str],
) -> str:
    """Emit a complete Fanuc 3+2 indexed G-code program.

    A/B are emitted ONCE in the orientation move at the top; body G1 lines
    carry X/Y/Z only.  When axis_aligned is True, the orientation move is
    skipped (plain 3-axis output).

    Parameters
    ----------
    cl_points   : list of {x, y, z} dicts — tool-tip positions (rotated frame).
    a_deg       : A-axis angle in degrees for the one orientation move.
    b_deg       : B-axis angle in degrees for the one orientation move.
    axis_aligned: True → skip orientation move.
    opts        : PostOpts
    warnings    : list of warning comment strings to prepend.
    """
    _n = _make_seq(opts.no_n_numbers)

    lines: list[str] = []

    # --- Warnings (Fanuc uses parenthetical comments) ---
    for w in warnings:
        msg = w.lstrip("; ").strip()
        lines.append(f"({msg})")

    # --- Header ---
    lines.append(f"{_n()}(GENERATED BY KERF CAM - FANUC 3+2 INDEXED POST HEAD_TABLE A/B)")
    lines.append(f"{_n()}(MACHINE KINEMATIC: {opts.machine_kinematic.upper()})")
    tcp_note = "G43.4 RTCP ENABLED" if opts.use_tcp else "TOOL-TIP COORDS - MACHINE HANDLES RTCP"
    lines.append(f"{_n()}(TCP MODE: {tcp_note})")
    if not axis_aligned:
        lines.append(f"{_n()}(INDEXED ORIENTATION: A={a_deg:.3f} B={b_deg:.3f})")
    else:
        lines.append(f"{_n()}(AXIS-ALIGNED: NO ROTATION MOVE A=0 B=0)")
    if opts.tool is not None:
        fanuc_tool_comment = opts.tool.to_comment().upper()
        lines.append(f"{_n()}({fanuc_tool_comment})")
    lines.append(f"{_n()}G90 G94 G17 G21")
    lines.append(f"{_n()}G54")
    lines.append(f"{_n()}M6 T{opts.tool_number}")
    lines.append(f"{_n()}G0 Z50.000 A0.000 B0.000")
    if opts.use_tcp:
        lines.append(f"{_n()}G05.1 Q1")              # AICC on
        lines.append(f"{_n()}G43.4 H{opts.tool_number}")
    else:
        lines.append(f"{_n()}(G43.4 H{opts.tool_number} - UNCOMMENT FOR RTCP)")

    # --- ONE orientation move (skipped when axis-aligned) ---
    if not axis_aligned:
        lines.append(f"{_n()}G0 A{a_deg:.3f} B{b_deg:.3f} F{opts.feed_rapid_mm_min:.0f}")

    lines.append(f"{_n()}S{opts.spindle_rpm} M3")
    if opts.coolant == "flood":
        lines.append(f"{_n()}M8")
    elif opts.coolant == "mist":
        lines.append(f"{_n()}M7")

    if not cl_points:
        lines.append(f"{_n()}G0 Z50.000")
        lines.append(f"{_n()}G0 A0.000 B0.000")
        if opts.use_tcp:
            lines.append(f"{_n()}G05.1 Q0")
        lines.append(f"{_n()}G49")
        lines.append(f"{_n()}M9")
        lines.append(f"{_n()}M5")
        lines.append(f"{_n()}M30")
        return "\n".join(lines)

    # --- Rapid to safe-Z + first XY ---
    p0 = cl_points[0]
    lines.append(
        f"{_n()}G0 X{p0['x']:.3f} Y{p0['y']:.3f} Z{p0['z'] + 2.0:.3f} "
        f"F{opts.feed_rapid_mm_min:.0f}"
    )

    # --- G1 plunge to first Z ---
    feed0 = float(p0.get("feed", p0.get("feed_rate", opts.feed_cut_mm_min)))
    lines.append(
        f"{_n()}G1 X{p0['x']:.3f} Y{p0['y']:.3f} Z{p0['z']:.3f} F{feed0:.0f}"
    )

    # --- Pure 3-axis body — no A/B on G1 lines ---
    prev_feed: float = feed0
    for pt in cl_points[1:]:
        feed = float(pt.get("feed", pt.get("feed_rate", opts.feed_cut_mm_min)))
        feed_word = f" F{feed:.0f}" if feed != prev_feed else ""
        prev_feed = feed
        lines.append(
            f"{_n()}G1 X{pt['x']:.3f} Y{pt['y']:.3f} Z{pt['z']:.3f}{feed_word}"
        )

    # --- Footer: retract, home rotaries, end ---
    lines.append(f"{_n()}G0 Z50.000 F{opts.feed_rapid_mm_min:.0f}")
    lines.append(f"{_n()}G0 A0.000 B0.000")
    if opts.use_tcp:
        lines.append(f"{_n()}G05.1 Q0")              # AICC off
    lines.append(f"{_n()}G49")
    lines.append(f"{_n()}M9")
    lines.append(f"{_n()}M5")
    lines.append(f"{_n()}M30")

    return "\n".join(lines)


def _make_seq(no_n_numbers: bool):
    """Return a callable that yields N-number prefixes, or empty strings."""
    counter = [0]

    def _next() -> str:
        if no_n_numbers:
            return ""
        counter[0] += 10
        return f"N{counter[0]} "

    return _next
