"""
Heidenhain iTNC 530 / TNC 640 5-axis post-processor.

Dialect notes
-------------
Heidenhain dialogue programming uses a distinct format from RS-274 G-code:
  - Block numbers: BLK N<n> (auto-incremented by 10 by default)
  - BEGIN PGM <name> MM / END PGM <name>
  - TOOL CALL <n> Z S<rpm>     — tool selection + spindle speed
  - L X<x> Y<y> Z<z> A<a> B<b> FMAX   — rapid (linear at max feed)
  - L X<x> Y<y> Z<z> A<a> B<b> F<f>   — cutting linear move
  - CYCL DEF 7.0 DATUM SHIFT ... / CYCL CALL — work offset
  - Coolant: M8 (flood on), M9 (off), M7 (mist)
  - M3 (spindle CW), M5 (spindle off), M30 (program end + rewind)

PLANE SPATIAL / CYCLE 800 (TCPM / RTCP)
-----------------------------------------
The Heidenhain approach to 5-axis RTCP is called TCPM (Tool Centre Point
Management) or, on older machines, PLANE SPATIAL.

  PLANE SPATIAL SPA<a> SPB<b> SPC<c> TURN FMAX STAY    — tilted WP
  PLANE RESET STAY                                      — cancel

On TNC 640 and iTNC 530 (≥ SW 34049x-04):
  CYCL DEF 800 Q498=0 Q531=+0.0 Q532=+0.0 Q533=+0.0  — TCPM off
  CYCL CALL                                            — activate

For our purposes we use PLANE SPATIAL for simultaneous 5-axis (constant-tilt)
because it is the most universally supported RTCP mechanism on iTNC 530.
When opts.use_tcp is True we wrap the cutting body in PLANE SPATIAL TURN blocks.
When opts.use_tcp is False we emit raw A/B coordinates in every L block
(tool-tip coordinates, machine handles nothing — operator must set up WCS correctly).

Rotary axis naming (iTNC 530 default)
--------------------------------------
A = rotation around X (table tilt axis, "A-axis")
B = rotation around Y (head tilt axis, "B-axis")
(Some machines use A+C or B+C; the axis letter is set in machine parameters.
 We default to A/B matching the head_table convention.)

Reference
---------
Heidenhain iTNC 530 Programming Manual, ID 367456-xx (§12 Tilted working plane)
Heidenhain TNC 640 HEROS 5 Programming Manual, ID 685901-xx (§15 PLANE functions)
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from kerf_cam.five_axis.gcode_constant_tilt import PostOpts


def emit(
    cl_points: list[dict],
    ab_pairs: list[tuple[float, float]],
    opts: "PostOpts",
    warnings: list[str],
) -> str:
    """Emit a complete Heidenhain iTNC 530 5-axis dialogue program.

    Parameters
    ----------
    cl_points : list of {x, y, z, i, j, k} dicts — tool-tip positions (mm).
    ab_pairs  : list of (A_deg, B_deg) per CL point.
    opts      : PostOpts
    warnings  : list of warning comment strings.
    """
    _n = _make_blk(opts.no_n_numbers)
    pgm_name = "KERF_5X"

    lines: list[str] = []

    # --- Program header ---
    lines.append(f"BEGIN PGM {pgm_name} MM")

    # Warnings as Heidenhain comments (; or *)
    for w in warnings:
        msg = w.lstrip("; ").strip()
        lines.append(f"; {msg}")

    lines.append(f"; Generated by Kerf CAM — Heidenhain iTNC 530 5-axis post (head_table A/B)")
    lines.append(f"; Machine kinematic: {opts.machine_kinematic}")
    tcp_note = "PLANE SPATIAL TCPM ENABLED" if opts.use_tcp else "Raw A/B coords — machine handles WCS"
    lines.append(f"; TCP mode: {tcp_note}")
    if opts.tool is not None:
        lines.append(f"; {opts.tool.to_comment()}")
    lines.append("")

    # BLK FORM (rough stock — optional but good practice; use a nominal 300mm cube)
    lines.append(f"{_n()}BLK FORM 0.1 Z X-150 Y-150 Z-100")
    lines.append(f"{_n()}BLK FORM 0.2 X+150 Y+150 Z+0")

    # Tool call
    lines.append(f"{_n()}TOOL CALL {opts.tool_number} Z S{opts.spindle_rpm}")

    # Coolant
    if opts.coolant == "flood":
        lines.append(f"{_n()}M8")
    elif opts.coolant == "mist":
        lines.append(f"{_n()}M7")

    # Spindle start (M3 = CW; on Heidenhain, spindle on is implied by TOOL CALL S>0
    # but M3 makes it explicit for controllers that require it)
    lines.append(f"{_n()}M3")

    # Safe-Z retract, rotaries to zero
    lines.append(f"{_n()}L Z+50 A+0 B+0 FMAX")
    lines.append(f"{_n()}L X+0 Y+0 FMAX")

    # TCPM / PLANE SPATIAL block
    if opts.use_tcp:
        # PLANE SPATIAL activates TCPM.  SPA/SPB/SPC are spatial Euler angles
        # but for our head_table convention we use PLANE AXIAL with the per-point
        # A/B angles on each L block.  The simpler approach that works on most
        # iTNC 530 machines is PLANE AXIAL:
        # PLANE AXIAL does NOT exist — the correct cycle is PLANE SPATIAL.
        # For continuous 5-axis we use PLANE SPATIAL at each point by embedding
        # the PLANE SPATIAL call per-block which is iTNC 530 "continuous TCPM".
        # Actually, continuous 5-axis on iTNC 530 uses "M128" (RTCP mode on) +
        # L blocks with A/B embedded.  M128 activates TCPM for the duration.
        lines.append(f"{_n()}M128")   # TCPM on (PLANE SPATIAL equivalent)
        lines.append(f"; M128: TCPM active — controller maintains tool tip during rotation")

    if not cl_points:
        if opts.use_tcp:
            lines.append(f"{_n()}M129")   # TCPM off
        lines.append(f"{_n()}L Z+50 A+0 B+0 FMAX")
        lines.append(f"{_n()}M5")
        lines.append(f"{_n()}M9")
        lines.append(f"{_n()}M30")
        lines.append(f"END PGM {pgm_name} MM")
        return "\n".join(lines)

    # --- Rapid to first point ---
    p0 = cl_points[0]
    a0, b0 = ab_pairs[0]
    lines.append(
        f"{_n()}L"
        f" X{_hh(p0['x'])} Y{_hh(p0['y'])} Z{_hh(p0['z'] + 2.0)}"
        f" A{_hh(a0)} B{_hh(b0)}"
        f" FMAX"
    )

    # --- Cutting moves ---
    prev_feed: float | None = None
    for pt, (a_deg, b_deg) in zip(cl_points, ab_pairs):
        feed = float(pt.get("feed", pt.get("feed_rate", opts.feed_cut_mm_min)))
        if feed != prev_feed:
            feed_word = f" F{feed:.0f}"
            prev_feed = feed
        else:
            feed_word = ""
        lines.append(
            f"{_n()}L"
            f" X{_hh(pt['x'])} Y{_hh(pt['y'])} Z{_hh(pt['z'])}"
            f" A{_hh(a_deg)} B{_hh(b_deg)}"
            f"{feed_word}"
        )

    # --- Footer ---
    lines.append(f"{_n()}L Z+50 A+0 B+0 FMAX")
    if opts.use_tcp:
        lines.append(f"{_n()}M129")   # TCPM off
    lines.append(f"{_n()}M5")         # spindle off
    lines.append(f"{_n()}M9")         # coolant off
    lines.append(f"{_n()}M30")        # program end + rewind
    lines.append(f"END PGM {pgm_name} MM")

    return "\n".join(lines)


def emit_indexed_3_2(
    cl_points: list[dict],
    a_deg: float,
    b_deg: float,
    axis_aligned: bool,
    opts: "PostOpts",
    warnings: list[str],
) -> str:
    """Emit a Heidenhain 3+2 indexed program using PLANE SPATIAL.

    In indexed (3+2) mode the rotary axes are set ONCE using PLANE SPATIAL
    and then the cutting body is pure 3-axis L moves (no A/B on body lines).

    PLANE SPATIAL SPA<a> SPB<b> SPC<c> TURN FMAX STAY activates the tilted
    working plane and all subsequent L moves are interpreted in the tilted WCS.

    When axis_aligned is True (A=B=0) PLANE SPATIAL is omitted and the program
    is plain 3-axis.
    """
    _n = _make_blk(opts.no_n_numbers)
    pgm_name = "KERF_3P2"

    lines: list[str] = []
    lines.append(f"BEGIN PGM {pgm_name} MM")

    for w in warnings:
        msg = w.lstrip("; ").strip()
        lines.append(f"; {msg}")

    lines.append(f"; Generated by Kerf CAM — Heidenhain iTNC 530 3+2 indexed post")
    lines.append(f"; Machine kinematic: {opts.machine_kinematic}")
    if not axis_aligned:
        lines.append(f"; Indexed orientation: A={a_deg:.3f} B={b_deg:.3f}")
    else:
        lines.append("; Axis-aligned: no PLANE SPATIAL (plain 3-axis output)")
    if opts.tool is not None:
        lines.append(f"; {opts.tool.to_comment()}")
    lines.append("")

    lines.append(f"{_n()}BLK FORM 0.1 Z X-150 Y-150 Z-100")
    lines.append(f"{_n()}BLK FORM 0.2 X+150 Y+150 Z+0")
    lines.append(f"{_n()}TOOL CALL {opts.tool_number} Z S{opts.spindle_rpm}")

    if opts.coolant == "flood":
        lines.append(f"{_n()}M8")
    elif opts.coolant == "mist":
        lines.append(f"{_n()}M7")

    lines.append(f"{_n()}M3")
    lines.append(f"{_n()}L Z+50 A+0 B+0 FMAX")

    # Tilted working plane activation via PLANE SPATIAL
    if not axis_aligned:
        # SPA = A-axis angle (tilt around X = the "spatial pitch angle")
        # SPB = B-axis angle (tilt around Y = the "spatial roll angle")
        # SPC = 0 (no rotation around Z)
        lines.append(
            f"{_n()}PLANE SPATIAL SPA{_hh(a_deg)} SPB{_hh(b_deg)} SPC+0 TURN FMAX STAY"
        )
        lines.append(f"; Tilted working plane active (A={a_deg:.3f}°, B={b_deg:.3f}°)")

    if opts.coolant == "flood":
        lines.append(f"{_n()}M8")

    if not cl_points:
        if not axis_aligned:
            lines.append(f"{_n()}PLANE RESET STAY")
        lines.append(f"{_n()}L Z+50 A+0 B+0 FMAX")
        lines.append(f"{_n()}M5")
        lines.append(f"{_n()}M9")
        lines.append(f"{_n()}M30")
        lines.append(f"END PGM {pgm_name} MM")
        return "\n".join(lines)

    # Rapid to first XY at safe-Z
    p0 = cl_points[0]
    lines.append(f"{_n()}L X{_hh(p0['x'])} Y{_hh(p0['y'])} Z{_hh(p0['z'] + 2.0)} FMAX")

    # G1 plunge to first Z
    feed0 = float(p0.get("feed", p0.get("feed_rate", opts.feed_cut_mm_min)))
    lines.append(f"{_n()}L X{_hh(p0['x'])} Y{_hh(p0['y'])} Z{_hh(p0['z'])} F{feed0:.0f}")

    # Pure 3-axis body — no A/B
    prev_feed: float = feed0
    for pt in cl_points[1:]:
        feed = float(pt.get("feed", pt.get("feed_rate", opts.feed_cut_mm_min)))
        feed_word = f" F{feed:.0f}" if feed != prev_feed else ""
        prev_feed = feed
        lines.append(f"{_n()}L X{_hh(pt['x'])} Y{_hh(pt['y'])} Z{_hh(pt['z'])}{feed_word}")

    # Footer
    lines.append(f"{_n()}L Z+50 FMAX")
    if not axis_aligned:
        lines.append(f"{_n()}PLANE RESET STAY")  # cancel tilted WP
    lines.append(f"{_n()}L A+0 B+0 FMAX")         # home rotaries
    lines.append(f"{_n()}M5")
    lines.append(f"{_n()}M9")
    lines.append(f"{_n()}M30")
    lines.append(f"END PGM {pgm_name} MM")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _hh(v: float) -> str:
    """Format a coordinate in Heidenhain style: sign always explicit, 3 dec."""
    if v >= 0:
        return f"+{v:.3f}"
    return f"{v:.3f}"


def _make_blk(no_n_numbers: bool):
    """Return a callable that yields 'N<n> ' prefixes or empty strings."""
    counter = [0]

    def _next() -> str:
        if no_n_numbers:
            return ""
        counter[0] += 10
        return f"N{counter[0]} "

    return _next
