"""
LinuxCNC 5-axis post-processor.

Dialect notes
-------------
- G90  absolute positioning
- G94  feed-per-minute mode (used for rapid + cutting; G93 inverse-time is the
       theoretically "correct" mode for 5-axis simultaneous because it avoids
       feed discontinuities at rotary-only moves — but G94 is far more widely
       supported by hobby + small-VMC LinuxCNC builds and does not require the
       operator to compute inverse-time values.  We emit G94 for compatibility
       and document G93 as a known follow-on.  See report section for rationale.)
- G17  XY-plane
- G21  metric (mm)
- G54  work-coordinate system (standard WCS 1)
- G43.4 H<n>  TCP / tool-length compensation  (emitted when use_tcp=True or
       the default in our post — LinuxCNC's RTCP mode requires G43.4)
- M6 T<n>  tool call
- S<rpm> M3  spindle on CW
- M8  flood coolant on  (if opts.coolant == "flood")
- M7  mist coolant on  (if opts.coolant == "mist")
- A<deg> B<deg>  rotary axes on each G1 move
- M9 M5  coolant off, spindle off
- M30  program end + rewind
- %  tape-start / tape-end markers (LinuxCNC convention)

Feed handling
-------------
G94 feed-per-minute is used for all moves.  Per-CL-point feed overrides
opts.feed_cut_mm_min when the CLPoint dict carries a "feed" or "feed_rate" key.

G93 (inverse-time) rationale — why NOT shipped
-----------------------------------------------
G93 requires the controller to complete the move in (60 / F) minutes.  The
inverse-time value must be recomputed for every segment length + angular travel;
the math differs per kinematic family and is non-trivial to get right in the
general case.  LinuxCNC's own trajectory planner handles velocity limiting on
rotary axes automatically in G94 mode since v2.8 via "max_acceleration" joint
limits — making G93 strictly unnecessary for the machines Kerf targets
(small VMC, hobbyist router-converted 5-axis).  Ships as G94; G93 is noted as
a deferred enhancement in the plan.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from kerf_cam.five_axis.gcode_constant_tilt import PostOpts


def emit(
    cl_points: list[dict],
    ab_pairs: list[tuple[float, float]],
    opts: "PostOpts",
    warnings: list[str],
) -> str:
    """Emit a complete LinuxCNC 5-axis G-code program.

    Parameters
    ----------
    cl_points : list of {x, y, z, i, j, k} dicts — tool-tip positions.
    ab_pairs  : list of (A_deg, B_deg) per CL point — precomputed by emitter.
    opts      : PostOpts
    warnings  : list of warning comment strings (prepended to file).
    """
    lines: list[str] = []

    # --- Tape start ---
    lines.append("%")

    # --- Warnings ---
    for w in warnings:
        lines.append(w)

    # --- Header ---
    lines.append("; Generated by Kerf CAM — LinuxCNC 5-axis post (head_table A/B)")
    lines.append(f"; Machine kinematic: {opts.machine_kinematic}")
    lines.append(f"; TCP mode: {'G43.4 RTCP' if opts.use_tcp else 'tool-tip coords (machine handles RTCP)'}")
    if opts.tool is not None:
        lines.append(f"; {opts.tool.to_comment()}")
    lines.append("G90 G94 G17 G21")   # abs / feed-per-min / XY-plane / mm
    lines.append("G54")               # work offset
    lines.append(f"M6 T{opts.tool_number}")
    lines.append(f"G0 Z50.000 A0.000 B0.000")
    if opts.use_tcp:
        lines.append(f"G43.4 H{opts.tool_number}")
    else:
        lines.append(f"; G43.4 H{opts.tool_number}  ; uncomment to enable TCP if machine supports it")
    lines.append(f"S{opts.spindle_rpm} M3")
    if opts.coolant == "flood":
        lines.append("M8")
    elif opts.coolant == "mist":
        lines.append("M7")

    if not cl_points:
        lines.extend(["G0 Z50.000 A0.000 B0.000", "G49", "M9", "M5", "M30", "%"])
        return "\n".join(lines)

    # --- Rapid to first point ---
    p0 = cl_points[0]
    a0, b0 = ab_pairs[0]
    lines.append(
        f"G0 X{p0['x']:.3f} Y{p0['y']:.3f} Z{p0['z'] + 2.0:.3f} "
        f"A{a0:.3f} B{b0:.3f} "
        f"F{opts.feed_rapid_mm_min:.0f}"
    )

    # --- Cutting moves ---
    prev_feed: float | None = None
    for pt, (a_deg, b_deg) in zip(cl_points, ab_pairs):
        feed = float(pt.get("feed", pt.get("feed_rate", opts.feed_cut_mm_min)))
        feed_word = f" F{feed:.0f}" if feed != prev_feed else ""
        prev_feed = feed
        lines.append(
            f"G1 X{pt['x']:.3f} Y{pt['y']:.3f} Z{pt['z']:.3f} "
            f"A{a_deg:.3f} B{b_deg:.3f}"
            f"{feed_word}"
        )

    # --- Footer ---
    lines.append(f"G0 Z50.000 A0.000 B0.000 F{opts.feed_rapid_mm_min:.0f}")
    lines.append("G49")   # cancel tool-length compensation
    lines.append("M9")    # coolant off
    lines.append("M5")    # spindle off
    lines.append("M30")   # program end + rewind
    lines.append("%")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# 3+2 indexed emitter (T6)
# ---------------------------------------------------------------------------

def emit_indexed_3_2(
    cl_points: list[dict],
    a_deg: float,
    b_deg: float,
    axis_aligned: bool,
    opts: "PostOpts",
    warnings: list[str],
) -> str:
    """Emit a complete LinuxCNC 3+2 indexed G-code program.

    A/B are emitted ONCE in the orientation move at the top; body G1 lines
    carry X/Y/Z only.  When axis_aligned is True, the orientation move is
    skipped (plain 3-axis output).

    Parameters
    ----------
    cl_points   : list of {x, y, z} dicts — tool-tip positions (rotated frame).
    a_deg       : A-axis angle in degrees for the one orientation move.
    b_deg       : B-axis angle in degrees for the one orientation move.
    axis_aligned: True → skip orientation move + home move is still emitted.
    opts        : PostOpts
    warnings    : list of warning comment strings to prepend.
    """
    lines: list[str] = []

    # --- Tape start ---
    lines.append("%")

    # --- Warnings ---
    for w in warnings:
        lines.append(w)

    # --- Header ---
    lines.append("; Generated by Kerf CAM — LinuxCNC 3+2 indexed post (head_table A/B)")
    lines.append(f"; Machine kinematic: {opts.machine_kinematic}")
    lines.append(f"; TCP mode: {'G43.4 RTCP' if opts.use_tcp else 'tool-tip coords (machine handles RTCP)'}")
    if not axis_aligned:
        lines.append(f"; Indexed orientation: A={a_deg:.3f} B={b_deg:.3f}")
    else:
        lines.append("; Axis-aligned: no rotation move (A=0, B=0)")
    if opts.tool is not None:
        lines.append(f"; {opts.tool.to_comment()}")
    lines.append("G90 G94 G17 G21")   # abs / feed-per-min / XY-plane / mm
    lines.append("G54")               # work offset
    lines.append(f"M6 T{opts.tool_number}")
    lines.append(f"G0 Z50.000 A0.000 B0.000")
    if opts.use_tcp:
        lines.append(f"G43.4 H{opts.tool_number}")
    else:
        lines.append(f"; G43.4 H{opts.tool_number}  ; uncomment to enable TCP if machine supports it")

    # --- ONE orientation move (skipped when axis-aligned) ---
    if not axis_aligned:
        lines.append(f"G0 A{a_deg:.3f} B{b_deg:.3f} F{opts.feed_rapid_mm_min:.0f}")

    lines.append(f"S{opts.spindle_rpm} M3")
    if opts.coolant == "flood":
        lines.append("M8")
    elif opts.coolant == "mist":
        lines.append("M7")

    if not cl_points:
        lines.extend([
            f"G0 Z50.000 F{opts.feed_rapid_mm_min:.0f}",
            "G0 A0.000 B0.000",
            "G49",
            "M9",
            "M5",
            "M30",
            "%",
        ])
        return "\n".join(lines)

    # --- Rapid to safe-Z + first XY ---
    p0 = cl_points[0]
    lines.append(
        f"G0 X{p0['x']:.3f} Y{p0['y']:.3f} Z{p0['z'] + 2.0:.3f} "
        f"F{opts.feed_rapid_mm_min:.0f}"
    )

    # --- G1 plunge to first Z ---
    feed0 = float(p0.get("feed", p0.get("feed_rate", opts.feed_cut_mm_min)))
    lines.append(
        f"G1 X{p0['x']:.3f} Y{p0['y']:.3f} Z{p0['z']:.3f} F{feed0:.0f}"
    )

    # --- Pure 3-axis body — no A/B on G1 lines ---
    prev_feed: float = feed0
    for pt in cl_points[1:]:
        feed = float(pt.get("feed", pt.get("feed_rate", opts.feed_cut_mm_min)))
        feed_word = f" F{feed:.0f}" if feed != prev_feed else ""
        prev_feed = feed
        lines.append(
            f"G1 X{pt['x']:.3f} Y{pt['y']:.3f} Z{pt['z']:.3f}{feed_word}"
        )

    # --- Footer: retract, home rotaries, end ---
    lines.append(f"G0 Z50.000 F{opts.feed_rapid_mm_min:.0f}")
    lines.append("G0 A0.000 B0.000")   # return rotaries to home
    lines.append("G49")                # cancel tool-length compensation
    lines.append("M9")                 # coolant off
    lines.append("M5")                 # spindle off
    lines.append("M30")                # program end + rewind
    lines.append("%")

    return "\n".join(lines)
