"""
Siemens SINUMERIK 840D sl 5-axis post-processor.

Dialect notes
-------------
SINUMERIK 840D uses standard DIN 66025 / ISO 6983 G-code but with extensive
Siemens-specific extensions for 5-axis machining:

  - G0 / G1  — rapid / linear interpolation (standard)
  - G17       — XY working plane
  - G90       — absolute coordinates
  - G94       — feed per minute
  - G71       — metric (inch: G70)
  - T<n>      — tool selection (no M6 in block; M6 on next line or implicit)
  - M6        — tool change activation
  - S<rpm> M3 — spindle speed + CW rotation
  - M8 / M7   — flood / mist coolant on
  - M9        — coolant off
  - M5        — spindle off
  - M30       — program end + rewind

TRAORI — 5-axis RTCP (Tool Radius Compensation with Orientation)
----------------------------------------------------------------
SINUMERIK 840D's RTCP equivalent is called TRAORI (TRAnsformation ORIentation).
It activates the 5-axis kinematic transformation and tool-tip tracking.

    TRAORI                   ; activate 5-axis transformation
    G0 X<x> Y<y> Z<z> A<a> B<b>   ; move with RTCP active
    TRAFOOF                  ; deactivate transformation

TRAORI requires a TRAORI data block to be defined in the machine parameters
(MD 24000 ... MD 24050) matching the physical kinematic chain.  The post
emits TRAORI blocks when opts.use_tcp is True; when False it emits raw
A/B coordinates (TCP pre-computed by the programmer).

CYCLE800 — tilted working plane (3+2 indexed)
----------------------------------------------
For 3+2 indexed machining, SINUMERIK uses CYCLE800:

    CYCLE800(1,"T1",0,57,0,0,0,A_ang,B_ang,0,1,-1,100,1)

Parameters (subset used here):
    P1=1       — frame selection (CYCLE800 = 1 for tilted WP)
    P2="T1"    — tool holder frame name (string)
    P3=0       — type: 0=no retract, 1=retract to safety plane, 3=retract + reposition
    P4=57      — rotation mode: 57 = "rotation of workpiece frame" (most common)
    P5..P7=0   — SX, SY, SZ: workpiece origin shift (none here)
    P8=A_ang   — rotation around X (A axis), degrees
    P9=B_ang   — rotation around Y (B axis), degrees
    P10=0      — rotation around Z (C axis), degrees
    P11=1      — direction: 1=clockwise of axes
    P12=-1     — rotation sequence (-1=factory default)
    P13=100    — feed for repositioning
    P14=1      — mode: 1=set new frame + keep tool orientation

    CYCLE800()  ; (no args) resets CYCLE800 (cancel tilted WP)

Reference
---------
Siemens SINUMERIK 840D sl Programming Manual Cycles, ID A5E33879855
§ CYCLE800 Swivel working plane (pp. 2-10 to 2-30)
Siemens SINUMERIK 840D sl Programming Manual Advanced, ID A5E02129384
§ 14.5 TRAORI — Transformation for 5-axis machining
Siemens SINUMERIK 840D sl Function Manual Special Functions, ID A5E02129384
§ F2 Polynomial Interpolation + 5-Axis Transformation
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from kerf_cam.five_axis.gcode_constant_tilt import PostOpts


def emit(
    cl_points: list[dict],
    ab_pairs: list[tuple[float, float]],
    opts: "PostOpts",
    warnings: list[str],
) -> str:
    """Emit a complete Siemens 840D 5-axis program using TRAORI.

    Parameters
    ----------
    cl_points : list of {x, y, z, i, j, k} dicts — tool-tip positions (mm).
    ab_pairs  : list of (A_deg, B_deg) per CL point.
    opts      : PostOpts
    warnings  : list of warning comment strings.
    """
    lines: list[str] = []

    # --- Warnings ---
    for w in warnings:
        msg = w.lstrip("; ").strip()
        lines.append(f"; {msg}")

    # --- Header ---
    lines.append("; Generated by Kerf CAM — Siemens 840D 5-axis post (head_table A/B)")
    lines.append(f"; Machine kinematic: {opts.machine_kinematic}")
    tcp_note = "TRAORI RTCP ENABLED" if opts.use_tcp else "Raw A/B coords — machine handles WCS"
    lines.append(f"; TCP mode: {tcp_note}")
    if opts.tool is not None:
        lines.append(f"; {opts.tool.to_comment()}")

    lines.append("G17 G90 G94 G71")   # XY plane, absolute, feed/min, metric
    lines.append(f"T{opts.tool_number}")
    lines.append("M6")
    lines.append(f"G0 Z50 A0 B0")

    if opts.use_tcp:
        lines.append("TRAORI")         # activate 5-axis transformation (RTCP)
        lines.append("; TRAORI: RTCP active — controller tracks tool tip during rotation")

    lines.append(f"S{opts.spindle_rpm} M3")

    if opts.coolant == "flood":
        lines.append("M8")
    elif opts.coolant == "mist":
        lines.append("M7")

    if not cl_points:
        if opts.use_tcp:
            lines.append("TRAFOOF")
        lines.append("G0 Z50 A0 B0")
        lines.append("M5")
        lines.append("M9")
        lines.append("M30")
        return "\n".join(lines)

    # --- Rapid to first point ---
    p0 = cl_points[0]
    a0, b0 = ab_pairs[0]
    lines.append(
        f"G0 X{p0['x']:.3f} Y{p0['y']:.3f} Z{p0['z'] + 2.0:.3f}"
        f" A{a0:.3f} B{b0:.3f}"
    )

    # --- Cutting moves ---
    prev_feed: float | None = None
    for pt, (a_deg, b_deg) in zip(cl_points, ab_pairs):
        feed = float(pt.get("feed", pt.get("feed_rate", opts.feed_cut_mm_min)))
        feed_word = f" F{feed:.0f}" if feed != prev_feed else ""
        prev_feed = feed
        lines.append(
            f"G1 X{pt['x']:.3f} Y{pt['y']:.3f} Z{pt['z']:.3f}"
            f" A{a_deg:.3f} B{b_deg:.3f}"
            f"{feed_word}"
        )

    # --- Footer ---
    lines.append(f"G0 Z50 A0 B0")
    if opts.use_tcp:
        lines.append("TRAFOOF")        # deactivate 5-axis transformation
    lines.append("M5")
    lines.append("M9")
    lines.append("M30")

    return "\n".join(lines)


def emit_indexed_3_2(
    cl_points: list[dict],
    a_deg: float,
    b_deg: float,
    axis_aligned: bool,
    opts: "PostOpts",
    warnings: list[str],
) -> str:
    """Emit a Siemens 840D 3+2 indexed program using CYCLE800.

    In 3+2 mode, CYCLE800 activates the tilted working plane with the
    specified A/B angles.  Body G1 lines are pure 3-axis XYZ.
    At end-of-program CYCLE800() (no args) resets the tilted WP.

    When axis_aligned is True (A=B=0) CYCLE800 is omitted.
    """
    lines: list[str] = []

    for w in warnings:
        msg = w.lstrip("; ").strip()
        lines.append(f"; {msg}")

    lines.append("; Generated by Kerf CAM — Siemens 840D 3+2 indexed post (CYCLE800)")
    lines.append(f"; Machine kinematic: {opts.machine_kinematic}")
    if not axis_aligned:
        lines.append(f"; Indexed orientation: A={a_deg:.3f} B={b_deg:.3f}")
    else:
        lines.append("; Axis-aligned: CYCLE800 skipped (plain 3-axis output)")
    if opts.tool is not None:
        lines.append(f"; {opts.tool.to_comment()}")

    lines.append("G17 G90 G94 G71")
    lines.append(f"T{opts.tool_number}")
    lines.append("M6")
    lines.append(f"G0 Z50 A0 B0")
    lines.append(f"S{opts.spindle_rpm} M3")

    if opts.coolant == "flood":
        lines.append("M8")
    elif opts.coolant == "mist":
        lines.append("M7")

    # Activate tilted working plane via CYCLE800
    if not axis_aligned:
        # CYCLE800 parameter list (Siemens 840D Cycles Manual §CYCLE800):
        # (stat, tc, mode, mdir, X0, Y0, Z0, A, B, C, dir, rotrp, fr, tilt)
        # stat=1: frame is defined via angles
        # tc="T1": tool carrier name (tool holder)
        # mode=0: no retract
        # mdir=57: rotate WCS by machine angles
        # X0=Y0=Z0=0: no origin shift
        # A=a_deg, B=b_deg, C=0: angles
        # dir=1: positive direction
        # rotrp=-1: factory default rotation sequence
        # fr=100: feed for repositioning (mm/min)
        # tilt=1: set new frame + keep tool orientation
        lines.append(
            f'CYCLE800(1,"T1",0,57,0,0,0,{a_deg:.3f},{b_deg:.3f},0,1,-1,100,1)'
        )
        lines.append(f"; CYCLE800: tilted WP active A={a_deg:.3f}° B={b_deg:.3f}°")

    if not cl_points:
        if not axis_aligned:
            lines.append("CYCLE800()")    # reset tilted WP
        lines.append("G0 Z50 A0 B0")
        lines.append("M5")
        lines.append("M9")
        lines.append("M30")
        return "\n".join(lines)

    # Rapid to first XY at safe-Z (3-axis — no A/B)
    p0 = cl_points[0]
    lines.append(f"G0 X{p0['x']:.3f} Y{p0['y']:.3f} Z{p0['z'] + 2.0:.3f}")

    # G1 plunge to first Z
    feed0 = float(p0.get("feed", p0.get("feed_rate", opts.feed_cut_mm_min)))
    lines.append(f"G1 X{p0['x']:.3f} Y{p0['y']:.3f} Z{p0['z']:.3f} F{feed0:.0f}")

    # Pure 3-axis body — no A/B
    prev_feed: float = feed0
    for pt in cl_points[1:]:
        feed = float(pt.get("feed", pt.get("feed_rate", opts.feed_cut_mm_min)))
        feed_word = f" F{feed:.0f}" if feed != prev_feed else ""
        prev_feed = feed
        lines.append(f"G1 X{pt['x']:.3f} Y{pt['y']:.3f} Z{pt['z']:.3f}{feed_word}")

    # Footer
    lines.append("G0 Z50")
    if not axis_aligned:
        lines.append("CYCLE800()")    # cancel tilted WP
    lines.append("G0 A0 B0")          # home rotaries
    lines.append("M5")
    lines.append("M9")
    lines.append("M30")

    return "\n".join(lines)
