"""LLM tool: make_arduino_sketch(spec) — deterministic template synthesizer.

Supported patterns (case-insensitive substring match):
  1. "blink"             — blink LED on pin N
  2. "dht22"             — read DHT22 temperature/humidity sensor (Adafruit DHT)
  3. "servo"             — control servo with potentiometer
  4. "accelerometer"     — log accelerometer over serial (MPU6050)
  5. "pwm motor"         — PWM motor speed from analog input

Returns:
  {"sketch": str, "manifest": dict}   on success
  {"error": str, "spec": str}          on unknown pattern

Every emitted sketch contains void setup() + void loop().
"""
from __future__ import annotations

import re
from typing import Any

from .project_manifest import make_manifest


# ── helpers ────────────────────────────────────────────────────────────────────

def _extract_pin(spec: str, default: int = 13) -> int:
    """Extract the first integer that looks like a pin number from *spec*."""
    m = re.search(r'\bpin\s+(\d+)\b', spec, re.IGNORECASE)
    if m:
        return int(m.group(1))
    # Also match bare numbers like "pin13" or "on 9"
    m2 = re.search(r'\b(\d{1,2})\b', spec)
    if m2:
        return int(m2.group(1))
    return default


# ── sketch templates ────────────────────────────────────────────────────────────

def _make_blink(spec: str) -> tuple[str, dict[str, Any]]:
    pin = _extract_pin(spec, default=13)
    sketch = f"""\
/*
 * Blink — generated by kerf make_arduino_sketch
 * Spec: {spec}
 */

const int LED_PIN = {pin};

void setup() {{
  pinMode(LED_PIN, OUTPUT);
}}

void loop() {{
  digitalWrite(LED_PIN, HIGH);
  delay(500);
  digitalWrite(LED_PIN, LOW);
  delay(500);
}}
"""
    manifest = make_manifest(
        name="blink",
        board="arduino-uno-r3",
        libraries=[],
        sources=["sketch/blink.ino"],
        build_flags=[],
        monitor_speed=0,
    )
    return sketch, manifest


def _make_dht22(spec: str) -> tuple[str, dict[str, Any]]:
    pin = _extract_pin(spec, default=2)
    sketch = f"""\
/*
 * DHT22 Temperature & Humidity — generated by kerf make_arduino_sketch
 * Spec: {spec}
 * Library: Adafruit DHT sensor library
 */

#include <DHT.h>

#define DHTPIN {pin}
#define DHTTYPE DHT22

DHT dht(DHTPIN, DHTTYPE);

void setup() {{
  Serial.begin(9600);
  dht.begin();
}}

void loop() {{
  delay(2000);
  float humidity = dht.readHumidity();
  float temperature = dht.readTemperature();

  if (isnan(humidity) || isnan(temperature)) {{
    Serial.println("Failed to read from DHT sensor!");
    return;
  }}

  Serial.print("Humidity: ");
  Serial.print(humidity);
  Serial.print("%  Temperature: ");
  Serial.print(temperature);
  Serial.println("°C");
}}
"""
    manifest = make_manifest(
        name="dht22-sensor",
        board="arduino-uno-r3",
        libraries=[{"name": "DHT sensor library", "version": "1.4.4"}],
        sources=["sketch/dht22_sensor.ino"],
        build_flags=[],
        monitor_speed=9600,
    )
    return sketch, manifest


def _make_servo(spec: str) -> tuple[str, dict[str, Any]]:
    sketch = """\
/*
 * Servo control with potentiometer — generated by kerf make_arduino_sketch
 * Spec: {spec}
 * Library: Servo (built-in)
 */

#include <Servo.h>

const int SERVO_PIN = 9;
const int POT_PIN   = A0;

Servo myServo;

void setup() {{
  myServo.attach(SERVO_PIN);
  Serial.begin(9600);
}}

void loop() {{
  int potValue  = analogRead(POT_PIN);
  int angle     = map(potValue, 0, 1023, 0, 180);
  myServo.write(angle);
  Serial.print("Angle: ");
  Serial.println(angle);
  delay(15);
}}
""".format(spec=spec)
    manifest = make_manifest(
        name="servo-pot",
        board="arduino-uno-r3",
        libraries=[{"name": "Servo", "version": "1.1.8"}],
        sources=["sketch/servo_pot.ino"],
        build_flags=[],
        monitor_speed=9600,
    )
    return sketch, manifest


def _make_accelerometer(spec: str) -> tuple[str, dict[str, Any]]:
    sketch = f"""\
/*
 * MPU6050 Accelerometer Logger — generated by kerf make_arduino_sketch
 * Spec: {spec}
 * Library: MPU6050 by Electronic Cats
 */

#include <Wire.h>
#include <MPU6050.h>

MPU6050 mpu;

void setup() {{
  Serial.begin(115200);
  Wire.begin();
  mpu.initialize();

  if (!mpu.testConnection()) {{
    Serial.println("MPU6050 connection failed");
    while (1);
  }}
  Serial.println("MPU6050 ready");
}}

void loop() {{
  int16_t ax, ay, az;
  int16_t gx, gy, gz;
  mpu.getMotion6(&ax, &ay, &az, &gx, &gy, &gz);

  Serial.print("AX: "); Serial.print(ax);
  Serial.print(" AY: "); Serial.print(ay);
  Serial.print(" AZ: "); Serial.print(az);
  Serial.print(" GX: "); Serial.print(gx);
  Serial.print(" GY: "); Serial.print(gy);
  Serial.print(" GZ: "); Serial.println(gz);

  delay(100);
}}
"""
    manifest = make_manifest(
        name="accel-logger",
        board="arduino-uno-r3",
        libraries=[{"name": "MPU6050", "version": "0.3.1"}],
        sources=["sketch/accel_logger.ino"],
        build_flags=["-DDEBUG=1"],
        monitor_speed=115200,
    )
    return sketch, manifest


def _make_pwm_motor(spec: str) -> tuple[str, dict[str, Any]]:
    sketch = f"""\
/*
 * PWM Motor Speed from Analog Input — generated by kerf make_arduino_sketch
 * Spec: {spec}
 */

const int MOTOR_PWM_PIN = 3;   // Must be a PWM-capable pin
const int ANALOG_IN_PIN = A0;

void setup() {{
  pinMode(MOTOR_PWM_PIN, OUTPUT);
  Serial.begin(9600);
}}

void loop() {{
  int sensorVal = analogRead(ANALOG_IN_PIN);
  int pwmVal    = map(sensorVal, 0, 1023, 0, 255);
  analogWrite(MOTOR_PWM_PIN, pwmVal);

  Serial.print("Sensor: ");
  Serial.print(sensorVal);
  Serial.print("  PWM: ");
  Serial.println(pwmVal);

  delay(50);
}}
"""
    manifest = make_manifest(
        name="pwm-motor",
        board="arduino-uno-r3",
        libraries=[],
        sources=["sketch/pwm_motor.ino"],
        build_flags=[],
        monitor_speed=9600,
    )
    return sketch, manifest


# ── pattern registry ──────────────────────────────────────────────────────────

_PATTERNS: list[tuple[str, Any]] = [
    ("dht22",        _make_dht22),
    ("servo",        _make_servo),
    ("accelerometer", _make_accelerometer),
    ("pwm motor",    _make_pwm_motor),
    ("motor",        _make_pwm_motor),
    ("blink",        _make_blink),
]


# ── public API ────────────────────────────────────────────────────────────────

def make_arduino_sketch(spec: str) -> dict[str, Any]:
    """Generate an Arduino sketch from a natural-language *spec*.

    Returns ``{"sketch": str, "manifest": dict}`` on a recognised pattern, or
    ``{"error": str, "spec": str}`` when no pattern matches.

    The *spec* is matched case-insensitively.  More specific patterns are
    checked before shorter / more generic ones.
    """
    spec_lower = spec.lower()

    for keyword, factory in _PATTERNS:
        if keyword in spec_lower:
            sketch, manifest = factory(spec)
            return {"sketch": sketch, "manifest": manifest}

    return {
        "error": (
            f"Unrecognised spec: {spec!r}. "
            "Supported patterns: blink LED, DHT22 temperature sensor, "
            "servo with potentiometer, accelerometer over serial, "
            "PWM motor speed."
        ),
        "spec": spec,
    }
