// circuitToSpice.test.js — vitest coverage for the pure netlist emitter.
//
// tscircuit deviation note: the brief listed `simple_bjt_transistor` and a
// distinct `simple_mosfet` ftype, but the actual values shipped by
// `@tscircuit/core` + `circuit-json` are `simple_transistor` (covers BJT) and
// `simple_mosfet`. The emitter accepts both `simple_transistor` and
// `simple_bjt_transistor` for forward-compat; tests target the real values.

import { describe, it, expect } from 'vitest'
import { circuitToSpice } from '../lib/circuitToSpice.js'

// --- fixture builders -----------------------------------------------------
// Loosely-typed on purpose: the real CircuitJson union has 200+ literal-`type`
// members with divergent required fields, far stricter than these minimal
// fixtures need to be.

const comp = (id: string, ftype: string, name: string, extra = {}): any => ({
  type: 'source_component',
  source_component_id: id,
  ftype,
  name,
  ...extra,
})
const port = (id: string, compId: string, pin: number): any => ({
  type: 'source_port',
  source_port_id: id,
  source_component_id: compId,
  pin_number: pin,
})
const trace = (...portIds: string[]): any => ({
  type: 'source_trace',
  connected_source_port_ids: portIds,
})

// V1(+) -- R1 -- mid -- R2 -- GND, V1(-) -- GND
const rDivider = () => [
  comp('c_v1', 'simple_voltage_source', 'V1', { voltage: 5 }),
  comp('c_r1', 'simple_resistor', 'R1', { resistance: 1000 }),
  comp('c_r2', 'simple_resistor', 'R2', { resistance: 2000 }),
  comp('c_gnd', 'simple_ground', 'GND'),
  port('p_v1_plus', 'c_v1', 1),
  port('p_v1_minus', 'c_v1', 2),
  port('p_r1_a', 'c_r1', 1),
  port('p_r1_b', 'c_r1', 2),
  port('p_r2_a', 'c_r2', 1),
  port('p_r2_b', 'c_r2', 2),
  port('p_gnd', 'c_gnd', 1),
  trace('p_v1_plus', 'p_r1_a'),
  trace('p_r1_b', 'p_r2_a'),
  trace('p_r2_b', 'p_gnd'),
  trace('p_v1_minus', 'p_gnd'),
]

describe('circuitToSpice — R divider', () => {
  const out = circuitToSpice(rDivider())

  it('returns no errors for a complete divider', () => {
    expect(out.errors).toEqual([])
  })

  it('header comment is the first line', () => {
    expect(out.netlist.split('\n')[0]).toBe('* Generated by Kerf circuitToSpice — DO NOT EDIT')
  })

  it('terminates with .end', () => {
    expect(out.netlist.trimEnd().endsWith('.end')).toBe(true)
  })

  it('emits R1 and R2 with their values', () => {
    expect(out.netlist).toMatch(/RR1 \d+ \d+ 1000/)
    expect(out.netlist).toMatch(/RR2 \d+ \d+ 2000/)
  })

  it('emits a DC voltage source', () => {
    expect(out.netlist).toMatch(/VV1 \d+ 0 DC 5/)
  })

  it('GND collapses to net 0', () => {
    // R2's second pin is wired to GND, so its second net must be 0.
    expect(out.netlist).toMatch(/RR2 \d+ 0 2000/)
  })

  it('the divider mid-net is shared by R1.b and R2.a', () => {
    const r1 = out.netlist.match(/RR1 (\d+) (\d+) 1000/)
    const r2 = out.netlist.match(/RR2 (\d+) (\d+) 2000/)
    expect(r1[2]).toBe(r2[1])
  })
})

describe('circuitToSpice — passive prefix letters', () => {
  const out = circuitToSpice([
    comp('c_c1', 'simple_capacitor', 'C1', { capacitance: 1e-6 }),
    comp('c_l1', 'simple_inductor', 'L1', { inductance: 1e-3 }),
    comp('c_gnd', 'simple_ground', 'GND'),
    port('p_c1_a', 'c_c1', 1),
    port('p_c1_b', 'c_c1', 2),
    port('p_l1_a', 'c_l1', 1),
    port('p_l1_b', 'c_l1', 2),
    port('p_gnd', 'c_gnd', 1),
    trace('p_c1_a', 'p_l1_a'),
    trace('p_c1_b', 'p_gnd'),
    trace('p_l1_b', 'p_gnd'),
  ])

  it('capacitor uses C prefix', () => {
    expect(out.netlist).toMatch(/CC1 \d+ 0 0\.000001/)
  })

  it('inductor uses L prefix', () => {
    expect(out.netlist).toMatch(/LL1 \d+ 0 0\.001/)
  })
})

describe('circuitToSpice — voltage source waveforms', () => {
  const baseSrc = (waveform) => [
    comp('c_v1', 'simple_voltage_source', 'V1', { waveform }),
    comp('c_gnd', 'simple_ground', 'GND'),
    port('p_v1_plus', 'c_v1', 1),
    port('p_v1_minus', 'c_v1', 2),
    port('p_gnd', 'c_gnd', 1),
    trace('p_v1_plus', 'p_gnd'),
    trace('p_v1_minus', 'p_gnd'),
  ]

  it('sine waveform emits SIN(offset amp freq)', () => {
    const out = circuitToSpice(baseSrc({ type: 'sine', amplitude: 1, frequency: 1000 }))
    expect(out.netlist).toMatch(/VV1 \d+ \d+ SIN\(0 1 1000\)/)
  })

  it('pulse waveform emits the full PULSE(...) tuple', () => {
    const out = circuitToSpice(baseSrc({
      type: 'pulse', v1: 0, v2: 5, td: 0, tr: '1n', tf: '1n', pw: '1u', per: '2u',
    }))
    expect(out.netlist).toMatch(/VV1 \d+ \d+ PULSE\(0 5 0 1n 1n 1u 2u\)/)
  })
})

describe('circuitToSpice — error paths', () => {
  it('missing resistance flags an error and skips R1', () => {
    const out = circuitToSpice([
      comp('c_r1', 'simple_resistor', 'R1', {}),
      comp('c_gnd', 'simple_ground', 'GND'),
      port('p_r1_a', 'c_r1', 1),
      port('p_r1_b', 'c_r1', 2),
      port('p_gnd', 'c_gnd', 1),
      trace('p_r1_a', 'p_gnd'),
      trace('p_r1_b', 'p_gnd'),
    ])
    expect(out.errors.some((e) => /R1.*resistance/.test(e))).toBe(true)
    expect(out.netlist).not.toMatch(/RR1 /)
  })

  it('voltage source with no voltage and no waveform errors', () => {
    const out = circuitToSpice([
      comp('c_v1', 'simple_voltage_source', 'V1', {}),
      comp('c_gnd', 'simple_ground', 'GND'),
      port('p_v1_plus', 'c_v1', 1),
      port('p_v1_minus', 'c_v1', 2),
      port('p_gnd', 'c_gnd', 1),
      trace('p_v1_plus', 'p_gnd'),
      trace('p_v1_minus', 'p_gnd'),
    ])
    expect(out.errors.length).toBeGreaterThan(0)
  })

  it('dangling port emits an error', () => {
    const out = circuitToSpice([
      comp('c_r1', 'simple_resistor', 'R1', { resistance: 100 }),
      port('p_r1_a', 'c_r1', 1),
      port('p_r1_b', 'c_r1', 2),
      // no traces at all
    ])
    expect(out.errors.some((e) => /dangling/.test(e))).toBe(true)
  })

  it('errors block analysis directives but still close with .end', () => {
    const out = circuitToSpice([
      comp('c_r1', 'simple_resistor', 'R1', {}), // missing resistance
    ], { analysis: { type: 'tran', tstep: '1u', tstop: '1m' } })
    expect(out.netlist).not.toMatch(/\.tran/)
    expect(out.netlist.trimEnd().endsWith('.end')).toBe(true)
  })
})

describe('circuitToSpice — diode model placeholder', () => {
  const out = circuitToSpice([
    comp('c_d1', 'simple_diode', 'D1'),
    comp('c_gnd', 'simple_ground', 'GND'),
    port('p_d1_a', 'c_d1', 1),
    port('p_d1_k', 'c_d1', 2),
    port('p_gnd', 'c_gnd', 1),
    trace('p_d1_a', 'p_gnd'),
    trace('p_d1_k', 'p_gnd'),
  ])

  it('emits D-line referencing DMOD_ model', () => {
    expect(out.netlist).toMatch(/DD1 \d+ \d+ DMOD_D1/)
  })

  it('emits a generic .model card and warns', () => {
    expect(out.netlist).toMatch(/\.model DMOD_D1 D/)
    expect(out.warnings.some((w) => /D1.*spice_model/.test(w))).toBe(true)
  })
})

describe('circuitToSpice — probe convention', () => {
  const fixture = [
    ...rDivider(),
    {
      type: 'simulation_probe',
      _kerf_probe: true,
      name: 'VOUT',
      kind: 'V',
      source_port_id: 'p_r1_b',
    },
  ]
  const out = circuitToSpice(fixture)

  it('probe surfaces in the probes array', () => {
    expect(out.probes).toEqual([{ name: 'VOUT', kind: 'V', netOrComp: expect.any(Number) }])
  })

  it('probe round-trips into a .print TRAN V(<net>) directive', () => {
    expect(out.netlist).toMatch(/\.print TRAN V\(\d+\)/)
  })
})

describe('circuitToSpice — determinism', () => {
  it('same input produces byte-identical netlist twice', () => {
    const a = circuitToSpice(rDivider()).netlist
    const b = circuitToSpice(rDivider()).netlist
    expect(a).toBe(b)
  })

  it('shuffled component order still produces the same netlist', () => {
    const ordered = rDivider()
    const shuffled = [...ordered].reverse()
    const a = circuitToSpice(ordered).netlist
    const b = circuitToSpice(shuffled).netlist
    expect(a).toBe(b)
  })
})
