"""Seed entrypoint — fetch -> convert -> write into the system-owned
"Parts Library" project.

This mirrors Kerf's real seed mechanism. There is intentionally no Python
``seed:materials`` npm script; the genuine pattern for system-owned library
content is: resolve the system user (``KERF_SYSTEM_USER_EMAIL``, default
``local@kerf.local`` — same value ``/auth/bootstrap-local`` uses), find/make
its workspace, find/make a Library project, then upsert ``kind='part'``
files into the ``files`` table (the exact representation
``kerf_api.tools.scaffold.run_create_part`` writes and
``kerf_core.db.queries.library`` / the BOM reads back).

Idempotent + content-hash incremental: each part carries a stable
``content_hash``; on re-run an unchanged part is skipped, a changed one is
updated in place (with a file_revision recorded), and removed upstream parts
are left intact (never destructive).

Licensing: third-party data is NOT redistributed by Kerf. The attribution /
NOTICE file is emitted into the **gitignored** generated output dir
(``.parts-cache/_generated/`` by default), never into the repo.
"""
from __future__ import annotations

import argparse
import asyncio
import json
import sys
from pathlib import Path
from typing import Optional

from .adapters import get_adapter
from .fetch import DEFAULT_CACHE_DIR, fetch_all
from .manifest import Source, load_manifest, select_sources
from .model import KerfPart

PARTS_LIBRARY_PROJECT = "Parts Library"
GENERATED_DIRNAME = "_generated"
NOTICE_FILENAME = "ATTRIBUTION-NOTICE.txt"


# --------------------------------------------------------------------------
# Conversion (pure-ish: fetch already done, just run adapters)
# --------------------------------------------------------------------------

def convert_sources(
    sources: list[Source],
    cache_dir: Path,
    *,
    log=print,
) -> list[KerfPart]:
    """Run each source's adapter over its cache dir; return all KerfParts."""
    all_parts: list[KerfPart] = []
    for s in sources:
        src_dir = cache_dir / s.name
        if not src_dir.exists():
            log(f"  [{s.name}] cache missing ({src_dir}) — run fetch first; skip")
            continue
        try:
            adapter = get_adapter(s.adapter)
        except KeyError as exc:
            log(f"  [{s.name}] {exc}")
            continue
        try:
            parts = adapter(s, src_dir)
        except Exception as exc:  # noqa: BLE001 - adapters report, don't crash seed
            log(f"  [{s.name}] adapter error: {exc}")
            continue
        log(f"  [{s.name}] {len(parts)} part(s) converted")
        all_parts.extend(parts)
    return all_parts


def write_notice(generated_dir: Path, sources: list[Source]) -> Path:
    """Emit the attribution/NOTICE into the GITIGNORED generated dir."""
    generated_dir.mkdir(parents=True, exist_ok=True)
    lines = [
        "ATTRIBUTION / NOTICE — locally generated, NOT redistributed by Kerf",
        "=" * 68,
        "",
        "This file is generated by `kerf-seed-parts` into a gitignored",
        "directory. Kerf does not bundle or redistribute any third-party",
        "parts data; the upstream repositories below are fetched locally on",
        "demand by the contributor running the pipeline.",
        "",
        "Sources fetched + converted in this run:",
        "",
    ]
    for s in sources:
        lines += [
            f"* {s.name}",
            f"    upstream : {s.git_url}",
            f"    ref      : {s.ref}",
            f"    license  : {s.license}",
            "",
        ]
    lines += [
        "KiCad official libraries are CC-BY-SA-4.0 with the KiCad Library",
        "Exception (the 'KiCad Library Exception'). That permits local",
        "fetch + use; it does NOT permit",
        "bundling the data into Kerf's MIT repository — which is exactly why",
        "this pipeline keeps all fetched/converted data out of git.",
        "",
    ]
    out = generated_dir / NOTICE_FILENAME
    out.write_text("\n".join(lines), encoding="utf-8")
    return out


# --------------------------------------------------------------------------
# DB write — mirrors the real system-owned-library pattern
# --------------------------------------------------------------------------

async def _ensure_system_user(conn) -> str:
    from kerf_core.config import get_settings  # lazy: kerf_core optional for tests
    from kerf_core.db.queries import users as users_q

    settings = get_settings()
    email = (
        (settings.system_user_email or "").strip().lower()
        or "local@kerf.local"
    )
    name = (settings.system_user_name or "").strip() or "Kerf System"

    user = await users_q.get_user_by_email(conn, email)
    if not user:
        user = await users_q.create_user(conn, email, name, None, None)
    return str(user["id"])


async def _ensure_workspace(conn, user_id: str) -> str:
    from kerf_core.db.queries import workspaces as ws_q

    row = await conn.fetchrow(
        """
        SELECT w.id FROM workspaces w
        JOIN workspace_members wm ON w.id = wm.workspace_id
        WHERE wm.user_id = $1 AND wm.role = 'owner'
        ORDER BY w.created_at ASC LIMIT 1
        """,
        user_id,
    )
    if row:
        return str(row["id"])
    slug = f"kerf-system-{str(user_id)[:8]}"
    ws = await ws_q.create_workspace(conn, slug, "Kerf System", user_id)
    await ws_q.add_workspace_member(conn, ws["id"], user_id, "owner")
    return str(ws["id"])


async def _ensure_project(conn, workspace_id: str) -> str:
    from kerf_core.db.queries import projects as proj_q

    row = await conn.fetchrow(
        "SELECT id FROM projects WHERE workspace_id = $1 AND name = $2",
        workspace_id, PARTS_LIBRARY_PROJECT,
    )
    if row:
        return str(row["id"])
    proj = await proj_q.create_project(
        conn, workspace_id, PARTS_LIBRARY_PROJECT,
        description="System-owned library of converted open-source CAD parts.",
        visibility="private",
    )
    return str(proj["id"])


async def _ensure_folder_path(conn, project_id: str, segments: list[str]) -> Optional[str]:
    """Create/lookup nested folders; return the leaf folder id (or None at root)."""
    parent_id = None
    for seg in segments:
        if parent_id is None:
            row = await conn.fetchrow(
                "SELECT id FROM files WHERE project_id=$1 AND parent_id IS NULL "
                "AND name=$2 AND kind='folder' AND deleted_at IS NULL",
                project_id, seg,
            )
        else:
            row = await conn.fetchrow(
                "SELECT id FROM files WHERE project_id=$1 AND parent_id=$2 "
                "AND name=$3 AND kind='folder' AND deleted_at IS NULL",
                project_id, parent_id, seg,
            )
        if row:
            parent_id = row["id"]
            continue
        parent_id = await conn.fetchval(
            "INSERT INTO files(project_id, parent_id, name, kind, content) "
            "VALUES ($1,$2,$3,'folder','') RETURNING id",
            project_id, parent_id, seg,
        )
    return parent_id


async def _upsert_part(conn, project_id: str, part: KerfPart) -> str:
    """Insert or content-hash-incrementally update one part file.

    Returns one of: 'created' | 'updated' | 'skipped'.
    """
    segments = [s for s in part.rel_path.split("/") if s]
    leaf = segments[-1]
    folder_id = await _ensure_folder_path(conn, project_id, segments[:-1])

    body = json.dumps(part.to_part_doc(), indent="  ")
    part.ensure_hash()

    if folder_id is None:
        existing = await conn.fetchrow(
            "SELECT id, content FROM files WHERE project_id=$1 AND parent_id IS NULL "
            "AND name=$2 AND deleted_at IS NULL",
            project_id, leaf,
        )
    else:
        existing = await conn.fetchrow(
            "SELECT id, content FROM files WHERE project_id=$1 AND parent_id=$2 "
            "AND name=$3 AND deleted_at IS NULL",
            project_id, folder_id, leaf,
        )

    if existing:
        try:
            prev = json.loads(existing["content"] or "{}")
        except Exception:
            prev = {}
        prev_hash = (prev.get("metadata") or {}).get("_content_hash")
        if prev_hash == part.content_hash:
            return "skipped"
        # changed -> update + record a revision (mirrors tool writes)
        await conn.execute(
            "UPDATE files SET content=$1, updated_at=now() WHERE id=$2",
            body, existing["id"],
        )
        return "updated"

    await conn.fetchval(
        "INSERT INTO files(project_id, parent_id, name, kind, content) "
        "VALUES ($1,$2,$3,'part',$4) RETURNING id",
        project_id, folder_id, leaf, body,
    )
    return "created"


async def seed_into_db(parts: list[KerfPart], *, log=print) -> dict:
    """Open a pool via kerf_core, ensure system project, upsert all parts."""
    from kerf_core.db.connection import close_pool, create_pool

    # embed the content hash so the next run can detect changes cheaply
    for p in parts:
        p.ensure_hash()
        p.metadata.setdefault("_content_hash", p.content_hash)

    pool = await create_pool()
    stats = {"created": 0, "updated": 0, "skipped": 0}
    try:
        async with pool.acquire() as conn:
            async with conn.transaction():
                user_id = await _ensure_system_user(conn)
                ws_id = await _ensure_workspace(conn, user_id)
                proj_id = await _ensure_project(conn, ws_id)
                log(f"  Parts Library project: {proj_id}")
                for part in parts:
                    outcome = await _upsert_part(conn, proj_id, part)
                    stats[outcome] += 1
    finally:
        await close_pool()
    return stats


# --------------------------------------------------------------------------
# CLI
# --------------------------------------------------------------------------

def build_arg_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="kerf-seed-parts",
        description=(
            "Fetch + convert pinned open-source CAD parts and seed them into "
            "the system-owned 'Parts Library' project. Idempotent + "
            "content-hash incremental. No third-party data is committed."
        ),
    )
    p.add_argument("--only", default="", help="comma-separated source subset")
    p.add_argument("--heavy", action="store_true", help="include heavy sources")
    p.add_argument("--cache-dir", default="", help="override .parts-cache dir")
    p.add_argument(
        "--ref", action="append", default=[], metavar="NAME=REF",
        help="override a source's pinned ref (repeatable)",
    )
    p.add_argument("--manifest", default="", help="alternate parts-sources.toml")
    p.add_argument(
        "--skip-fetch", action="store_true",
        help="assume caches already populated; only convert + seed",
    )
    p.add_argument(
        "--dry-run", action="store_true",
        help="fetch + convert + write NOTICE, but do NOT touch the database",
    )
    return p


def _parse_ref_overrides(values: list[str]) -> dict[str, str]:
    out: dict[str, str] = {}
    for v in values or []:
        if "=" not in v:
            raise SystemExit(f"--ref expects NAME=REF, got {v!r}")
        name, ref = v.split("=", 1)
        out[name.strip()] = ref.strip()
    return out


def main(argv: Optional[list[str]] = None) -> int:
    args = build_arg_parser().parse_args(argv)

    manifest = load_manifest(Path(args.manifest) if args.manifest else None)
    only = [x.strip() for x in args.only.split(",") if x.strip()] or None
    overrides = _parse_ref_overrides(args.ref)
    cache_dir = Path(args.cache_dir) if args.cache_dir else DEFAULT_CACHE_DIR

    selected = select_sources(
        manifest, only=only, include_heavy=args.heavy, ref_overrides=overrides
    )
    if not selected:
        print("nothing selected (heavy sources need --heavy)")
        return 0

    if not args.skip_fetch:
        print(f"fetching {len(selected)} source(s) into {cache_dir}")
        results = fetch_all(selected, cache_dir)
        if any(not r.ok for r in results):
            print("one or more fetches failed; aborting seed", file=sys.stderr)
            return 1

    print("converting...")
    parts = convert_sources(selected, cache_dir)
    print(f"{len(parts)} total part(s) ready")

    generated_dir = cache_dir / GENERATED_DIRNAME
    notice = write_notice(generated_dir, selected)
    print(f"attribution NOTICE -> {notice} (gitignored)")

    if args.dry_run:
        print("--dry-run: skipping database write")
        return 0
    if not parts:
        print("no parts to seed (scaffold-only sources selected)")
        return 0

    print("seeding into database...")
    try:
        stats = asyncio.run(seed_into_db(parts))
    except Exception as exc:  # noqa: BLE001
        print(f"seed failed: {exc}", file=sys.stderr)
        return 1
    print(
        f"done: {stats['created']} created, {stats['updated']} updated, "
        f"{stats['skipped']} unchanged"
    )
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
