"""
T-2: Jewelry — eternity ring auto-distribution (feature integration tests).

25 size/stone/style/mode/coverage permutations driven against a pre-computed
calibration table.  Each case asserts:

  1. stone_count == expected (calibration table match).
  2. perimeter consumed == arc_length ± 0.05 mm
     perimeter_consumed = Σ stone_mm + gap_mm × n_stones
  3. All stone seat positions lie on the inner bore circle.
  4. pitch × n == arc (within 1e-4°).
  5. Retention list has exactly stone_count entries.
  6. Idempotency: calling twice with same args returns identical stone_count.

Additional boundary / error / idempotency cases bring total above 25.
"""

from __future__ import annotations

import math
import pytest

from kerf_cad_core.jewelry.eternity_auto import eternity_auto_distribute

# ---------------------------------------------------------------------------
# Calibration table
# Each tuple:
#   (ring_size, stone_mm, setting_style, calibration_mode, coverage,
#    size_system, fixed_count_or_None, expected_n)
# expected_n was generated by running eternity_auto_distribute with these
# exact parameters and recording the result.
# ---------------------------------------------------------------------------

_CALIB: list[tuple] = [
    # idx  ring_size  stone_mm  style         mode          coverage       sys   fixed_count  expected_n
    (5,    1.5,  "prong",       "fixed_size",  "full",          "us", None, 28),  # 0
    (6,    1.75, "channel",     "fixed_size",  "full",          "us", None, 25),  # 1
    (7,    2.0,  "prong",       "fixed_size",  "full",          "us", None, 23),  # 2
    (7,    2.5,  "channel",     "fixed_size",  "full",          "us", None, 18),  # 3
    (8,    3.0,  "shared_bead", "fixed_size",  "full",          "us", None, 16),  # 4
    (9,    1.5,  "u_cut",       "fixed_size",  "full",          "us", None, 34),  # 5
    (10,   2.0,  "bezel",       "fixed_size",  "full",          "us", None, 26),  # 6
    (7,    2.0,  "prong",       "fixed_size",  "three_quarter", "us", None, 17),  # 7
    (7,    2.0,  "channel",     "fixed_size",  "half",          "us", None, 11),  # 8
    (7,    1.5,  "prong",       "fixed_count", "full",          "us",   20, 20),  # 9
    (7,    2.0,  "prong",       "fixed_count", "full",          "us",   16, 16),  # 10
    (6,    2.5,  "channel",     "fixed_count", "three_quarter", "us",   10, 10),  # 11
    (7,    3.0,  "prong",       "graduated",   "full",          "us", None, 15),  # 12
    (8,    2.5,  "channel",     "graduated",   "full",          "us", None, 19),  # 13
    (7,    2.0,  "prong",       "graduated",   "three_quarter", "us", None, 17),  # 14
    ("N",  2.0,  "prong",       "fixed_size",  "full",          "uk", None, 23),  # 15
    ("P",  2.5,  "channel",     "fixed_size",  "full",          "uk", None, 19),  # 16
    (54,   2.0,  "prong",       "fixed_size",  "full",          "eu", None, 23),  # 17
    (60,   2.5,  "shared_bead", "fixed_size",  "full",          "eu", None, 20),  # 18
    (12,   2.0,  "prong",       "fixed_size",  "full",          "jp", None, 20),  # 19
    (5,    1.5,  "prong",       "fixed_size",  "full",          "us", None, 28),  # 20 (idempotency duplicate of 0)
    (7,    4.0,  "bezel",       "fixed_size",  "full",          "us", None, 11),  # 21
    (4,    1.5,  "prong",       "fixed_size",  "half",          "us", None, 13),  # 22
    (11,   2.0,  "u_cut",       "fixed_size",  "three_quarter", "us", None, 21),  # 23
    (6,    1.75, "prong",       "fixed_count", "half",          "us",   12, 12),  # 24
]

# Maximum perimeter error tolerance (mm).
_PERIMETER_TOL_MM = 0.05


def _run(row: tuple):
    """Call eternity_auto_distribute for one calibration row."""
    rs, smm, style, mode, cov, sys, fc, _ = row
    kwargs: dict = dict(
        ring_size=rs,
        stone_cut="round_brilliant",
        stone_mm=smm,
        setting_style=style,
        calibration_mode=mode,
        coverage=cov,
        size_system=sys,
    )
    if fc is not None:
        kwargs["fixed_count"] = fc
    return eternity_auto_distribute(**kwargs)


# ---------------------------------------------------------------------------
# Parametrised calibration table: 25 cases
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("row", _CALIB, ids=[
    f"rs{r[0]}-{r[2]}-{r[3]}-{r[4]}-{r[5]}" for r in _CALIB
])
def test_calibration_stone_count(row):
    """Stone count matches the pre-computed calibration table."""
    *_, expected_n = row
    res = _run(row)
    assert res["stone_count"] == expected_n, (
        f"Expected {expected_n} stones; got {res['stone_count']} "
        f"(ring={row[0]}, stone_mm={row[1]}, style={row[2]}, "
        f"mode={row[3]}, cov={row[4]}, sys={row[5]})"
    )


@pytest.mark.parametrize("row", _CALIB, ids=[
    f"rs{r[0]}-{r[2]}-{r[3]}-{r[4]}-{r[5]}" for r in _CALIB
])
def test_perimeter_consumed_within_tolerance(row):
    """Perimeter consumed (seat widths + gaps) equals arc length ± 0.05 mm."""
    res = _run(row)
    n = res["stone_count"]
    gap = res["gap_mm"]
    arc_len = res["inner_circumference_mm"] * res["arc_deg"] / 360.0
    seat_widths_sum = sum(s["stone_mm"] for s in res["stones"])
    perimeter_consumed = seat_widths_sum + gap * n
    diff = abs(perimeter_consumed - arc_len)
    assert diff <= _PERIMETER_TOL_MM, (
        f"Perimeter diff {diff:.6f} mm > tol {_PERIMETER_TOL_MM} mm "
        f"(arc_len={arc_len:.4f}, consumed={perimeter_consumed:.4f}, "
        f"n={n}, gap={gap:.4f}, seats={seat_widths_sum:.4f})"
    )


# ---------------------------------------------------------------------------
# Per-permutation: stone positions lie on inner bore circle
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("row", _CALIB, ids=[
    f"rs{r[0]}-{r[2]}-{r[3]}-{r[4]}-{r[5]}" for r in _CALIB
])
def test_stone_positions_on_bore_circle(row):
    """All stone seat positions lie on the inner bore circle."""
    res = _run(row)
    inner_r = res["inner_radius_mm"]
    for s in res["stones"]:
        dist = math.sqrt(s["seat_x"] ** 2 + s["seat_y"] ** 2)
        assert abs(dist - inner_r) < 1e-3, (
            f"Stone {s['index']} radius {dist:.4f} != inner_r {inner_r:.4f}"
        )


# ---------------------------------------------------------------------------
# Per-permutation: pitch × n == arc_deg within tolerance
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("row", _CALIB, ids=[
    f"rs{r[0]}-{r[2]}-{r[3]}-{r[4]}-{r[5]}" for r in _CALIB
])
def test_pitch_times_n_equals_arc_deg(row):
    """pitch_deg × stone_count == arc_deg within 1e-4°."""
    res = _run(row)
    n = res["stone_count"]
    pitch = res["pitch_deg"]
    arc = res["arc_deg"]
    assert abs(n * pitch - arc) < 1e-4, (
        f"n={n} × pitch={pitch:.6f} = {n*pitch:.6f}; arc={arc}"
    )


# ---------------------------------------------------------------------------
# Per-permutation: retention list length == stone_count
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("row", _CALIB, ids=[
    f"rs{r[0]}-{r[2]}-{r[3]}-{r[4]}-{r[5]}" for r in _CALIB
])
def test_retention_length_matches_stone_count(row):
    """Retention list has exactly stone_count entries."""
    res = _run(row)
    assert len(res["retention"]) == res["stone_count"]


# ---------------------------------------------------------------------------
# Idempotency: identical args → identical stone_count (duplicate rows 0 & 20)
# ---------------------------------------------------------------------------

def test_idempotency_same_params_same_count():
    """Calling twice with identical params returns the same stone count."""
    row = _CALIB[0]
    r1 = _run(row)
    r2 = _run(row)
    assert r1["stone_count"] == r2["stone_count"]
    assert r1["pitch_mm"] == r2["pitch_mm"]
    assert r1["gap_mm"] == r2["gap_mm"]


def test_idempotency_duplicate_row_matches():
    """Calibration row 20 (duplicate of row 0) returns same stone count."""
    r0 = _run(_CALIB[0])
    r20 = _run(_CALIB[20])
    assert r0["stone_count"] == r20["stone_count"]
    assert r0["pitch_mm"] == r20["pitch_mm"]


# ---------------------------------------------------------------------------
# Boundary: smallest valid stone (1.5 mm) on smallest ring (US 4)
# ---------------------------------------------------------------------------

def test_boundary_smallest_ring_smallest_stone():
    res = eternity_auto_distribute(
        ring_size=4, stone_cut="round_brilliant", stone_mm=1.5,
        setting_style="prong", calibration_mode="fixed_size",
        coverage="full", size_system="us",
    )
    assert res["stone_count"] >= 1
    assert res["gap_mm"] >= 0.0


# ---------------------------------------------------------------------------
# Boundary: large stone (4.0 mm) on a large ring (US 12)
# ---------------------------------------------------------------------------

def test_boundary_large_stone_large_ring():
    res = eternity_auto_distribute(
        ring_size=12, stone_cut="round_brilliant", stone_mm=4.0,
        setting_style="bezel", calibration_mode="fixed_size",
        coverage="full", size_system="us",
    )
    # Large stones on large ring should still fit at least a few
    assert res["stone_count"] >= 4


# ---------------------------------------------------------------------------
# Boundary: half eternity stone count < three_quarter < full
# ---------------------------------------------------------------------------

def test_coverage_ordering():
    base = dict(ring_size=7, stone_cut="round_brilliant", stone_mm=2.0,
                setting_style="prong", calibration_mode="fixed_size")
    full = eternity_auto_distribute(**base, coverage="full")
    tq   = eternity_auto_distribute(**base, coverage="three_quarter")
    half = eternity_auto_distribute(**base, coverage="half")
    assert half["stone_count"] < tq["stone_count"] < full["stone_count"]


# ---------------------------------------------------------------------------
# Malformed input: stone_mm = 0 raises
# ---------------------------------------------------------------------------

def test_malformed_zero_stone_mm():
    with pytest.raises((ValueError, ZeroDivisionError)):
        eternity_auto_distribute(
            ring_size=7, stone_cut="round_brilliant", stone_mm=0,
            setting_style="prong",
        )


# ---------------------------------------------------------------------------
# Malformed input: negative stone_mm raises
# ---------------------------------------------------------------------------

def test_malformed_negative_stone_mm():
    with pytest.raises(ValueError):
        eternity_auto_distribute(
            ring_size=7, stone_cut="round_brilliant", stone_mm=-1.0,
            setting_style="prong",
        )


# ---------------------------------------------------------------------------
# Malformed input: unknown stone_cut raises
# ---------------------------------------------------------------------------

def test_malformed_unknown_cut():
    with pytest.raises(ValueError, match="Unknown stone_cut"):
        eternity_auto_distribute(
            ring_size=7, stone_cut="nonexistent_cut", stone_mm=2.0,
            setting_style="prong",
        )


# ---------------------------------------------------------------------------
# Malformed input: unknown setting_style raises
# ---------------------------------------------------------------------------

def test_malformed_unknown_style():
    with pytest.raises(ValueError, match="Unknown setting_style"):
        eternity_auto_distribute(
            ring_size=7, stone_cut="round_brilliant", stone_mm=2.0,
            setting_style="invisible_rail",
        )


# ---------------------------------------------------------------------------
# Malformed input: fixed_count mode without fixed_count param
# ---------------------------------------------------------------------------

def test_malformed_fixed_count_missing_param():
    with pytest.raises(ValueError):
        eternity_auto_distribute(
            ring_size=7, stone_cut="round_brilliant", stone_mm=2.0,
            calibration_mode="fixed_count",
        )


# ---------------------------------------------------------------------------
# Malformed input: fixed_count too tight (stones won't fit)
# ---------------------------------------------------------------------------

def test_malformed_fixed_count_too_tight():
    with pytest.raises(ValueError, match="gap="):
        eternity_auto_distribute(
            ring_size=7, stone_cut="round_brilliant", stone_mm=5.0,
            calibration_mode="fixed_count", fixed_count=100,
        )


# ---------------------------------------------------------------------------
# Malformed input: unknown coverage raises
# ---------------------------------------------------------------------------

def test_malformed_unknown_coverage():
    with pytest.raises(ValueError, match="Unknown coverage"):
        eternity_auto_distribute(
            ring_size=7, stone_cut="round_brilliant", stone_mm=2.0,
            setting_style="prong", coverage="seven_eighths",
        )


# ---------------------------------------------------------------------------
# Cross-size system: same physical ring in US vs UK vs EU vs JP
# gives consistent stone counts (within ±2 due to rounding in size tables)
# ---------------------------------------------------------------------------

def test_size_system_consistency():
    """US 7, UK N, EU 54 are all ~17.1 mm ID; stone counts should agree ±2."""
    base = dict(stone_cut="round_brilliant", stone_mm=2.0,
                setting_style="prong", calibration_mode="fixed_size",
                coverage="full")
    us = eternity_auto_distribute(ring_size=7,    size_system="us", **base)
    uk = eternity_auto_distribute(ring_size="N",  size_system="uk", **base)
    eu = eternity_auto_distribute(ring_size=54,   size_system="eu", **base)
    counts = [us["stone_count"], uk["stone_count"], eu["stone_count"]]
    assert max(counts) - min(counts) <= 2, (
        f"Cross-system stone counts diverge too much: us={counts[0]}, "
        f"uk={counts[1]}, eu={counts[2]}"
    )
