"""config_tcl.py — Emit the OpenLane ``openlane_config.tcl`` for Caravel.

The generated Tcl configuration follows the Efabless caravel_user_project
template for OpenLane 1.x (the version used for MPW shuttle submissions).

Key constraints baked in:
  - ``DIE_AREA``       1000 x 1000 µm  (1 mm² user area)
  - ``FP_CORE_UTIL``   45 %  (conservative for first-pass)
  - ``CLOCK_PORT``     wb_clk_i
  - ``CLOCK_PERIOD``   10 ns (100 MHz — adjustable via project_info)
  - ``PDK``            sky130A
  - ``STD_CELL_LIBRARY`` sky130_fd_sc_hd

All values can be overridden by passing ``extra_config`` (dict[str, str]) to
:func:`generate_config_tcl`.
"""

from __future__ import annotations

from typing import Any

# ---------------------------------------------------------------------------
# Default OpenLane configuration values
# ---------------------------------------------------------------------------

_DEFAULTS: dict[str, Any] = {
    "PDK":                        "sky130A",
    "STD_CELL_LIBRARY":           "sky130_fd_sc_hd",
    "DESIGN_NAME":                "user_project_wrapper",
    "VERILOG_FILES":              "dir::src/*.v",
    "CLOCK_PORT":                 "wb_clk_i",
    "CLOCK_PERIOD":               "10",        # ns → 100 MHz
    "DIE_AREA":                   "0 0 1000 1000",   # µm, 1 mm²
    "FP_SIZING":                  "absolute",
    "FP_CORE_UTIL":               "45",
    "PL_TARGET_DENSITY":          "0.45",
    "ROUTING_CORES":              "4",
    "GLB_RESIZER_TIMING_OPTIMIZATIONS": "1",
    "DIODE_INSERTION_STRATEGY":   "4",
    "FILL_INSERTION":             "1",
    "TAP_DECAP_INSERTION":        "1",
    "LEC_ENABLE":                 "0",
    "RUN_KLAYOUT":                "0",
}


# ---------------------------------------------------------------------------
# Emit function
# ---------------------------------------------------------------------------


def generate_config_tcl(
    top_module: str,
    *,
    clock_period_ns: float = 10.0,
    extra_config: dict[str, Any] | None = None,
) -> str:
    """Return the full text of ``openlane_config.tcl`` for *top_module*.

    Parameters
    ----------
    top_module:
        The user's top-level module name (used as ``DESIGN_NAME``).
    clock_period_ns:
        Target clock period in nanoseconds (default 10 ns = 100 MHz).
    extra_config:
        Additional or override Tcl ``set ::env(KEY) value`` entries.

    Returns
    -------
    str
        Complete ``openlane_config.tcl`` text.
    """
    config = dict(_DEFAULTS)
    config["DESIGN_NAME"] = top_module
    config["CLOCK_PERIOD"] = str(clock_period_ns)
    if extra_config:
        config.update(extra_config)

    lines: list[str] = [
        "# openlane_config.tcl — auto-generated by kerf-silicon Caravel packager",
        "# DO NOT EDIT — regenerate by re-running package_for_caravel()",
        "# Reference: github.com/efabless/caravel_user_project",
        "",
    ]

    for key, value in config.items():
        # Quote string values; leave numeric-looking values unquoted
        if isinstance(value, bool):
            tcl_val = "1" if value else "0"
        elif isinstance(value, (int, float)):
            tcl_val = str(value)
        else:
            tcl_val = f'"{value}"'
        lines.append(f"set ::env({key}) {tcl_val}")

    lines.append("")
    return "\n".join(lines)
