"""pin_order.py — Emit the Caravel ``pin_order.cfg`` file.

``pin_order.cfg`` tells OpenLane / Magic the physical placement order of the
pins on the ``user_project_wrapper`` boundary.  The Efabless Caravel template
defines a canonical order that must be respected for the chip-level integration
to succeed.

Canonical order (Caravel MPW-9 / sky130A):
  West side  : power rails + clock + reset + Wishbone + LA
  East side  : GPIO (io_in/out/oeb)
  North/South: unused (no user pins)

Reference: github.com/efabless/caravel_user_project/blob/main/openlane/
           user_project_wrapper/pin_order.cfg
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# Canonical pin sections
# ---------------------------------------------------------------------------

# Each section is (compass_direction, list_of_pin_names)
# Brackets are expanded inline (io_in[0..37] etc.)

_WISHBONE_PINS = [
    "wb_clk_i",
    "wb_rst_i",
    "wbs_stb_i",
    "wbs_cyc_i",
    "wbs_we_i",
    "wbs_sel_i[0]",
    "wbs_sel_i[1]",
    "wbs_sel_i[2]",
    "wbs_sel_i[3]",
]

_WBS_DATA_PINS = [f"wbs_dat_i[{i}]" for i in range(32)]
_WBS_ADDR_PINS = [f"wbs_adr_i[{i}]" for i in range(32)]
_WBS_DOUT_PINS = [f"wbs_dat_o[{i}]" for i in range(32)]

_LA_IN_PINS   = [f"la_data_in[{i}]"  for i in range(128)]
_LA_OUT_PINS  = [f"la_data_out[{i}]" for i in range(128)]
_LA_OENB_PINS = [f"la_oenb[{i}]"     for i in range(128)]

_MISC_PINS = [
    "wbs_ack_o",
    "user_clock2",
    "user_irq[0]",
    "user_irq[1]",
    "user_irq[2]",
]

_GPIO_IN_PINS  = [f"io_in[{i}]"  for i in range(38)]
_GPIO_OUT_PINS = [f"io_out[{i}]" for i in range(38)]
_GPIO_OEB_PINS = [f"io_oeb[{i}]" for i in range(38)]


# ---------------------------------------------------------------------------
# Sections: (direction, pins)
# ---------------------------------------------------------------------------

_SECTIONS: list[tuple[str, list[str]]] = [
    ("#S",   _WISHBONE_PINS
             + _WBS_DATA_PINS
             + _WBS_ADDR_PINS
             + _WBS_DOUT_PINS
             + _LA_IN_PINS
             + _LA_OUT_PINS
             + _LA_OENB_PINS
             + _MISC_PINS),
    ("#E",   _GPIO_IN_PINS + _GPIO_OUT_PINS + _GPIO_OEB_PINS),
]


# ---------------------------------------------------------------------------
# Emit function
# ---------------------------------------------------------------------------


def generate_pin_order(top_module: str = "user_project_wrapper") -> str:
    """Return the full text of ``pin_order.cfg`` for the Caravel wrapper.

    Parameters
    ----------
    top_module:
        The wrapper module name (always ``user_project_wrapper`` for Caravel).
    """
    lines: list[str] = [
        f"# pin_order.cfg — auto-generated by kerf-silicon Caravel packager",
        f"# Module: {top_module}",
        "# Reference: github.com/efabless/caravel_user_project",
        "",
    ]

    for direction, pins in _SECTIONS:
        lines.append(direction)
        for pin in pins:
            lines.append(pin)
        lines.append("")

    return "\n".join(lines)
