"""wrapper.py — Generate the Caravel ``user_project_wrapper.v`` file.

The Caravel harness (github.com/efabless/caravel_user_project) requires that
every user design be wrapped inside a module named exactly
``user_project_wrapper``.  This module exposes the full Caravel interface:

  - 38-bit GPIO bus    (io_in, io_out, io_oeb)
  - Wishbone master    (wb_clk_i, wb_rst_i, wbs_stb_i, wbs_cyc_i, wbs_we_i,
                        wbs_sel_i[3:0], wbs_dat_i[31:0], wbs_dat_o[31:0],
                        wbs_adr_i[31:0], wbs_ack_o)
  - Logic analyser     (la_data_in[127:0], la_data_out[127:0], la_oenb[127:0])
  - Miscellaneous      (user_clock2, user_irq[2:0])

The generated wrapper instantiates the user's top-level module and connects
all signals by name.  Power rails (vccd1, vssd1, vccd2, vssd2, vdda1, vssa1,
vdda2, vssa2) are declared as ``supply`` nets matching the Caravel template.
"""

from __future__ import annotations

import textwrap

# ---------------------------------------------------------------------------
# Wrapper Verilog template
# ---------------------------------------------------------------------------

_WRAPPER_TEMPLATE = textwrap.dedent(
    """\
    // user_project_wrapper.v — auto-generated by kerf-silicon Caravel packager
    // DO NOT EDIT — regenerate by re-running package_for_caravel()
    //
    // Wraps user module: {top_module}
    `default_nettype none

    module user_project_wrapper #(
        parameter BITS = 32
    ) (
    `ifdef USE_POWER_PINS
        inout vdda1,   // User area 1 3.3V supply
        inout vdda2,   // User area 2 3.3V supply
        inout vssa1,   // User area 1 analog ground
        inout vssa2,   // User area 2 analog ground
        inout vccd1,   // User area 1 1.8V supply
        inout vccd2,   // User area 2 1.8V supply
        inout vssd1,   // User area 1 digital ground
        inout vssd2,   // User area 2 digital ground
    `endif

        // Wishbone slave interface
        input  wire        wb_clk_i,
        input  wire        wb_rst_i,
        input  wire        wbs_stb_i,
        input  wire        wbs_cyc_i,
        input  wire        wbs_we_i,
        input  wire [3:0]  wbs_sel_i,
        input  wire [31:0] wbs_dat_i,
        input  wire [31:0] wbs_adr_i,
        output wire        wbs_ack_o,
        output wire [31:0] wbs_dat_o,

        // Logic analyser signals
        input  wire [127:0] la_data_in,
        output wire [127:0] la_data_out,
        input  wire [127:0] la_oenb,

        // GPIO signals
        input  wire [37:0] io_in,
        output wire [37:0] io_out,
        output wire [37:0] io_oeb,

        // Independent clock
        input  wire        user_clock2,

        // User interrupts
        output wire [2:0]  user_irq
    );

        {top_module} mprj (
    `ifdef USE_POWER_PINS
            .vccd1     (vccd1),
            .vssd1     (vssd1),
    `endif
            .wb_clk_i  (wb_clk_i),
            .wb_rst_i  (wb_rst_i),
            .wbs_stb_i (wbs_stb_i),
            .wbs_cyc_i (wbs_cyc_i),
            .wbs_we_i  (wbs_we_i),
            .wbs_sel_i (wbs_sel_i),
            .wbs_dat_i (wbs_dat_i),
            .wbs_adr_i (wbs_adr_i),
            .wbs_ack_o (wbs_ack_o),
            .wbs_dat_o (wbs_dat_o),
            .la_data_in  (la_data_in),
            .la_data_out (la_data_out),
            .la_oenb     (la_oenb),
            .io_in  (io_in),
            .io_out (io_out),
            .io_oeb (io_oeb),
            .user_clock2 (user_clock2),
            .user_irq    (user_irq)
        );

    endmodule
    `default_nettype wire
    """
)


def generate_wrapper(top_module: str) -> str:
    """Return the full text of ``user_project_wrapper.v`` for *top_module*.

    Parameters
    ----------
    top_module:
        The name of the user's top-level Verilog module.
    """
    return _WRAPPER_TEMPLATE.format(top_module=top_module)
