// TextilesWeaveKnitPanel — display panel for textiles_generate tool results.
//
// Renders weave cell matrix as an SVG grid, and knit structures as
// a stitch notation grid.  Also shows float/density statistics.
//
// Props
// ─────
//   result  {Object}  — parsed output from textiles_generate tool call
//     For weave: { name, float_stats, analytic_warp_mean_float,
//                  analytic_weft_mean_float, svg }
//     For knit:  { name, density_stats, svg }
//   className  {string}  — extra CSS classes on root element
//
// Pure display — no live API calls. All data comes from result prop.
//
// Exported pure helpers for vitest:
//   parseTextilesResult(raw)     → { kind, type, name, svg, stats, error? }
//   fmtFloat(n)                  → formatted float length string
//   weaveStatLabel(key)          → human-readable stat label

import { useMemo } from 'react'
import { Grid3x3, Layers } from 'lucide-react'

// ---------------------------------------------------------------------------
// Pure helpers (exported for tests)
// ---------------------------------------------------------------------------

/**
 * Parse raw textiles_generate result (string or object) into a display-ready
 * object. Returns { kind: 'ok'|'empty'|'invalid', type, name, svg, stats, error? }
 */
export function parseTextilesResult(raw) {
  if (raw == null) return { kind: 'empty' }
  const obj = typeof raw === 'string' ? (() => { try { return JSON.parse(raw) } catch { return null } })() : raw
  if (!obj || typeof obj !== 'object') return { kind: 'invalid', error: 'Expected JSON object' }
  if (obj.error) return { kind: 'invalid', error: obj.error }

  // Detect type from shape
  const isWeave = 'float_stats' in obj || 'analytic_warp_mean_float' in obj
  const isKnit  = 'density_stats' in obj

  const type  = isWeave ? 'weave' : isKnit ? 'knit' : 'unknown'
  const name  = obj.name || '(unnamed)'
  const svg   = obj.svg || null

  let stats = {}
  if (isWeave) {
    stats = {
      warp_mean_float: obj.analytic_warp_mean_float ?? obj.float_stats?.warp_mean_float,
      weft_mean_float: obj.analytic_weft_mean_float ?? obj.float_stats?.weft_mean_float,
      max_float:       obj.float_stats?.max_float,
    }
  } else if (isKnit) {
    stats = {
      wales_per_cm:   obj.density_stats?.wales_per_cm,
      courses_per_cm: obj.density_stats?.courses_per_cm,
      density_within_1pct: obj.density_stats?.density_within_1pct,
    }
  }

  return { kind: 'ok', type, name, svg, stats }
}

/**
 * Format a float-length number. Returns "—" for null/undefined/NaN.
 */
export function fmtFloat(n) {
  if (n == null || !Number.isFinite(n)) return '—'
  return n.toFixed(2)
}

/**
 * Return a human-readable label for a weave/knit stat key.
 */
export function weaveStatLabel(key) {
  const labels = {
    warp_mean_float:       'Warp mean float',
    weft_mean_float:       'Weft mean float',
    max_float:             'Max float length',
    wales_per_cm:          'Wales / cm',
    courses_per_cm:        'Courses / cm',
    density_within_1pct:   'Density ±1%',
  }
  return labels[key] ?? key
}

// ---------------------------------------------------------------------------
// Sub-components
// ---------------------------------------------------------------------------

function StatRow({ label, value }) {
  return (
    <div className="flex items-center justify-between py-1">
      <span className="text-xs text-ink-400">{label}</span>
      <span className="font-mono text-xs text-ink-200">
        {value === true ? 'yes' : value === false ? 'no' : String(value ?? '—')}
      </span>
    </div>
  )
}

function WeaveStats({ stats }) {
  if (!stats || Object.keys(stats).length === 0) return null
  return (
    <div
      className="mt-3 rounded-lg border border-ink-800 bg-ink-950/50 px-3 py-2 divide-y divide-ink-800/60"
      data-testid="weave-stats"
    >
      {Object.entries(stats).map(([k, v]) => (
        <StatRow
          key={k}
          label={weaveStatLabel(k)}
          value={k === 'warp_mean_float' || k === 'weft_mean_float' || k === 'max_float'
            ? fmtFloat(v)
            : v
          }
        />
      ))}
    </div>
  )
}

function SVGPreview({ svg }) {
  if (!svg) return null
  return (
    <div
      className="mt-3 overflow-auto rounded-lg border border-ink-800 bg-ink-950/50 p-2"
      data-testid="textiles-svg-preview"
      // SVG content is generated by kerf-textiles (trusted backend); using
      // dangerouslySetInnerHTML is intentional here — same as other SVG panels.
      // eslint-disable-next-line react/no-danger
      dangerouslySetInnerHTML={{ __html: svg }}
    />
  )
}

// ---------------------------------------------------------------------------
// Main component
// ---------------------------------------------------------------------------

/**
 * TextilesWeaveKnitPanel — renders weave or knit structure results.
 *
 * @param {Object} props
 * @param {Object|string|null} props.result  — textiles_generate output
 * @param {string} [props.className]
 */
export default function TextilesWeaveKnitPanel({ result = null, className = '' }) {
  const parsed = useMemo(() => parseTextilesResult(result), [result])

  if (parsed.kind === 'empty') {
    return (
      <div
        className={`flex flex-col items-center justify-center gap-2 py-10 text-ink-500 ${className}`}
        data-testid="textiles-panel-empty"
      >
        <Grid3x3 size={28} className="opacity-40" />
        <p className="text-sm">No weave or knit result yet.</p>
        <p className="text-xs opacity-60">
          Ask Kerf to generate a weave or knit structure.
        </p>
      </div>
    )
  }

  if (parsed.kind === 'invalid') {
    return (
      <div
        className={`rounded-lg border border-red-500/30 bg-red-500/10 px-3 py-2 text-sm text-red-400 ${className}`}
        data-testid="textiles-panel-error"
      >
        Error: {parsed.error}
      </div>
    )
  }

  const typeLabel = parsed.type === 'weave' ? 'Weave' : parsed.type === 'knit' ? 'Knit' : 'Textile'

  return (
    <div className={`flex flex-col gap-0 ${className}`} data-testid="textiles-weave-knit-panel">
      {/* Header */}
      <div className="flex items-center gap-2 mb-1">
        <span className="grid place-items-center w-5 h-5 rounded bg-cyan-edge/10 border border-cyan-edge/20 text-cyan-edge">
          <Layers size={11} />
        </span>
        <span className="font-mono text-[11px] uppercase tracking-wider text-ink-400">
          {typeLabel} structure
        </span>
        <span
          className="ml-auto rounded-md border border-ink-700 bg-ink-900/60 px-2 py-0.5 font-mono text-[11px] text-ink-300"
          data-testid="textiles-structure-name"
        >
          {parsed.name}
        </span>
      </div>

      {/* SVG preview */}
      <SVGPreview svg={parsed.svg} />

      {/* Stats */}
      <WeaveStats stats={parsed.stats} />
    </div>
  )
}
