"""
kerf_plm.change_impact
======================

Change-impact analyzer following the PROSTEP-iViP SIG Smart Systems
Engineering Change Impact Methodology and ISO 10303-242 managed
model-based engineering concepts.

Graph model
-----------
Nodes represent any PLM entity:
  - part / assembly
  - requirement
  - test
  - document

Edges are typed directed relationships:
  - "depends_on"   — A depends_on B  (A breaks if B changes)
  - "impacted_by"  — A impacted_by B (B changing causes rework on A)
    (Note: impacted_by is the transpose of depends_on.  Both are stored
     so callers can traverse in either direction.)
  - "mates_with"   — A mates_with B  (geometry/interface coupling; symmetric)

Impact-level categorisation (per PROSTEP-iViP §4.3)
----------------------------------------------------
  high   — direct neighbours (BFS depth 1)
  medium — 2-hop neighbours  (BFS depth 2 or 3, see below)
  low    — ≥ 3-hop neighbours (BFS depth ≥ 3, see below, capped at 4)

  BFS depth mapping:
    1  → high
    2  → medium
    3  → medium   (still close coupling per §4.3)
    ≥4 → low

Rework cost model (simple tier model, §5.1)
-------------------------------------------
  high   → 8 engineer-hours per node
  medium → 3 engineer-hours per node
  low    → 1 engineer-hour  per node

Public API
----------
  build_impact_graph(plm_data)              -> ImpactGraph
  analyze_change_impact(part_id, graph)     -> ImpactReport
  propose_co_changes(report)                -> list[Suggestion]
  estimate_change_cost(report, hourly_rate) -> dict
"""

from __future__ import annotations

from collections import deque
from dataclasses import dataclass, field
from typing import Literal


# ---------------------------------------------------------------------------
# Domain types
# ---------------------------------------------------------------------------

NodeKind = Literal["part", "assembly", "requirement", "test", "document"]
EdgeKind = Literal["depends_on", "impacted_by", "mates_with"]
ImpactLevel = Literal["high", "medium", "low"]

# PROSTEP-iViP §4.3 rework cost in engineer-hours per impacted node
_HOURS_PER_LEVEL: dict[ImpactLevel, float] = {
    "high": 8.0,
    "medium": 3.0,
    "low": 1.0,
}


@dataclass
class ImpactNode:
    """A node in the impact graph (part, assembly, requirement, test, or doc)."""
    id: str
    kind: NodeKind = "part"
    label: str = ""
    # Optional metadata for co-change heuristics
    attributes: dict = field(default_factory=dict)


@dataclass
class ImpactEdge:
    source: str  # node id
    target: str  # node id
    kind: EdgeKind
    # Optional: coupling strength 0–1 (not enforced; informational)
    strength: float = 1.0


@dataclass
class ImpactedNode:
    """A single node that is impacted by a change, with its assessed level."""
    node_id: str
    kind: NodeKind
    label: str
    hop_distance: int
    impact_level: ImpactLevel
    rework_hours: float


@dataclass
class ImpactReport:
    """Result of analyze_change_impact()."""
    changed_part_id: str
    # Nodes that are impacted (excludes the changed node itself)
    impacted_nodes: list[ImpactedNode]
    # Quick lookup: node_id -> ImpactedNode
    _by_id: dict[str, ImpactedNode] = field(default_factory=dict, repr=False)

    def __post_init__(self) -> None:
        self._by_id = {n.node_id: n for n in self.impacted_nodes}

    def total_rework_hours(self) -> float:
        return sum(n.rework_hours for n in self.impacted_nodes)

    def nodes_at_level(self, level: ImpactLevel) -> list[ImpactedNode]:
        return [n for n in self.impacted_nodes if n.impact_level == level]


@dataclass
class Suggestion:
    """A co-change suggestion generated by propose_co_changes()."""
    node_id: str
    label: str
    reason: str
    # How strongly recommended (informational, 0–1)
    confidence: float = 1.0


class ImpactGraph:
    """
    Directed graph of PLM entities and their impact relationships.

    Internally stores both an adjacency list for "impacted_by" traversal
    (forward BFS from a changed part) and a node registry.

    Edge semantics
    --------------
    "depends_on" A→B  : A breaks if B changes
      → stored also as "impacted_by" B→A so BFS from B reaches A.
    "mates_with" A↔B  : stored in both directions as mates edges.
    "impacted_by" A→B : explicit impact edge — A is impacted if B changes
      → stored also as "impacted_by" B→A (so BFS from B reaches A).
    """

    def __init__(self) -> None:
        self._nodes: dict[str, ImpactNode] = {}
        # impact adjacency: node_id -> set of node_ids it propagates impact TO
        self._impact_adj: dict[str, set[str]] = {}
        # mates adjacency (symmetric): node_id -> set of node_ids it mates with
        self._mates_adj: dict[str, set[str]] = {}
        self._edges: list[ImpactEdge] = []

    # ------------------------------------------------------------------
    # Builder helpers
    # ------------------------------------------------------------------

    def add_node(self, node: ImpactNode) -> None:
        self._nodes[node.id] = node
        if node.id not in self._impact_adj:
            self._impact_adj[node.id] = set()
        if node.id not in self._mates_adj:
            self._mates_adj[node.id] = set()

    def add_edge(self, edge: ImpactEdge) -> None:
        # Ensure both endpoints exist (create placeholder nodes if absent)
        for nid in (edge.source, edge.target):
            if nid not in self._nodes:
                self.add_node(ImpactNode(id=nid, kind="part", label=nid))

        self._edges.append(edge)

        if edge.kind == "depends_on":
            # A depends_on B → B's change propagates impact to A
            self._impact_adj.setdefault(edge.source, set())
            self._impact_adj.setdefault(edge.target, set())
            self._impact_adj[edge.target].add(edge.source)

        elif edge.kind == "impacted_by":
            # A impacted_by B → B's change propagates impact to A
            # (same direction as depends_on)
            self._impact_adj.setdefault(edge.source, set())
            self._impact_adj.setdefault(edge.target, set())
            self._impact_adj[edge.target].add(edge.source)

        elif edge.kind == "mates_with":
            # Symmetric — changes to either side may require changes to the other
            self._mates_adj.setdefault(edge.source, set())
            self._mates_adj.setdefault(edge.target, set())
            self._mates_adj[edge.source].add(edge.target)
            self._mates_adj[edge.target].add(edge.source)
            # Also add to impact adjacency for BFS propagation
            self._impact_adj.setdefault(edge.source, set())
            self._impact_adj.setdefault(edge.target, set())
            self._impact_adj[edge.source].add(edge.target)
            self._impact_adj[edge.target].add(edge.source)

    def node(self, node_id: str) -> ImpactNode | None:
        return self._nodes.get(node_id)

    def downstream_ids(self, node_id: str) -> set[str]:
        """Return direct impact neighbours of node_id."""
        return set(self._impact_adj.get(node_id, set()))

    def mates_of(self, node_id: str) -> set[str]:
        return set(self._mates_adj.get(node_id, set()))

    def all_node_ids(self) -> list[str]:
        return list(self._nodes.keys())


# ---------------------------------------------------------------------------
# Build graph from PLM data dict
# ---------------------------------------------------------------------------

def build_impact_graph(plm_data: dict) -> ImpactGraph:
    """
    Build an ImpactGraph from a PLM data dictionary.

    Expected schema (all keys optional — gracefully degraded)::

        {
          "parts": [
            {
              "id": "P-001",
              "label": "Main Housing",
              "kind": "part",      # part | assembly | requirement | test | document
              "attributes": {...}  # free-form metadata (e.g. diameter_mm)
            },
            ...
          ],
          "assemblies": [
            {
              "id": "A-001",
              "children": ["P-001", "P-002", "P-003"]
            },
            ...
          ],
          "requirements": [
            {"id": "R-001", "label": "Max load 10 kN", "verified_by": ["T-001"]}
          ],
          "tests": [
            {"id": "T-001", "label": "Load test", "tests_part": "P-001"}
          ],
          "documents": [
            {"id": "D-001", "label": "Design Spec", "references": ["P-001"]}
          ],
          "edges": [
            {
              "source": "P-001",
              "target": "P-002",
              "kind": "depends_on",   # depends_on | impacted_by | mates_with
              "strength": 0.9
            },
            ...
          ]
        }

    Assembly children edges are synthesised as "depends_on" (child is a
    constituent of the parent → if child changes the assembly is impacted).

    Requirement->test edges are synthesised as "depends_on" (the test
    depends on the requirement it verifies).

    Document->part references are synthesised as "depends_on" (the document
    depends on the part it documents).
    """
    g = ImpactGraph()

    # ── Register all nodes ────────────────────────────────────────────────
    for part in plm_data.get("parts", []):
        g.add_node(ImpactNode(
            id=part["id"],
            kind=part.get("kind", "part"),
            label=part.get("label", part["id"]),
            attributes=part.get("attributes", {}),
        ))

    for asm in plm_data.get("assemblies", []):
        nid = asm["id"]
        if nid not in g._nodes:
            g.add_node(ImpactNode(id=nid, kind="assembly", label=asm.get("label", nid)))

    for req in plm_data.get("requirements", []):
        nid = req["id"]
        if nid not in g._nodes:
            g.add_node(ImpactNode(id=nid, kind="requirement", label=req.get("label", nid)))

    for tst in plm_data.get("tests", []):
        nid = tst["id"]
        if nid not in g._nodes:
            g.add_node(ImpactNode(id=nid, kind="test", label=tst.get("label", nid)))

    for doc in plm_data.get("documents", []):
        nid = doc["id"]
        if nid not in g._nodes:
            g.add_node(ImpactNode(id=nid, kind="document", label=doc.get("label", nid)))

    # ── Synthesise edges from structural data ─────────────────────────────

    # Assembly children: changing a child propagates impact up to assembly
    # (assembly "depends_on" each child)
    for asm in plm_data.get("assemblies", []):
        for child_id in asm.get("children", []):
            if child_id not in g._nodes:
                g.add_node(ImpactNode(id=child_id, kind="part", label=child_id))
            # Assembly depends on the child — child change impacts assembly
            g.add_edge(ImpactEdge(
                source=asm["id"],
                target=child_id,
                kind="depends_on",
                strength=1.0,
            ))

    # Requirements: requirement depends on part it governs;
    # test depends on requirement it verifies
    for req in plm_data.get("requirements", []):
        req_id = req["id"]
        for test_id in req.get("verified_by", []):
            if test_id not in g._nodes:
                g.add_node(ImpactNode(id=test_id, kind="test", label=test_id))
            # Test depends on requirement — requirement change impacts test
            g.add_edge(ImpactEdge(
                source=test_id,
                target=req_id,
                kind="depends_on",
                strength=0.9,
            ))
        for part_id in req.get("applies_to", []):
            if part_id not in g._nodes:
                g.add_node(ImpactNode(id=part_id, kind="part", label=part_id))
            # Requirement depends on the part — part change impacts requirement
            g.add_edge(ImpactEdge(
                source=req_id,
                target=part_id,
                kind="depends_on",
                strength=0.8,
            ))

    # Tests: test depends on the part it tests
    for tst in plm_data.get("tests", []):
        part_id = tst.get("tests_part")
        if part_id:
            if part_id not in g._nodes:
                g.add_node(ImpactNode(id=part_id, kind="part", label=part_id))
            g.add_edge(ImpactEdge(
                source=tst["id"],
                target=part_id,
                kind="depends_on",
                strength=0.9,
            ))

    # Documents: document depends on referenced parts
    for doc in plm_data.get("documents", []):
        for ref_id in doc.get("references", []):
            if ref_id not in g._nodes:
                g.add_node(ImpactNode(id=ref_id, kind="part", label=ref_id))
            g.add_edge(ImpactEdge(
                source=doc["id"],
                target=ref_id,
                kind="depends_on",
                strength=0.7,
            ))

    # ── Explicit edges ────────────────────────────────────────────────────
    for raw in plm_data.get("edges", []):
        kind = raw.get("kind", "depends_on")
        if kind not in ("depends_on", "impacted_by", "mates_with"):
            kind = "depends_on"
        g.add_edge(ImpactEdge(
            source=raw["source"],
            target=raw["target"],
            kind=kind,
            strength=float(raw.get("strength", 1.0)),
        ))

    return g


# ---------------------------------------------------------------------------
# Analyze change impact
# ---------------------------------------------------------------------------

def _hop_to_level(hop: int) -> ImpactLevel:
    """
    Map BFS hop distance to PROSTEP-iViP impact level.

    Depth 1        → high    (direct dependency)
    Depth 2 or 3   → medium  (indirect, still tightly coupled)
    Depth ≥ 4      → low     (remote coupling)
    """
    if hop <= 1:
        return "high"
    if hop <= 3:
        return "medium"
    return "low"


def analyze_change_impact(
    changed_part_id: str,
    impact_graph: ImpactGraph,
    max_hops: int = 10,
) -> ImpactReport:
    """
    BFS propagation from ``changed_part_id`` through impact edges.

    Returns an ImpactReport with each reachable node categorised by
    impact level (high / medium / low) per the PROSTEP-iViP methodology.

    Parameters
    ----------
    changed_part_id:
        The PLM entity that is being changed.
    impact_graph:
        Graph built by build_impact_graph().
    max_hops:
        BFS depth cap (default 10).  Prevents runaway propagation in
        cyclic graphs (which should not occur in practice but may exist
        in test data).

    Returns
    -------
    ImpactReport
    """
    if changed_part_id not in impact_graph._nodes:
        return ImpactReport(
            changed_part_id=changed_part_id,
            impacted_nodes=[],
        )

    visited: dict[str, int] = {}  # node_id -> hop distance at first visit
    queue: deque[tuple[str, int]] = deque()

    for neighbour in impact_graph.downstream_ids(changed_part_id):
        if neighbour != changed_part_id and neighbour not in visited:
            visited[neighbour] = 1
            queue.append((neighbour, 1))

    while queue:
        current_id, depth = queue.popleft()
        if depth >= max_hops:
            continue
        for neighbour in impact_graph.downstream_ids(current_id):
            if neighbour != changed_part_id and neighbour not in visited:
                visited[neighbour] = depth + 1
                queue.append((neighbour, depth + 1))

    impacted: list[ImpactedNode] = []
    for node_id, hop in visited.items():
        node = impact_graph.node(node_id)
        if node is None:
            node = ImpactNode(id=node_id, kind="part", label=node_id)
        level = _hop_to_level(hop)
        rework_hours = _HOURS_PER_LEVEL[level]
        impacted.append(ImpactedNode(
            node_id=node_id,
            kind=node.kind,
            label=node.label,
            hop_distance=hop,
            impact_level=level,
            rework_hours=rework_hours,
        ))

    # Sort deterministically: by hop ascending, then node_id
    impacted.sort(key=lambda n: (n.hop_distance, n.node_id))

    return ImpactReport(
        changed_part_id=changed_part_id,
        impacted_nodes=impacted,
    )


# ---------------------------------------------------------------------------
# Co-change suggestions
# ---------------------------------------------------------------------------

def propose_co_changes(
    impact_report: ImpactReport,
    impact_graph: ImpactGraph | None = None,
) -> list[Suggestion]:
    """
    Suggest parts/entities that should be co-changed with the primary change.

    Heuristics applied (per PROSTEP-iViP §6.2 "Interface Coupling"):
    1. **Mating partners** — any node connected to the changed part via a
       ``mates_with`` edge is flagged as a mandatory co-change if the graph
       is provided.
    2. **High-impact assembly parent** — an assembly node at hop=1 is likely
       a container that needs revision (ECO workflow trigger).
    3. **Linked test plans** — test nodes at any hop are flagged as needing
       re-execution rather than geometric rework.
    4. **Linked documents** — document nodes at hop ≤ 2 require revision.
    """
    suggestions: list[Suggestion] = []
    seen: set[str] = set()

    changed_id = impact_report.changed_part_id

    def _add(node_id: str, label: str, reason: str, confidence: float = 1.0) -> None:
        if node_id not in seen and node_id != changed_id:
            seen.add(node_id)
            suggestions.append(Suggestion(
                node_id=node_id,
                label=label,
                reason=reason,
                confidence=confidence,
            ))

    # Heuristic 1: mating partners from the graph
    if impact_graph is not None:
        for mate_id in impact_graph.mates_of(changed_id):
            mate_node = impact_graph.node(mate_id)
            label = mate_node.label if mate_node else mate_id
            _add(
                mate_id,
                label,
                reason=(
                    f"Mates with '{changed_id}': interface coupling requires "
                    "matching geometry change (e.g. mating hole ↔ shaft diameter)."
                ),
                confidence=0.95,
            )

    # Heuristics 2–4: scan impacted nodes
    for inode in impact_report.impacted_nodes:
        if inode.kind == "assembly" and inode.impact_level == "high":
            _add(
                inode.node_id,
                inode.label,
                reason=(
                    f"Assembly '{inode.label}' directly contains the changed part. "
                    "Assembly drawing / BOM revision required (ECO trigger)."
                ),
                confidence=0.90,
            )
        elif inode.kind == "test":
            _add(
                inode.node_id,
                inode.label,
                reason=(
                    f"Test plan '{inode.label}' validates an entity affected by this "
                    "change — re-run or update test procedure."
                ),
                confidence=0.80,
            )
        elif inode.kind == "document" and inode.hop_distance <= 2:
            _add(
                inode.node_id,
                inode.label,
                reason=(
                    f"Document '{inode.label}' references a directly impacted entity. "
                    "Update revision and re-release."
                ),
                confidence=0.75,
            )

    return suggestions


# ---------------------------------------------------------------------------
# Cost estimation
# ---------------------------------------------------------------------------

def estimate_change_cost(
    impact_report: ImpactReport,
    hourly_rate: float = 100.0,
) -> dict:
    """
    Estimate total and per-tier rework cost from an ImpactReport.

    Parameters
    ----------
    impact_report:
        Output of analyze_change_impact().
    hourly_rate:
        Engineer hourly rate in USD (default $100/hr).

    Returns
    -------
    dict with keys:
        total_hours   : float — sum of all rework hours
        total_cost_usd: float — total_hours * hourly_rate
        by_level      : dict[str, dict] — breakdown per impact level
            hours, count, cost_usd
        hourly_rate   : float — echo of the input rate
    """
    by_level: dict[str, dict] = {
        "high":   {"hours": 0.0, "count": 0},
        "medium": {"hours": 0.0, "count": 0},
        "low":    {"hours": 0.0, "count": 0},
    }

    for inode in impact_report.impacted_nodes:
        lvl = inode.impact_level
        by_level[lvl]["hours"] += inode.rework_hours
        by_level[lvl]["count"] += 1

    total_hours = sum(v["hours"] for v in by_level.values())
    total_cost = total_hours * hourly_rate

    for lvl, v in by_level.items():
        v["cost_usd"] = v["hours"] * hourly_rate

    return {
        "total_hours": total_hours,
        "total_cost_usd": total_cost,
        "by_level": by_level,
        "hourly_rate": hourly_rate,
    }
