"kerf-marine: naval architecture plugin for Kerf — hydrostatics, stability, hull-section integration, seakeeping/RAOs, ISO 12215-5 scantlings."

__version__ = "0.1.0"

from kerf_marine.seakeeping import (
    HullSection,
    GlobalMatrices,
    RAOResult,
    MotionStatistics,
    compute_global_matrices,
    compute_rao,
    compute_response_statistics,
    encounter_frequency,
    jonswap_spectrum,
    pierson_moskowitz_spectrum,
    wigley_hull_sections,
)

from kerf_marine.scantlings import (
    DesignCategory,
    MaterialProps,
    MATERIAL_E_GLASS_FRP,
    MATERIAL_E_GLASS_EPOXY,
    MATERIAL_AL5083,
    MATERIAL_AL6061T6,
    MATERIAL_STEEL_S235,
    MATERIAL_STEEL_S355,
    DesignPressures,
    PlateResult,
    StiffenerResult,
    HullSectionProps,
    LongStrengthResult,
    ScantlingsReport,
    design_pressures_motor_craft,
    design_pressures_sailing_craft,
    plate_thickness,
    stiffener_section_modulus,
    longitudinal_strength_check,
    scantlings_report,
)

__all__ = [
    # seakeeping
    "HullSection",
    "GlobalMatrices",
    "RAOResult",
    "MotionStatistics",
    "compute_global_matrices",
    "compute_rao",
    "compute_response_statistics",
    "encounter_frequency",
    "jonswap_spectrum",
    "pierson_moskowitz_spectrum",
    "wigley_hull_sections",
    # scantlings
    "DesignCategory",
    "MaterialProps",
    "MATERIAL_E_GLASS_FRP",
    "MATERIAL_E_GLASS_EPOXY",
    "MATERIAL_AL5083",
    "MATERIAL_AL6061T6",
    "MATERIAL_STEEL_S235",
    "MATERIAL_STEEL_S355",
    "DesignPressures",
    "PlateResult",
    "StiffenerResult",
    "HullSectionProps",
    "LongStrengthResult",
    "ScantlingsReport",
    "design_pressures_motor_craft",
    "design_pressures_sailing_craft",
    "plate_thickness",
    "stiffener_section_modulus",
    "longitudinal_strength_check",
    "scantlings_report",
]
